// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.domain.usecase

import kotlinx.coroutines.flow.first
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.CruiseComparison
import org.jewzaam.cruiseweather.domain.model.CruiseWithPorts
import org.jewzaam.cruiseweather.domain.model.PortWithWeather
import javax.inject.Inject

class CompareCruisesUseCase @Inject constructor(
    private val cruiseRepository: CruiseRepository,
    private val weatherRepository: WeatherRepository,
    private val fetchWeatherUseCase: FetchWeatherForCruiseUseCase,
) {
    suspend operator fun invoke(cruiseIds: List<Long>): List<CruiseComparison> =
        cruiseIds.mapNotNull { cruiseId ->
            val cruiseWithPorts = cruiseRepository.getCruiseWithPorts(cruiseId).first()
                ?: return@mapNotNull null

            // Fetch any missing or stale weather data before comparing
            fetchWeatherUseCase(cruiseWithPorts = cruiseWithPorts)

            val portWithWeatherList = cruiseWithPorts.ports.map { port ->
                weatherRepository.getPortWithWeather(port.id)
                    ?: PortWithWeather(port = port, summary = null, years = emptyList())
            }

            val summaries = portWithWeatherList.mapNotNull { it.summary }
            if (summaries.isEmpty()) return@mapNotNull null

            val rainiestPort = portWithWeatherList
                .filter { it.summary != null }
                .maxByOrNull { it.summary?.rainProbabilityPct ?: 0.0 }

            val totalRainy = summaries.sumOf { it.rainyYearCount }
            val totalYears = summaries.sumOf { it.totalYearCount }

            CruiseComparison(
                cruise = cruiseWithPorts.cruise,
                avgTempHighF = summaries.map { it.avgTempHighF }.average(),
                avgTempLowF = summaries.map { it.avgTempLowF }.average(),
                rainProbabilityPct = if (totalYears > 0) totalRainy.toDouble() / totalYears * 100.0 else 0.0,
                avgPrecipMm = summaries.map { it.avgPrecipMm }.average(),
                avgWindMaxMph = summaries.map { it.avgWindMaxMph }.average(),
                avgUvIndexMax = summaries.map { it.avgUvIndexMax }.average(),
                avgHumidityPct = summaries.map { it.avgHumidityPct }.average(),
                avgSunshineMins = summaries.map { it.avgSunshineMins }.average(),
                avgSunriseMinutes = summaries.map { it.avgSunriseMinutes }.average(),
                avgSunsetMinutes = summaries.map { it.avgSunsetMinutes }.average(),
                rainiestPortName = rainiestPort?.port?.portName,
                rainiestPortRainPct = rainiestPort?.summary?.rainProbabilityPct,
                portBreakdowns = portWithWeatherList,
            )
        }
}
