// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.domain.usecase

import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.repository.WeatherFetchResult
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.CruiseWithPorts
import timber.log.Timber
import javax.inject.Inject

data class PortFetchResult(
    val port: PortOfCall,
    val result: WeatherFetchResult,
)

class FetchWeatherForCruiseUseCase @Inject constructor(
    private val weatherRepository: WeatherRepository,
) {
    suspend operator fun invoke(
        cruiseWithPorts: CruiseWithPorts,
        forceRefresh: Boolean = false,
    ): List<PortFetchResult> {
        val results = mutableListOf<PortFetchResult>()
        for (port in cruiseWithPorts.ports) {
            if (port.latitude == null || port.longitude == null) {
                Timber.w("Skipping port %d: no coordinates", port.id)
                results.add(PortFetchResult(port = port, result = WeatherFetchResult.NoCoordinates))
                continue
            }
            if (!forceRefresh && !weatherRepository.isFetchNeeded(port.id)) {
                Timber.d("Skipping port %d: data is fresh", port.id)
                continue
            }
            val result = weatherRepository.fetchWeatherForPort(port)
            results.add(PortFetchResult(port = port, result = result))
        }
        return results
    }
}
