// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.domain.usecase

import org.jewzaam.cruiseweather.data.repository.GeocodingRepository
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import javax.inject.Inject

class GeocodePortUseCase @Inject constructor(
    private val geocodingRepository: GeocodingRepository,
) {
    suspend operator fun invoke(query: String): Result<List<GeocodingCandidate>> =
        geocodingRepository.geocode(query)
}
