// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.data.local.entity

enum class CruiseLine(val displayName: String) {
    CARNIVAL("Carnival"),
    CELEBRITY("Celebrity Cruises"),
    DISNEY("Disney Cruise Line"),
    HOLLAND_AMERICA("Holland America Line"),
    MSC("MSC Cruises"),
    NCL("Norwegian Cruise Line"),
    PRINCESS("Princess Cruises"),
    ROYAL_CARIBBEAN("Royal Caribbean"),
    VIRGIN_VOYAGES("Virgin Voyages"),
    OTHER("Other"),
}
