// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.Instant
import java.time.LocalDate

@Entity(tableName = "cruises")
data class Cruise(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val sailDate: LocalDate,
    val returnDate: LocalDate,
    // Denormalized for fast list-screen display without joins.
    // Coordinates live on the PortOfCall rows (type = DEPARTURE / RETURN).
    val cruiseLine: String = "",
    val shipName: String = "",
    val departurePortName: String,
    val returnPortName: String? = null, // null = same port as departure
    val createdAt: Instant = Instant.now(),
    val updatedAt: Instant = Instant.now(),
)
