// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "port_weather_years",
    foreignKeys = [
        ForeignKey(
            entity = PortOfCall::class,
            parentColumns = ["id"],
            childColumns = ["portOfCallId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("portOfCallId")],
)
data class PortWeatherYear(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val portOfCallId: Long,
    val year: Int,
    val tempHighF: Double,
    val tempLowF: Double,
    val precipMm: Double,
    val precipHours: Double,
    val windMaxMph: Double,
    val windGustMph: Double,
    val humidityPct: Double,
    val uvIndexMax: Double,
    val sunshineDurationSec: Double,
)
