// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import java.time.Instant

@Entity(
    tableName = "port_weather_summaries",
    foreignKeys = [
        ForeignKey(
            entity = PortOfCall::class,
            parentColumns = ["id"],
            childColumns = ["portOfCallId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index(value = ["portOfCallId"], unique = true)],
)
data class PortWeatherSummary(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val portOfCallId: Long,
    val dataSource: String,         // "historical_avg"
    val yearsUsed: String,          // e.g. "2021,2022,2023,2024,2025"
    val avgTempHighF: Double,
    val avgTempLowF: Double,
    val tempHighMin: Double,        // lowest high across sampled years
    val tempHighMax: Double,        // highest high across sampled years
    val tempLowMin: Double,
    val tempLowMax: Double,
    val avgPrecipMm: Double,
    val avgPrecipHours: Double,
    val rainyYearCount: Int,        // years with >1mm precip
    val totalYearCount: Int,        // total years sampled
    val avgWindMaxMph: Double,
    val avgWindGustMph: Double,
    val avgHumidityPct: Double,
    val avgUvIndexMax: Double,
    val avgSunshineMins: Double,    // converted from seconds
    /** Average sunrise as minutes from midnight in local port timezone. */
    val avgSunriseMinutes: Double = 0.0,
    /** Average sunset as minutes from midnight in local port timezone. */
    val avgSunsetMinutes: Double = 0.0,
    val fetchedAt: Instant = Instant.now(),
) {
    /** Rain probability as a percentage (0–100), or null if no year data. */
    val rainProbabilityPct: Double?
        get() = if (totalYearCount > 0) rainyYearCount.toDouble() / totalYearCount * 100.0 else null

    /** Format minutes-from-midnight as "H:MM AM/PM". */
    val sunriseFormatted: String get() = formatMinutesAsTime(avgSunriseMinutes)
    val sunsetFormatted: String get() = formatMinutesAsTime(avgSunsetMinutes)
}

private fun formatMinutesAsTime(minutes: Double): String {
    val totalMins = minutes.toInt()
    val h = totalMins / 60
    val m = totalMins % 60
    val hour12 = if (h == 0) 12 else if (h > 12) h - 12 else h
    val amPm = if (h < 12) "AM" else "PM"
    return "%d:%02d %s".format(hour12, m, amPm)
}
