// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.remote.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class HistoricalWeatherResponse(
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val timezone: String? = null,
    val daily: DailyWeatherData? = null,
    val error: Boolean = false,
    val reason: String? = null,
)

@Serializable
data class DailyWeatherData(
    val time: List<String>,
    @SerialName("temperature_2m_max") val tempMaxF: List<Double?>,
    @SerialName("temperature_2m_min") val tempMinF: List<Double?>,
    @SerialName("precipitation_sum") val precipMm: List<Double?>,
    @SerialName("precipitation_hours") val precipHours: List<Double?>,
    @SerialName("wind_speed_10m_max") val windMaxMph: List<Double?>,
    @SerialName("wind_gusts_10m_max") val windGustMph: List<Double?>,
    @SerialName("relative_humidity_2m_mean") val humidityPct: List<Double?>,
    @SerialName("uv_index_max") val uvIndexMax: List<Double?>,
    @SerialName("sunshine_duration") val sunshineDurationSec: List<Double?>,
)
