// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruiselist

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.ListItem
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.CruiseLine
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle

private val DATE_FORMAT = DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CruiseListScreen(
    onAddCruise: () -> Unit,
    onCruiseClick: (Long) -> Unit,
    onCompareClick: () -> Unit,
    viewModel: CruiseListViewModel = hiltViewModel(),
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    Scaffold(
        topBar = { TopAppBar(title = { Text("Cruise Weather Planner") }) },
        floatingActionButton = {
            FloatingActionButton(onClick = onAddCruise) {
                Icon(imageVector = Icons.Default.Add, contentDescription = "Add cruise")
            }
        },
    ) { padding ->
        Column(modifier = Modifier.padding(padding)) {
            if (uiState.showCompareButton) {
                Button(
                    onClick = onCompareClick,
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 16.dp, vertical = 8.dp),
                ) {
                    Text("Compare Cruises")
                }
            }

            if (uiState.cruises.isEmpty()) {
                Box(
                    modifier = Modifier.fillMaxSize(),
                    contentAlignment = Alignment.Center,
                ) {
                    Text(
                        text = "No cruises yet.\nTap + to add your first cruise.",
                        style = MaterialTheme.typography.bodyLarge,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            } else {
                LazyColumn(modifier = Modifier.fillMaxSize()) {
                    items(items = uiState.cruises, key = { it.id }) { cruise ->
                        CruiseListItem(
                            cruise = cruise,
                            onClick = { onCruiseClick(cruise.id) },
                            onDelete = { viewModel.deleteCruise(cruise) },
                        )
                        HorizontalDivider()
                    }
                }
            }
        }
    }
}

@Composable
private fun CruiseListItem(
    cruise: Cruise,
    onClick: () -> Unit,
    onDelete: () -> Unit,
) {
    var showDeleteDialog by remember { mutableStateOf(false) }

    val cruiseLineDisplay = CruiseLine.entries.find { it.name == cruise.cruiseLine }?.displayName
    val shipLine = listOfNotNull(cruiseLineDisplay, cruise.shipName.takeIf { it.isNotBlank() })
        .joinToString(" \u2022 ")

    ListItem(
        headlineContent = { Text(cruise.name) },
        supportingContent = {
            Text(
                buildString {
                    if (shipLine.isNotBlank()) appendLine(shipLine)
                    append("${DATE_FORMAT.format(cruise.sailDate)} – ${DATE_FORMAT.format(cruise.returnDate)}")
                    append("\n${cruise.departurePortName}")
                },
            )
        },
        trailingContent = {
            IconButton(onClick = { showDeleteDialog = true }) {
                Icon(
                    imageVector = Icons.Default.Delete,
                    contentDescription = "Delete ${cruise.name}",
                )
            }
        },
        modifier = Modifier.clickable(onClick = onClick),
    )

    if (showDeleteDialog) {
        AlertDialog(
            onDismissRequest = { showDeleteDialog = false },
            title = { Text("Delete cruise?") },
            text = {
                Text("\"${cruise.name}\" and all its weather data will be permanently deleted.")
            },
            confirmButton = {
                TextButton(onClick = {
                    showDeleteDialog = false
                    onDelete()
                }) {
                    Text("Delete")
                }
            },
            dismissButton = {
                TextButton(onClick = { showDeleteDialog = false }) {
                    Text("Cancel")
                }
            },
        )
    }
}
