// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruiselist

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import javax.inject.Inject

data class CruiseListUiState(
    val cruises: List<Cruise> = emptyList(),
    val showCompareButton: Boolean = false,
)

@HiltViewModel
class CruiseListViewModel @Inject constructor(
    private val cruiseRepository: CruiseRepository,
) : ViewModel() {

    val uiState: StateFlow<CruiseListUiState> = cruiseRepository.getAllCruises()
        .map { cruises ->
            CruiseListUiState(
                cruises = cruises,
                showCompareButton = cruises.size >= 2,
            )
        }
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = CruiseListUiState(),
        )

    fun deleteCruise(cruise: Cruise) {
        viewModelScope.launch {
            cruiseRepository.deleteCruise(cruise)
        }
    }
}
