// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.repository

import org.jewzaam.cruiseweather.data.remote.OpenMeteoApi
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

// GeoNames feature codes for non-populated-place features to exclude
private val EXCLUDED_FEATURE_CODES = setOf(
    "AIRP", "AIRF", "AIRH", "AIRB", "AIRT", // airports/airfields
    "RSTN", "RSTP", "RSTE",                   // railway stations
    "PRT", "BRKS", "MILB",                    // ports (commercial), barracks, military
)

@Singleton
class GeocodingRepository @Inject constructor(
    private val api: OpenMeteoApi,
) {
    suspend fun geocode(query: String): Result<List<GeocodingCandidate>> = runCatching {
        val response = api.geocode(query = query, count = 10)
        val allResults = response.results ?: emptyList()

        // Filter out airports/stations, but fall back to unfiltered if nothing remains
        val filtered = allResults.filter { result ->
            val code = result.featureCode ?: ""
            code !in EXCLUDED_FEATURE_CODES
        }
        val results = filtered.ifEmpty { allResults }

        val candidates = results
            .take(5)
            .map { result ->
                val parts = listOfNotNull(result.name, result.admin1, result.country)
                GeocodingCandidate(
                    id = result.id,
                    displayName = parts.joinToString(", "),
                    latitude = result.latitude,
                    longitude = result.longitude,
                )
            }
        Timber.i("Geocode: query=%s candidates=%d (filtered=%d total=%d)", query, candidates.size, filtered.size, allResults.size)
        candidates
    }.onFailure { e ->
        Timber.e(e, "Geocoding failed: query=%s", query)
    }
}
