// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.repository

import androidx.room.withTransaction
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import org.jewzaam.cruiseweather.data.local.AppDatabase
import org.jewzaam.cruiseweather.data.local.PortOfCallDao
import org.jewzaam.cruiseweather.data.local.WeatherDao
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherYear
import org.jewzaam.cruiseweather.data.remote.OpenMeteoApi
import org.jewzaam.cruiseweather.data.remote.dto.DailyWeatherData
import org.jewzaam.cruiseweather.domain.model.PortWithWeather
import timber.log.Timber
import java.time.Instant
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import javax.inject.Inject
import javax.inject.Singleton

private const val HISTORICAL_YEARS = 5
private const val WEATHER_WINDOW_DAYS = 2L // ±2 days = 5-day window
private const val RAINY_THRESHOLD_MM = 1.0
private val DATE_FORMAT = DateTimeFormatter.ISO_LOCAL_DATE

sealed class WeatherFetchResult {
    data object Success : WeatherFetchResult()
    data class PartialSuccess(val fetchedYears: Int, val totalYears: Int) : WeatherFetchResult()
    data class Failure(val message: String) : WeatherFetchResult()
    data object NoCoordinates : WeatherFetchResult()
}

@Singleton
class WeatherRepository @Inject constructor(
    private val db: AppDatabase,
    private val weatherDao: WeatherDao,
    private val portOfCallDao: PortOfCallDao,
    private val api: OpenMeteoApi,
) {
    fun getSummaryForPort(portId: Long): Flow<PortWeatherSummary?> =
        weatherDao.getSummaryForPort(portId)

    fun getYearDataForPort(portId: Long): Flow<List<PortWeatherYear>> =
        weatherDao.getYearDataForPort(portId)

    suspend fun getPortWithWeather(portId: Long): PortWithWeather? {
        val port = portOfCallDao.getPortById(portId) ?: return null
        val summary = weatherDao.getSummaryForPortOnce(portId)
        val years = weatherDao.getYearDataForPortOnce(portId)
        return PortWithWeather(port = port, summary = summary, years = years)
    }

    suspend fun isFetchNeeded(portId: Long): Boolean {
        // Historical weather doesn't change — only fetch if no data exists
        return weatherDao.getSummaryForPortOnce(portId) == null
    }

    suspend fun fetchWeatherForPort(port: PortOfCall): WeatherFetchResult {
        val lat = port.latitude
        val lon = port.longitude
        if (lat == null || lon == null) {
            Timber.w("Port %d has no resolved coordinates, skipping weather fetch", port.id)
            return WeatherFetchResult.NoCoordinates
        }

        Timber.i(
            "Fetching weather: portId=%d name=%s lat=%f lon=%f",
            port.id,
            port.portName,
            lat,
            lon,
        )

        val targetDate = port.date
        val currentYear = LocalDate.now().year
        val yearsToFetch = (1..HISTORICAL_YEARS).map { currentYear - it }

        val fetchedYears = mutableListOf<PortWeatherYear>()
        for (year in yearsToFetch) {
            val centerDate = buildDateForYear(targetDate = targetDate, year = year)
            if (centerDate == null) {
                Timber.w("Skipping year %d for portId=%d: leap-year date", year, port.id)
                continue
            }
            val windowStart = centerDate.minusDays(WEATHER_WINDOW_DAYS)
            val windowEnd = centerDate.plusDays(WEATHER_WINDOW_DAYS)
            val startStr = DATE_FORMAT.format(windowStart)
            val endStr = DATE_FORMAT.format(windowEnd)
            try {
                val response = api.fetchHistoricalWeather(
                    latitude = lat,
                    longitude = lon,
                    startDate = startStr,
                    endDate = endStr,
                )
                if (response.error) {
                    Timber.w("API error: portId=%d year=%d reason=%s", port.id, year, response.reason)
                    continue
                }
                val daily = response.daily ?: continue
                if (daily.time.isEmpty()) continue

                val weatherYear = buildWeatherYear(portId = port.id, year = year, daily = daily)
                if (weatherYear != null) {
                    fetchedYears.add(weatherYear)
                }
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                Timber.e(e, "Weather fetch failed: portId=%d year=%d", port.id, year)
            }
        }

        if (fetchedYears.isEmpty()) {
            return WeatherFetchResult.Failure("No data available for any sampled year")
        }

        val summary = computeSummary(portId = port.id, years = fetchedYears)
        db.withTransaction {
            weatherDao.deleteWeatherYearsForPort(port.id)
            weatherDao.deleteSummaryForPort(port.id)
            weatherDao.insertWeatherYears(fetchedYears)
            weatherDao.insertSummary(summary)
        }

        Timber.i("Weather fetch complete: portId=%d yearsStored=%d", port.id, fetchedYears.size)

        return if (fetchedYears.size == HISTORICAL_YEARS) {
            WeatherFetchResult.Success
        } else {
            WeatherFetchResult.PartialSuccess(
                fetchedYears = fetchedYears.size,
                totalYears = HISTORICAL_YEARS,
            )
        }
    }

    private fun buildDateForYear(targetDate: LocalDate, year: Int): LocalDate? =
        try {
            targetDate.withYear(year)
        } catch (_: Exception) {
            // Feb 29 in non-leap years
            null
        }

    private fun buildWeatherYear(portId: Long, year: Int, daily: DailyWeatherData): PortWeatherYear? {
        val highs = daily.tempMaxF.filterNotNull()
        val lows = daily.tempMinF.filterNotNull()
        if (highs.isEmpty() || lows.isEmpty()) return null
        return PortWeatherYear(
            portOfCallId = portId,
            year = year,
            tempHighF = highs.average(),
            tempLowF = lows.average(),
            precipMm = daily.precipMm.filterNotNull().averageOrZero(),
            precipHours = daily.precipHours.filterNotNull().averageOrZero(),
            windMaxMph = daily.windMaxMph.filterNotNull().averageOrZero(),
            windGustMph = daily.windGustMph.filterNotNull().averageOrZero(),
            humidityPct = daily.humidityPct.filterNotNull().averageOrZero(),
            uvIndexMax = daily.uvIndexMax.filterNotNull().averageOrZero(),
            sunshineDurationSec = daily.sunshineDurationSec.filterNotNull().averageOrZero(),
        )
    }

    private fun List<Double>.averageOrZero(): Double = if (isEmpty()) 0.0 else average()

    private fun computeSummary(portId: Long, years: List<PortWeatherYear>): PortWeatherSummary {
        val rainyCount = years.count { it.precipMm > RAINY_THRESHOLD_MM }
        return PortWeatherSummary(
            portOfCallId = portId,
            dataSource = "historical_avg",
            yearsUsed = years.map { it.year }.sorted().joinToString(","),
            avgTempHighF = years.map { it.tempHighF }.average(),
            avgTempLowF = years.map { it.tempLowF }.average(),
            tempHighMin = years.minOf { it.tempHighF },
            tempHighMax = years.maxOf { it.tempHighF },
            tempLowMin = years.minOf { it.tempLowF },
            tempLowMax = years.maxOf { it.tempLowF },
            avgPrecipMm = years.map { it.precipMm }.average(),
            avgPrecipHours = years.map { it.precipHours }.average(),
            rainyYearCount = rainyCount,
            totalYearCount = years.size,
            avgWindMaxMph = years.map { it.windMaxMph }.average(),
            avgWindGustMph = years.map { it.windGustMph }.average(),
            avgHumidityPct = years.map { it.humidityPct }.average(),
            avgUvIndexMax = years.map { it.uvIndexMax }.average(),
            avgSunshineMins = years.map { it.sunshineDurationSec / 60.0 }.average(),
            fetchedAt = Instant.now(),
        )
    }
}
