// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruisedetail

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Add
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.ui.components.LoadingOverlay
import org.jewzaam.cruiseweather.ui.cruiseedit.PortOfCallSheet
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle
import java.time.temporal.ChronoUnit

private val DATE_FORMAT = DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CruiseDetailScreen(
    cruiseId: Long,
    onNavigateUp: () -> Unit,
    onEditCruise: () -> Unit,
    viewModel: CruiseDetailViewModel = hiltViewModel(),
) {
    LaunchedEffect(cruiseId) {
        viewModel.loadCruise(cruiseId)
    }

    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
    val snackbarHostState = remember { SnackbarHostState() }
    var editingPort by remember { mutableStateOf<PortOfCall?>(null) }
    var addingPortOnDate by remember { mutableStateOf<java.time.LocalDate?>(null) }

    LaunchedEffect(uiState.fetchMessage) {
        uiState.fetchMessage?.let { msg ->
            snackbarHostState.showSnackbar(msg)
            viewModel.clearMessage()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text(uiState.cruiseWithPorts?.cruise?.name ?: "")
                        uiState.cruiseWithPorts?.cruise?.let { cruise ->
                            Text(
                                text = "${DATE_FORMAT.format(cruise.sailDate)} – ${DATE_FORMAT.format(cruise.returnDate)}",
                                style = MaterialTheme.typography.bodySmall,
                            )
                        }
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onNavigateUp) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Navigate up",
                        )
                    }
                },
            )
        },
        snackbarHost = { SnackbarHost(snackbarHostState) },
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .fillMaxSize()
                .verticalScroll(rememberScrollState()),
        ) {
            // Action buttons
            Row(modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp)) {
                OutlinedButton(onClick = onEditCruise) { Text("Edit") }
                Spacer(modifier = Modifier.weight(1f))
                Button(
                    onClick = { viewModel.fetchWeather(forceRefresh = true) },
                    enabled = !uiState.isFetchingWeather,
                ) {
                    Text("Refresh Weather")
                }
            }

            // Day-by-day itinerary with sea day gaps
            val cruiseWithPorts = uiState.cruiseWithPorts
            if (cruiseWithPorts != null) {
                val cruise = cruiseWithPorts.cruise
                val portsByDate = cruiseWithPorts.allPortsChronological
                    .groupBy { it.date }
                val totalDays = ChronoUnit.DAYS.between(cruise.sailDate, cruise.returnDate).toInt() + 1
                for (dayIndex in 0 until totalDays) {
                    val date = cruise.sailDate.plusDays(dayIndex.toLong())
                    val dayNumber = dayIndex + 1
                    val portsOnDay = portsByDate[date]
                    if (portsOnDay != null) {
                        portsOnDay.forEach { port ->
                            WeatherCard(
                                port = port,
                                summary = uiState.portWeather[port.id],
                                dayNumber = dayNumber,
                                modifier = if (port.type == PortType.PORT_OF_CALL) {
                                    Modifier.clickable { editingPort = port }
                                } else Modifier,
                            )
                        }
                    } else {
                        SeaDayRow(
                            dayNumber = dayNumber,
                            onAddPort = { addingPortOnDate = date },
                        )
                    }
                }

                Spacer(modifier = Modifier.height(8.dp))

                Text(
                    text = "* Based on historical 5-year averages (±2 day window)",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(horizontal = 16.dp),
                )
            }
        }

        if (uiState.isFetchingWeather) {
            LoadingOverlay(message = "Fetching weather data…")
        }
    }

    editingPort?.let { port ->
        val cruise = uiState.cruiseWithPorts?.cruise ?: return@let
        PortOfCallSheet(
            cruiseId = cruise.id,
            sailDate = cruise.sailDate,
            returnDate = cruise.returnDate,
            existingPort = port,
            onSave = { updated -> viewModel.updatePortOfCall(updated) },
            onDelete = { deleted -> viewModel.deletePortOfCall(deleted.id) },
            onDismiss = { editingPort = null },
            onGeocode = { query -> viewModel.geocodeQuery(query) },
        )
    }

    addingPortOnDate?.let { targetDate ->
        val cruise = uiState.cruiseWithPorts?.cruise ?: return@let
        PortOfCallSheet(
            cruiseId = cruise.id,
            sailDate = cruise.sailDate,
            returnDate = cruise.returnDate,
            lastPortDate = targetDate.minusDays(1),
            onSave = { port -> viewModel.addPortOfCall(port) },
            onDismiss = { addingPortOnDate = null },
            onGeocode = { query -> viewModel.geocodeQuery(query) },
        )
    }
}

@Composable
private fun SeaDayRow(dayNumber: Int, onAddPort: () -> Unit) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 24.dp, vertical = 2.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(
            text = "Day $dayNumber  •  At Sea",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = Modifier.weight(1f),
        )
        TextButton(
            onClick = onAddPort,
        ) {
            Icon(
                imageVector = Icons.Default.Add,
                contentDescription = "Add port on day $dayNumber",
                modifier = Modifier.padding(end = 4.dp),
            )
            Text("Add Port", style = MaterialTheme.typography.labelSmall)
        }
    }
}
