// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruisedetail

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherFetchResult
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.CruiseWithPorts
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import org.jewzaam.cruiseweather.domain.usecase.FetchWeatherForCruiseUseCase
import org.jewzaam.cruiseweather.domain.usecase.GeocodePortUseCase
import timber.log.Timber
import javax.inject.Inject

data class CruiseDetailUiState(
    val cruiseWithPorts: CruiseWithPorts? = null,
    val portWeather: Map<Long, PortWeatherSummary> = emptyMap(),
    val isFetchingWeather: Boolean = false,
    val fetchMessage: String? = null,
    val error: String? = null,
)

@HiltViewModel
class CruiseDetailViewModel @Inject constructor(
    private val cruiseRepository: CruiseRepository,
    private val weatherRepository: WeatherRepository,
    private val fetchWeatherUseCase: FetchWeatherForCruiseUseCase,
    private val geocodePortUseCase: GeocodePortUseCase,
) : ViewModel() {

    private val _uiState = MutableStateFlow(CruiseDetailUiState())
    val uiState: StateFlow<CruiseDetailUiState> = _uiState

    private var collectJob: Job? = null

    fun loadCruise(cruiseId: Long) {
        collectJob?.cancel()
        collectJob = viewModelScope.launch {
            var hasAutoFetched = false
            Timber.d("loadCruise(%d) started, new collect session", cruiseId)
            cruiseRepository.getCruiseWithPorts(cruiseId).collect { cruiseWithPorts ->
                if (cruiseWithPorts == null) return@collect
                Timber.d("loadCruise(%d) emission received, hasAutoFetched=%b", cruiseId, hasAutoFetched)
                val portWeather = buildPortWeatherMap(cruiseWithPorts)
                _uiState.update { it.copy(cruiseWithPorts = cruiseWithPorts, portWeather = portWeather) }
                if (!hasAutoFetched) {
                    hasAutoFetched = true
                    val portsNeedingFetch = cruiseWithPorts.ports.filter { port ->
                        port.latitude != null && weatherRepository.isFetchNeeded(port.id)
                    }
                    if (portsNeedingFetch.isNotEmpty()) {
                        Timber.d("Auto-fetch triggered for %d ports: %s",
                            portsNeedingFetch.size,
                            portsNeedingFetch.joinToString { "${it.id}:${it.portName}" })
                        fetchWeather()
                    } else {
                        Timber.d("No auto-fetch needed, all ports have fresh weather")
                    }
                }
            }
        }
    }

    private suspend fun buildPortWeatherMap(
        cruiseWithPorts: CruiseWithPorts,
    ): Map<Long, PortWeatherSummary> =
        cruiseWithPorts.ports.mapNotNull { port ->
            // One-shot snapshot — historical data doesn't change after fetch
            val summary = weatherRepository.getPortWithWeather(port.id)?.summary
            if (summary != null) port.id to summary else null
        }.toMap()

    fun fetchWeather(forceRefresh: Boolean = false) {
        val cruiseWithPorts = _uiState.value.cruiseWithPorts ?: return
        Timber.d("fetchWeather called, forceRefresh=%b, caller=%s",
            forceRefresh, Throwable().stackTrace[1])
        viewModelScope.launch {
            _uiState.update { it.copy(isFetchingWeather = true, fetchMessage = null, error = null) }
            val results = fetchWeatherUseCase(
                cruiseWithPorts = cruiseWithPorts,
                forceRefresh = forceRefresh,
            )
            val failures = results.count { it.result is WeatherFetchResult.Failure }
            val noCoords = results.count { it.result is WeatherFetchResult.NoCoordinates }
            val message = when {
                results.isEmpty() -> "All weather data is up to date"
                failures > 0 -> "$failures port(s) failed to fetch weather"
                noCoords > 0 -> "$noCoords port(s) have no geocoded location — geocode them first"
                else -> "Weather updated successfully"
            }
            // Refresh port weather map after fetch
            val updated = buildPortWeatherMap(cruiseWithPorts)
            _uiState.update { it.copy(isFetchingWeather = false, fetchMessage = message, portWeather = updated) }
        }
    }

    fun addPortOfCall(port: PortOfCall) {
        viewModelScope.launch {
            try {
                // Check for existing SEA_DAY on the same date — transfer notes and remove it
                val existingSeaDay = _uiState.value.cruiseWithPorts?.ports
                    ?.firstOrNull { it.date == port.date && it.type == PortType.SEA_DAY }
                val portWithNotes = if (existingSeaDay != null && existingSeaDay.notes.isNotBlank() && port.notes.isBlank()) {
                    port.copy(notes = existingSeaDay.notes)
                } else {
                    port
                }
                val id = cruiseRepository.addPortOfCall(portWithNotes)
                if (existingSeaDay != null) {
                    cruiseRepository.deletePortOfCall(existingSeaDay.id)
                }
                fetchWeatherForPort(portWithNotes.copy(id = id))
            } catch (e: Exception) {
                _uiState.update { it.copy(error = e.message ?: "Failed to add port") }
            }
        }
    }

    fun updatePortOfCall(port: PortOfCall) {
        viewModelScope.launch {
            try {
                val oldPort = _uiState.value.cruiseWithPorts?.ports?.find { it.id == port.id }
                cruiseRepository.updatePortOfCall(port)
                val coordsChanged = oldPort == null
                    || oldPort.latitude != port.latitude
                    || oldPort.longitude != port.longitude
                    || oldPort.date != port.date
                if (coordsChanged) {
                    fetchWeatherForPort(port)
                }
            } catch (e: Exception) {
                _uiState.update { it.copy(error = e.message ?: "Failed to update port") }
            }
        }
    }

    fun deletePortOfCall(portId: Long) {
        viewModelScope.launch {
            try {
                cruiseRepository.deletePortOfCall(portId)
            } catch (e: Exception) {
                _uiState.update { it.copy(error = e.message ?: "Failed to delete port") }
            }
        }
    }

    private fun fetchWeatherForPort(port: PortOfCall) {
        if (port.latitude == null || port.longitude == null) return
        viewModelScope.launch {
            _uiState.update { it.copy(isFetchingWeather = true) }
            weatherRepository.fetchWeatherForPort(port)
            val cruiseWithPorts = _uiState.value.cruiseWithPorts
            if (cruiseWithPorts != null) {
                val updated = buildPortWeatherMap(cruiseWithPorts)
                _uiState.update { it.copy(isFetchingWeather = false, portWeather = updated) }
            } else {
                _uiState.update { it.copy(isFetchingWeather = false) }
            }
        }
    }

    suspend fun geocodeQuery(query: String): List<GeocodingCandidate> =
        geocodePortUseCase(query = query).getOrDefault(emptyList())

    fun clearMessage() = _uiState.update { it.copy(fetchMessage = null, error = null) }
}
