// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.ui.cruisedetail

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherFetchResult
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.CruiseWithPorts
import org.jewzaam.cruiseweather.domain.usecase.FetchWeatherForCruiseUseCase
import timber.log.Timber
import javax.inject.Inject

data class CruiseDetailUiState(
    val cruiseWithPorts: CruiseWithPorts? = null,
    val portWeather: Map<Long, PortWeatherSummary> = emptyMap(),
    val isFetchingWeather: Boolean = false,
    val fetchMessage: String? = null,
    val error: String? = null,
)

@HiltViewModel
class CruiseDetailViewModel @Inject constructor(
    private val cruiseRepository: CruiseRepository,
    private val weatherRepository: WeatherRepository,
    private val fetchWeatherUseCase: FetchWeatherForCruiseUseCase,
) : ViewModel() {

    private val _uiState = MutableStateFlow(CruiseDetailUiState())
    val uiState: StateFlow<CruiseDetailUiState> = _uiState.asStateFlow()

    private var collectJob: Job? = null

    fun loadCruise(cruiseId: Long) {
        collectJob?.cancel()
        collectJob = viewModelScope.launch {
            var hasAutoFetched = false
            Timber.d("loadCruise(%d) started, new collect session", cruiseId)
            cruiseRepository.getCruiseWithPorts(cruiseId).collect { cruiseWithPorts ->
                if (cruiseWithPorts == null) return@collect
                Timber.d("loadCruise(%d) emission received, hasAutoFetched=%b", cruiseId, hasAutoFetched)
                val portWeather = buildPortWeatherMap(cruiseWithPorts)
                _uiState.update { it.copy(cruiseWithPorts = cruiseWithPorts, portWeather = portWeather) }
                if (!hasAutoFetched) {
                    hasAutoFetched = true
                    val portsNeedingFetch = cruiseWithPorts.ports.filter { port ->
                        port.latitude != null && weatherRepository.isFetchNeeded(port.id)
                    }
                    if (portsNeedingFetch.isNotEmpty()) {
                        Timber.d("Auto-fetch triggered for %d ports: %s",
                            portsNeedingFetch.size,
                            portsNeedingFetch.joinToString { "${it.id}:${it.portName}" })
                        fetchWeather()
                    } else {
                        Timber.d("No auto-fetch needed, all ports have fresh weather")
                    }
                }
            }
        }
    }

    private suspend fun buildPortWeatherMap(
        cruiseWithPorts: CruiseWithPorts,
    ): Map<Long, PortWeatherSummary> =
        cruiseWithPorts.ports.mapNotNull { port ->
            val summary = weatherRepository.getPortWithWeather(port.id)?.summary
            if (summary != null) port.id to summary else null
        }.toMap()

    fun fetchWeather(forceRefresh: Boolean = false) {
        val cruiseWithPorts = _uiState.value.cruiseWithPorts ?: return
        Timber.d("fetchWeather called, forceRefresh=%b", forceRefresh)
        viewModelScope.launch {
            _uiState.update { it.copy(isFetchingWeather = true, fetchMessage = null, error = null) }
            val results = fetchWeatherUseCase(
                cruiseWithPorts = cruiseWithPorts,
                forceRefresh = forceRefresh,
            )
            val failures = results.count { it.result is WeatherFetchResult.Failure }
            val noCoords = results.count { it.result is WeatherFetchResult.NoCoordinates }
            val message = when {
                results.isEmpty() -> "All weather data is up to date"
                failures > 0 -> "$failures port(s) failed to fetch weather"
                noCoords > 0 -> "$noCoords port(s) have no geocoded location — geocode them first"
                else -> "Weather updated successfully"
            }
            val updated = buildPortWeatherMap(cruiseWithPorts)
            _uiState.update { it.copy(isFetchingWeather = false, fetchMessage = message, portWeather = updated) }
        }
    }

    fun updatePortOfCall(port: PortOfCall) {
        viewModelScope.launch {
            try {
                cruiseRepository.updatePortOfCall(port)
            } catch (e: Exception) {
                _uiState.update { it.copy(error = e.message ?: "Failed to update port") }
            }
        }
    }

    fun clearMessage() = _uiState.update { it.copy(fetchMessage = null, error = null) }
}
