// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.ui.cruisedetail

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.jewzaam.cruiseweather.data.local.entity.CruiseLine
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.ui.components.LoadingOverlay
import java.time.LocalDate
import java.time.temporal.ChronoUnit

private val DATE_FORMAT = org.jewzaam.cruiseweather.ui.util.DateFormatters.MEDIUM_DATE

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CruiseDetailScreen(
    cruiseId: Long,
    onNavigateUp: () -> Unit,
    onEditCruise: () -> Unit,
    viewModel: CruiseDetailViewModel = hiltViewModel(),
) {
    LaunchedEffect(cruiseId) {
        viewModel.loadCruise(cruiseId)
    }

    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
    val snackbarHostState = remember { SnackbarHostState() }
    var expandedPortLocalId by remember { mutableStateOf<String?>(null) }
    var editingNotesPort by remember { mutableStateOf<PortOfCall?>(null) }

    LaunchedEffect(uiState.fetchMessage) {
        uiState.fetchMessage?.let { msg ->
            snackbarHostState.showSnackbar(msg)
            viewModel.clearMessage()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text(uiState.cruiseWithPorts?.cruise?.name ?: "")
                        uiState.cruiseWithPorts?.cruise?.let { cruise ->
                            Text(
                                text = "${DATE_FORMAT.format(cruise.sailDate)} – ${DATE_FORMAT.format(cruise.returnDate)}",
                                style = MaterialTheme.typography.bodySmall,
                            )
                        }
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onNavigateUp) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Navigate up",
                        )
                    }
                },
            )
        },
        snackbarHost = { SnackbarHost(snackbarHostState) },
    ) { padding ->
        val scrollState = rememberScrollState()
        Column(
            modifier = Modifier
                .padding(padding)
                .fillMaxSize()
                .verticalScroll(scrollState),
        ) {
            // Action buttons
            Row(modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp)) {
                OutlinedButton(onClick = onEditCruise) { Text("Edit") }
                Spacer(modifier = Modifier.weight(1f))
                Button(
                    onClick = { viewModel.fetchWeather(forceRefresh = true) },
                    enabled = !uiState.isFetchingWeather,
                ) {
                    Text("Refresh Weather")
                }
            }

            // Cruise metadata
            val cruiseWithPorts = uiState.cruiseWithPorts
            if (cruiseWithPorts != null) {
                val cruise = cruiseWithPorts.cruise
                val cruiseLineDisplay = CruiseLine.entries.find { it.name == cruise.cruiseLine }?.displayName
                val metaParts = listOfNotNull(
                    cruiseLineDisplay,
                    cruise.shipName.takeIf { it.isNotBlank() },
                )
                if (metaParts.isNotEmpty()) {
                    Text(
                        text = metaParts.joinToString("  \u2022  "),
                        style = MaterialTheme.typography.bodyMedium,
                        modifier = Modifier.padding(horizontal = 16.dp, vertical = 4.dp),
                    )
                }

                // Day-by-day itinerary (read-only, notes editable)
                val portsByDate = cruiseWithPorts.allPortsChronological
                    .groupBy { it.date }
                val totalDays = ChronoUnit.DAYS.between(cruise.sailDate, cruise.returnDate).toInt() + 1
                for (dayIndex in 0 until totalDays) {
                    val date = cruise.sailDate.plusDays(dayIndex.toLong())
                    val dayNumber = dayIndex + 1
                    val portsOnDay = portsByDate[date]
                    val seaDays = portsOnDay?.filter { it.type == PortType.SEA_DAY }
                    val realPorts = portsOnDay?.filter { it.type != PortType.SEA_DAY }

                    if (!realPorts.isNullOrEmpty()) {
                        realPorts.forEach { port ->
                            val isExpanded = expandedPortLocalId == port.localId
                            WeatherCard(
                                port = port,
                                summary = uiState.portWeather[port.id],
                                dayNumber = dayNumber,
                                isExpanded = isExpanded,
                                onNote = { editingNotesPort = port },
                                scrollState = scrollState,
                                modifier = Modifier.clickable {
                                    expandedPortLocalId = if (isExpanded) null else port.localId
                                },
                            )
                        }
                    } else {
                        val seaDayEntity = seaDays?.firstOrNull()
                        SeaDayRow(
                            dayNumber = dayNumber,
                            date = date,
                            notes = seaDayEntity?.notes?.takeIf { it.isNotBlank() },
                            onAddNote = if (seaDayEntity != null) {
                                { editingNotesPort = seaDayEntity }
                            } else null,
                        )
                    }
                }

                Spacer(modifier = Modifier.height(8.dp))

                Text(
                    text = "* Based on historical 5-year averages (±2 day window)",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(horizontal = 16.dp),
                )
            }
        }

        if (uiState.isFetchingWeather) {
            LoadingOverlay(message = "Fetching weather data…")
        }
    }

    // Notes-only editing dialog
    editingNotesPort?.let { port ->
        val cruise = uiState.cruiseWithPorts?.cruise ?: return@let
        NotesDialog(
            port = port,
            sailDate = cruise.sailDate,
            onSave = { newNotes ->
                viewModel.updatePortOfCall(port.copy(notes = newNotes))
                editingNotesPort = null
            },
            onDismiss = { editingNotesPort = null },
        )
    }
}

@Composable
private fun SeaDayRow(
    dayNumber: Int,
    date: LocalDate,
    notes: String? = null,
    onAddNote: (() -> Unit)? = null,
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 24.dp, vertical = 2.dp),
    ) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Text(
                text = "Day $dayNumber  •  ${DATE_FORMAT.format(date)}  •  At Sea",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.weight(1f),
            )
            if (onAddNote != null) {
                TextButton(onClick = onAddNote) {
                    Text("Note", style = MaterialTheme.typography.labelSmall)
                }
            }
        }
        if (notes != null) {
            Text(
                text = notes,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.padding(start = 8.dp, bottom = 4.dp),
            )
        }
    }
}
