// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruisedetail

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.ScrollState
import androidx.compose.ui.layout.onGloballyPositioned
import androidx.compose.ui.layout.positionInParent
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.ui.components.deriveWeatherCondition
import org.jewzaam.cruiseweather.ui.components.toEmoji
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.temporal.ChronoUnit
import kotlin.math.roundToInt

private val DAY_FORMAT = DateTimeFormatter.ofPattern("MMM d")

@Composable
fun WeatherCard(
    port: PortOfCall?,
    summary: PortWeatherSummary?,
    dayNumber: Int,
    isExpanded: Boolean = false,
    onEdit: (() -> Unit)? = null,
    scrollState: ScrollState? = null,
    modifier: Modifier = Modifier,
) {
    val condition = deriveWeatherCondition(summary)
    val isDepartureOrReturn = port?.type == PortType.DEPARTURE || port?.type == PortType.RETURN
    val isSeaDay = port?.type == PortType.SEA_DAY
    var cardBottomY by remember { mutableStateOf(0) }

    // Auto-scroll so the bottom of the expanded card is visible
    LaunchedEffect(isExpanded) {
        if (isExpanded && scrollState != null) {
            // Small delay to let AnimatedVisibility measure
            kotlinx.coroutines.delay(300)
            val viewportBottom = scrollState.value + scrollState.viewportSize
            if (cardBottomY > viewportBottom) {
                scrollState.animateScrollTo(scrollState.value + (cardBottomY - viewportBottom) + 32)
            }
        }
    }

    Card(
        modifier = modifier
            .fillMaxWidth()
            .padding(horizontal = 12.dp, vertical = 4.dp)
            .onGloballyPositioned { coords ->
                cardBottomY = (coords.positionInParent().y + coords.size.height).toInt()
            },
        colors = CardDefaults.cardColors(
            containerColor = when {
                isDepartureOrReturn -> MaterialTheme.colorScheme.primaryContainer
                isSeaDay -> MaterialTheme.colorScheme.surface
                else -> MaterialTheme.colorScheme.surfaceVariant
            },
        ),
    ) {
        Column(modifier = Modifier.padding(12.dp)) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                // Left: day number + date + port name + type label
                Column(modifier = Modifier.weight(1f)) {
                    val typeLabel = port?.let {
                        when (it.type) {
                            PortType.DEPARTURE -> "Embark"
                            PortType.RETURN -> "Debark"
                            PortType.SEA_DAY -> "At Sea"
                            else -> null
                        }
                    }
                    val portName = if (isSeaDay) "At Sea" else port?.portName ?: ""
                    val dateText = port?.let { DAY_FORMAT.format(it.date) } ?: ""
                    Text(
                        text = "Day $dayNumber  •  $dateText" + if (typeLabel != null) "  •  $typeLabel" else "",
                        style = MaterialTheme.typography.labelSmall,
                        color = if (isDepartureOrReturn) {
                            MaterialTheme.colorScheme.onPrimaryContainer
                        } else {
                            MaterialTheme.colorScheme.onSurfaceVariant
                        },
                    )
                    if (!isSeaDay) {
                        Text(
                            text = portName,
                            style = MaterialTheme.typography.bodyLarge,
                            fontWeight = FontWeight.SemiBold,
                        )
                    }
                }

                // Right: 3-row weather summary (not for sea days)
                if (summary != null && !isSeaDay) {
                    Column(horizontalAlignment = Alignment.End) {
                        Text(
                            text = "${condition.toEmoji()} ${"%.0f".format(summary.avgTempHighF)}°/${"%.0f".format(summary.avgTempLowF)}°F",
                            style = MaterialTheme.typography.bodyMedium,
                            fontWeight = FontWeight.SemiBold,
                        )
                        val rainPct = (summary.rainProbabilityPct ?: 0.0).toInt()
                        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                            Text(text = "Rain $rainPct%", style = MaterialTheme.typography.bodySmall)
                            Text(text = "Hum ${"%.0f".format(summary.avgHumidityPct)}%", style = MaterialTheme.typography.bodySmall)
                        }
                        val moonEmoji = port?.date?.let { moonPhaseEmoji(it) } ?: ""
                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            Text(
                                text = "\u2600${summary.sunriseFormatted}  \u263E${summary.sunsetFormatted}",
                                style = MaterialTheme.typography.bodySmall,
                            )
                            if (moonEmoji.isNotEmpty()) {
                                Text(text = moonEmoji, style = MaterialTheme.typography.bodySmall)
                            }
                        }
                    }
                } else if (!isSeaDay && summary == null) {
                    Text(
                        text = "No data",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            }

            // Notes preview (collapsed — show first line if present)
            if (!isExpanded && !port?.notes.isNullOrBlank()) {
                Text(
                    text = port!!.notes.lines().first(),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    maxLines = 1,
                )
            }

            // Expanded details — bringIntoViewRequester attached here
            AnimatedVisibility(visible = isExpanded) {
                Column {
                    if (summary != null && !isSeaDay) {
                        HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp))
                        ExpandedWeatherDetails(summary = summary)
                    }
                    // Notes section
                    HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp))
                    if (port?.notes.isNullOrBlank()) {
                        Text(
                            text = "No notes",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                    } else {
                        Text(
                            text = port!!.notes,
                            style = MaterialTheme.typography.bodySmall,
                        )
                    }
                    if (onEdit != null) {
                        Spacer(modifier = Modifier.height(4.dp))
                        TextButton(onClick = onEdit) {
                            Icon(
                                imageVector = Icons.Default.Edit,
                                contentDescription = "Edit",
                                modifier = Modifier.padding(end = 4.dp),
                            )
                            Text("Edit")
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun ExpandedWeatherDetails(summary: PortWeatherSummary) {
    Column(verticalArrangement = Arrangement.spacedBy(2.dp)) {
        DetailRow("Temperature", "${"%.0f".format(summary.avgTempHighF)}° / ${"%.0f".format(summary.avgTempLowF)}°F")
        DetailRow("Range", "${"%.0f".format(summary.tempHighMin)}–${"%.0f".format(summary.tempHighMax)}°F high, ${"%.0f".format(summary.tempLowMin)}–${"%.0f".format(summary.tempLowMax)}°F low")
        DetailRow("Wind", "${"%.0f".format(summary.avgWindMaxMph)} mph, gusts ${"%.0f".format(summary.avgWindGustMph)} mph")
        DetailRow("UV Index", "${"%.1f".format(summary.avgUvIndexMax)}")
        DetailRow("Precipitation", "${"%.1f".format(summary.avgPrecipMm)} mm, ${"%.1f".format(summary.avgPrecipHours)} hrs")
        DetailRow("Sunshine", "${"%.1f".format(summary.avgSunshineMins / 60.0)} hrs")
        DetailRow("Humidity", "${"%.0f".format(summary.avgHumidityPct)}%")
    }
}

@Composable
private fun DetailRow(label: String, value: String) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceBetween,
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        Text(
            text = value,
            style = MaterialTheme.typography.bodySmall,
            fontWeight = FontWeight.Medium,
        )
    }
}

/**
 * Approximate moon phase emoji for a given date.
 * Uses the synodic month (~29.53 days) from a known new moon reference.
 */
private fun moonPhaseEmoji(date: LocalDate): String {
    val referenceNewMoon = LocalDate.of(2000, 1, 6)
    val daysSinceRef = ChronoUnit.DAYS.between(referenceNewMoon, date).toDouble()
    val synodicMonth = 29.53058867
    val phase = ((daysSinceRef % synodicMonth) + synodicMonth) % synodicMonth
    val phaseIndex = ((phase / synodicMonth) * 8).roundToInt() % 8
    return when (phaseIndex) {
        0 -> "\uD83C\uDF11"
        1 -> "\uD83C\uDF12"
        2 -> "\uD83C\uDF13"
        3 -> "\uD83C\uDF14"
        4 -> "\uD83C\uDF15"
        5 -> "\uD83C\uDF16"
        6 -> "\uD83C\uDF17"
        7 -> "\uD83C\uDF18"
        else -> ""
    }
}
