// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruisedetail

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.ui.components.deriveWeatherCondition
import org.jewzaam.cruiseweather.ui.components.toEmoji
import java.time.format.DateTimeFormatter

private val DAY_FORMAT = DateTimeFormatter.ofPattern("MMM d")

@Composable
fun WeatherCard(
    port: PortOfCall?,
    summary: PortWeatherSummary?,
    dayNumber: Int,
    isSeaDay: Boolean = false,
    modifier: Modifier = Modifier,
) {
    val condition = deriveWeatherCondition(summary)
    val isDepartureOrReturn = port?.type == PortType.DEPARTURE || port?.type == PortType.RETURN

    Card(
        modifier = modifier
            .fillMaxWidth()
            .padding(horizontal = 12.dp, vertical = 4.dp),
        colors = CardDefaults.cardColors(
            containerColor = if (isDepartureOrReturn) {
                MaterialTheme.colorScheme.primaryContainer
            } else {
                MaterialTheme.colorScheme.surfaceVariant
            },
        ),
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(12.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            // Left: day number + date + port name + type label
            Column(modifier = Modifier.weight(1f)) {
                val typeLabel = port?.let {
                    when (it.type) {
                        PortType.DEPARTURE -> "Departure"
                        PortType.RETURN -> "Return"
                        else -> null
                    }
                }
                val portName = if (isSeaDay) "At Sea" else port?.portName ?: ""
                val dateText = port?.let { DAY_FORMAT.format(it.date) } ?: ""
                Text(
                    text = "Day $dayNumber  •  $dateText" + if (typeLabel != null) "  •  $typeLabel" else "",
                    style = MaterialTheme.typography.labelSmall,
                    color = if (isDepartureOrReturn) {
                        MaterialTheme.colorScheme.onPrimaryContainer
                    } else {
                        MaterialTheme.colorScheme.onSurfaceVariant
                    },
                )
                Text(
                    text = portName,
                    style = MaterialTheme.typography.bodyLarge,
                    fontWeight = FontWeight.SemiBold,
                )
            }

            // Right: weather summary
            if (summary != null) {
                Column(horizontalAlignment = Alignment.End) {
                    Text(
                        text = "${condition.toEmoji()} ${"%.0f".format(summary.avgTempHighF)}°/${"%.0f".format(summary.avgTempLowF)}°F",
                        style = MaterialTheme.typography.bodyMedium,
                        fontWeight = FontWeight.SemiBold,
                    )
                    val rainPct = if (summary.totalYearCount > 0) {
                        (summary.rainyYearCount.toDouble() / summary.totalYearCount * 100.0).toInt()
                    } else 0
                    Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                        Text(
                            text = "Rain $rainPct%",
                            style = MaterialTheme.typography.bodySmall,
                        )
                        Text(
                            text = "Wind ${"%.0f".format(summary.avgWindMaxMph)}mph",
                            style = MaterialTheme.typography.bodySmall,
                        )
                    }
                    Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                        Text(
                            text = "UV ${"%.1f".format(summary.avgUvIndexMax)}",
                            style = MaterialTheme.typography.bodySmall,
                        )
                        Text(
                            text = "Hum ${"%.0f".format(summary.avgHumidityPct)}%",
                            style = MaterialTheme.typography.bodySmall,
                        )
                    }
                }
            } else if (!isSeaDay) {
                Text(
                    text = "No data",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        }
    }
}
