// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.domain.model

import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType

data class CruiseWithPorts(
    val cruise: Cruise,
    val ports: List<PortOfCall>,
) {
    val departurePort: PortOfCall? get() = ports.firstOrNull { it.type == PortType.DEPARTURE }
    val returnPort: PortOfCall? get() = ports.firstOrNull { it.type == PortType.RETURN }
    val portsOfCall: List<PortOfCall> get() = ports.filter {
        it.type == PortType.PORT_OF_CALL || it.type == PortType.SEA_DAY
    }

    /** All ports in calendar order for the detail view. */
    val allPortsChronological: List<PortOfCall>
        get() = ports.sortedWith(compareBy({ it.date }, { it.sortOrder }))
}
