// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.domain.model

import org.jewzaam.cruiseweather.data.local.entity.Cruise

data class CruiseComparison(
    val cruise: Cruise,
    val avgTempHighF: Double,
    val avgTempLowF: Double,
    val rainProbabilityPct: Double,
    val avgPrecipMm: Double,
    val avgWindMaxMph: Double,
    val avgUvIndexMax: Double,
    val avgHumidityPct: Double,
    val avgSunshineMins: Double,
    val rainiestPortName: String?,
    val rainiestPortRainPct: Double?,
    val portBreakdowns: List<PortWithWeather>,
)
