// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.domain.model

data class GeocodingCandidate(
    val id: Long,
    val displayName: String,
    val latitude: Double,
    val longitude: Double,
)
