// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local

import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherYear

// Schema version 1 — Phase 1 initial schema.
// fallbackToDestructiveMigration() is used during pre-release development.
// Switch to explicit Migration objects before any production release.
@Database(
    entities = [
        Cruise::class,
        PortOfCall::class,
        PortWeatherYear::class,
        PortWeatherSummary::class,
    ],
    version = 1,
    exportSchema = true,
)
@TypeConverters(Converters::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun cruiseDao(): CruiseDao
    abstract fun portOfCallDao(): PortOfCallDao
    abstract fun weatherDao(): WeatherDao
}
