// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local

import androidx.room.TypeConverter
import org.jewzaam.cruiseweather.data.local.entity.PortType
import timber.log.Timber
import java.time.Instant
import java.time.LocalDate
import java.time.format.DateTimeParseException

class Converters {
    @TypeConverter
    fun fromLocalDate(value: String?): LocalDate? = value?.let {
        try {
            LocalDate.parse(it)
        } catch (e: DateTimeParseException) {
            Timber.e(e, "Corrupt LocalDate in database: %s", it)
            null
        }
    }

    @TypeConverter
    fun toLocalDate(date: LocalDate?): String? = date?.toString()

    @TypeConverter
    fun fromInstant(value: Long?): Instant? = value?.let { Instant.ofEpochMilli(it) }

    @TypeConverter
    fun toInstant(instant: Instant?): Long? = instant?.toEpochMilli()

    @TypeConverter
    fun fromPortType(value: String?): PortType? = value?.let {
        try {
            PortType.valueOf(it)
        } catch (e: IllegalArgumentException) {
            Timber.e(e, "Corrupt PortType in database: %s", it)
            null
        }
    }

    @TypeConverter
    fun toPortType(type: PortType?): String? = type?.name
}
