// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local

import androidx.room.TypeConverter
import org.jewzaam.cruiseweather.data.local.entity.PortType
import java.time.Instant
import java.time.LocalDate

class Converters {
    @TypeConverter
    fun fromLocalDate(value: String?): LocalDate? = value?.let { LocalDate.parse(it) }

    @TypeConverter
    fun toLocalDate(date: LocalDate?): String? = date?.toString()

    @TypeConverter
    fun fromInstant(value: Long?): Instant? = value?.let { Instant.ofEpochMilli(it) }

    @TypeConverter
    fun toInstant(instant: Instant?): Long? = instant?.toEpochMilli()

    @TypeConverter
    fun fromPortType(value: String?): PortType? = value?.let { PortType.valueOf(it) }

    @TypeConverter
    fun toPortType(type: PortType?): String? = type?.name
}
