// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow
import org.jewzaam.cruiseweather.data.local.entity.Cruise

@Dao
interface CruiseDao {
    @Query("SELECT * FROM cruises ORDER BY sailDate ASC")
    fun getAllCruises(): Flow<List<Cruise>>

    @Query("SELECT * FROM cruises WHERE id = :id")
    fun getCruiseById(id: Long): Flow<Cruise?>

    @Insert
    suspend fun insert(cruise: Cruise): Long

    @Update
    suspend fun update(cruise: Cruise)

    @Delete
    suspend fun delete(cruise: Cruise)
}
