// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.data.local

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/** v1→v2: Add localId column to ports_of_call. */
val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "ALTER TABLE ports_of_call ADD COLUMN localId TEXT NOT NULL DEFAULT ''",
        )
        // Backfill existing rows with unique hex values derived from rowid
        db.execSQL(
            "UPDATE ports_of_call SET localId = lower(hex(randomblob(16))) WHERE localId = ''",
        )
    }
}

/** v2→v3: Add sunrise/sunset columns to weather tables, invalidate cached weather. */
val MIGRATION_2_3 = object : Migration(2, 3) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "ALTER TABLE port_weather_years ADD COLUMN sunriseMinutes REAL NOT NULL DEFAULT 0.0",
        )
        db.execSQL(
            "ALTER TABLE port_weather_years ADD COLUMN sunsetMinutes REAL NOT NULL DEFAULT 0.0",
        )
        db.execSQL(
            "ALTER TABLE port_weather_summaries ADD COLUMN avgSunriseMinutes REAL NOT NULL DEFAULT 0.0",
        )
        db.execSQL(
            "ALTER TABLE port_weather_summaries ADD COLUMN avgSunsetMinutes REAL NOT NULL DEFAULT 0.0",
        )
        // Existing summaries have avgSunriseMinutes == 0.0, which
        // isFetchNeeded() treats as stale — auto-fetch will fire lazily.
    }
}

/** v3→v4: Add notes column to ports_of_call. */
val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "ALTER TABLE ports_of_call ADD COLUMN notes TEXT NOT NULL DEFAULT ''",
        )
    }
}

/** All migrations — must be registered in DatabaseModule. */
val ALL_MIGRATIONS: Array<Migration> = arrayOf(MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_4)
