// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import kotlinx.coroutines.flow.Flow
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherYear

@Dao
interface WeatherDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertWeatherYear(data: PortWeatherYear)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertWeatherYears(data: List<PortWeatherYear>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertSummary(summary: PortWeatherSummary)

    @Query("SELECT * FROM port_weather_summaries WHERE portOfCallId = :portId")
    fun getSummaryForPort(portId: Long): Flow<PortWeatherSummary?>

    @Query("SELECT * FROM port_weather_summaries WHERE portOfCallId = :portId")
    suspend fun getSummaryForPortOnce(portId: Long): PortWeatherSummary?

    @Query("SELECT * FROM port_weather_years WHERE portOfCallId = :portId ORDER BY year ASC")
    fun getYearDataForPort(portId: Long): Flow<List<PortWeatherYear>>

    @Query("SELECT * FROM port_weather_years WHERE portOfCallId = :portId ORDER BY year ASC")
    suspend fun getYearDataForPortOnce(portId: Long): List<PortWeatherYear>

    @Query("DELETE FROM port_weather_years WHERE portOfCallId = :portId")
    suspend fun deleteWeatherYearsForPort(portId: Long)

    @Query("DELETE FROM port_weather_summaries WHERE portOfCallId = :portId")
    suspend fun deleteSummaryForPort(portId: Long)
}
