// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.comparison

import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Card
import androidx.compose.material3.Checkbox
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.domain.model.CruiseComparison
import org.jewzaam.cruiseweather.ui.components.LoadingOverlay
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle

private val DATE_FORMAT = DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ComparisonScreen(
    onNavigateUp: () -> Unit,
    viewModel: ComparisonViewModel = hiltViewModel(),
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Compare Cruises") },
                navigationIcon = {
                    IconButton(onClick = onNavigateUp) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Navigate up",
                        )
                    }
                },
            )
        },
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .fillMaxSize()
                .verticalScroll(rememberScrollState()),
        ) {
            Text(
                text = "Select cruises to compare:",
                style = MaterialTheme.typography.titleSmall,
                modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp),
            )

            uiState.allCruises.forEach { cruise ->
                CruiseCheckRow(
                    cruise = cruise,
                    isChecked = cruise.id in uiState.selectedIds,
                    onCheckedChange = { viewModel.toggleCruise(cruise.id) },
                )
            }

            if (uiState.comparisons.isNotEmpty()) {
                Spacer(modifier = Modifier.height(8.dp))
                HorizontalDivider()
                Spacer(modifier = Modifier.height(8.dp))

                Row(
                    modifier = Modifier.horizontalScroll(rememberScrollState()),
                ) {
                    ComparisonTable(comparisons = uiState.comparisons)
                }
            }

            uiState.error?.let { error ->
                Text(
                    text = error,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(16.dp),
                )
            }
        }

        if (uiState.isLoading) {
            LoadingOverlay(message = "Computing comparison…")
        }
    }
}

@Composable
private fun CruiseCheckRow(
    cruise: Cruise,
    isChecked: Boolean,
    onCheckedChange: () -> Unit,
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 8.dp, vertical = 4.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Checkbox(
            checked = isChecked,
            onCheckedChange = { onCheckedChange() },
        )
        Spacer(modifier = Modifier.width(8.dp))
        Column {
            Text(text = cruise.name, style = MaterialTheme.typography.bodyMedium)
            Text(
                text = "${DATE_FORMAT.format(cruise.sailDate)} – ${DATE_FORMAT.format(cruise.returnDate)}",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
    }
}

@Composable
private fun ComparisonTable(comparisons: List<CruiseComparison>) {
    // Header row + label column
    Column(modifier = Modifier.padding(8.dp)) {
        // Column headers
        Row {
            TableCell(text = "", isHeader = true, width = 140)
            comparisons.forEach { c ->
                TableCell(text = c.cruise.name, isHeader = true, width = 110)
            }
        }
        HorizontalDivider()

        ComparisonRow(
            label = "Avg High",
            values = comparisons.map { "${"%.0f".format(it.avgTempHighF)}°F" },
        )
        ComparisonRow(
            label = "Avg Low",
            values = comparisons.map { "${"%.0f".format(it.avgTempLowF)}°F" },
        )
        ComparisonRow(
            label = "Rain Chance",
            values = comparisons.map { "${"%.0f".format(it.rainProbabilityPct)}%" },
        )
        ComparisonRow(
            label = "Avg Precip",
            values = comparisons.map { "${"%.1f".format(it.avgPrecipMm)} mm" },
        )
        ComparisonRow(
            label = "Avg Wind",
            values = comparisons.map { "${"%.0f".format(it.avgWindMaxMph)} mph" },
        )
        ComparisonRow(
            label = "Avg UV",
            values = comparisons.map { "${"%.1f".format(it.avgUvIndexMax)}" },
        )
        ComparisonRow(
            label = "Avg Humidity",
            values = comparisons.map { "${"%.0f".format(it.avgHumidityPct)}%" },
        )
        ComparisonRow(
            label = "Sunshine hrs",
            values = comparisons.map { "${"%.1f".format(it.avgSunshineMins / 60.0)}" },
        )
        ComparisonRow(
            label = "Rainiest Port",
            values = comparisons.map { c ->
                if (c.rainiestPortName != null && c.rainiestPortRainPct != null) {
                    "${c.rainiestPortName} (${"%.0f".format(c.rainiestPortRainPct)}%)"
                } else "—"
            },
        )
    }
}

@Composable
private fun ComparisonRow(label: String, values: List<String>) {
    Row {
        TableCell(text = label, isHeader = false, width = 140)
        values.forEach { value ->
            TableCell(text = value, isHeader = false, width = 110)
        }
    }
    HorizontalDivider()
}

@Composable
private fun TableCell(text: String, isHeader: Boolean, width: Int) {
    Text(
        text = text,
        modifier = Modifier
            .width(width.dp)
            .padding(horizontal = 8.dp, vertical = 6.dp),
        style = if (isHeader) MaterialTheme.typography.labelMedium else MaterialTheme.typography.bodySmall,
        fontWeight = if (isHeader) FontWeight.Bold else FontWeight.Normal,
        maxLines = 2,
    )
}
