// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.comparison

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.domain.model.CruiseComparison
import org.jewzaam.cruiseweather.domain.usecase.CompareCruisesUseCase
import javax.inject.Inject

data class ComparisonUiState(
    val allCruises: List<Cruise> = emptyList(),
    val selectedIds: Set<Long> = emptySet(),
    val comparisons: List<CruiseComparison> = emptyList(),
    val isLoading: Boolean = false,
    val error: String? = null,
)

@HiltViewModel
class ComparisonViewModel @Inject constructor(
    private val cruiseRepository: CruiseRepository,
    private val compareCruisesUseCase: CompareCruisesUseCase,
) : ViewModel() {

    private val _selectedIds = MutableStateFlow<Set<Long>>(emptySet())
    private val _comparisons = MutableStateFlow<List<CruiseComparison>>(emptyList())
    private val _isLoading = MutableStateFlow(false)
    private val _error = MutableStateFlow<String?>(null)

    val uiState: StateFlow<ComparisonUiState> = combine(
        cruiseRepository.getAllCruises(),
        _selectedIds,
        _comparisons,
        _isLoading,
        _error,
    ) { cruises, selectedIds, comparisons, isLoading, error ->
        ComparisonUiState(
            allCruises = cruises,
            selectedIds = selectedIds,
            comparisons = comparisons,
            isLoading = isLoading,
            error = error,
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5_000),
        initialValue = ComparisonUiState(),
    )

    fun toggleCruise(cruiseId: Long) {
        _selectedIds.update { ids ->
            if (cruiseId in ids) ids - cruiseId else ids + cruiseId
        }
        refreshComparisons()
    }

    private var comparisonJob: Job? = null

    private fun refreshComparisons() {
        val ids = _selectedIds.value.toList()
        if (ids.size < 2) {
            _comparisons.value = emptyList()
            return
        }
        comparisonJob?.cancel()
        comparisonJob = viewModelScope.launch {
            _isLoading.value = true
            _error.value = null
            runCatching {
                compareCruisesUseCase(cruiseIds = ids)
            }.onSuccess { result ->
                _comparisons.value = result
            }.onFailure { e ->
                _error.value = e.message ?: "Comparison failed"
            }
            _isLoading.value = false
        }
    }
}
