// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.comparison

import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Checkbox
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.foundation.ScrollState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.domain.model.CruiseComparison
import org.jewzaam.cruiseweather.ui.components.LoadingOverlay

import java.time.temporal.ChronoUnit

private val DATE_FORMAT = org.jewzaam.cruiseweather.ui.util.DateFormatters.MEDIUM_DATE

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ComparisonScreen(
    onNavigateUp: () -> Unit,
    viewModel: ComparisonViewModel = hiltViewModel(),
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Compare Cruises") },
                navigationIcon = {
                    IconButton(onClick = onNavigateUp) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "Navigate up",
                        )
                    }
                },
            )
        },
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .fillMaxSize()
                .verticalScroll(rememberScrollState()),
        ) {
            Text(
                text = "Select cruises to compare:",
                style = MaterialTheme.typography.titleSmall,
                modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp),
            )

            uiState.allCruises.forEach { cruise ->
                CruiseCheckRow(
                    cruise = cruise,
                    isChecked = cruise.id in uiState.selectedIds,
                    onCheckedChange = { viewModel.toggleCruise(cruise.id) },
                )
            }

            if (uiState.comparisons.isNotEmpty()) {
                Spacer(modifier = Modifier.height(8.dp))
                HorizontalDivider()
                Spacer(modifier = Modifier.height(8.dp))

                ComparisonTable(comparisons = uiState.comparisons)
            }

            uiState.error?.let { error ->
                Text(
                    text = error,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(16.dp),
                )
            }
        }

        if (uiState.isLoading) {
            LoadingOverlay(message = "Fetching weather data…")
        }
    }
}

@Composable
private fun CruiseCheckRow(
    cruise: Cruise,
    isChecked: Boolean,
    onCheckedChange: () -> Unit,
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 8.dp, vertical = 4.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Checkbox(
            checked = isChecked,
            onCheckedChange = { onCheckedChange() },
        )
        Spacer(modifier = Modifier.width(8.dp))
        Column {
            Text(text = cruise.name, style = MaterialTheme.typography.bodyMedium)
            Text(
                text = "${DATE_FORMAT.format(cruise.sailDate)} – ${DATE_FORMAT.format(cruise.returnDate)}",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
    }
}

private data class ComparisonRowData(val label: String, val values: List<String>)

@Composable
private fun ComparisonTable(comparisons: List<CruiseComparison>) {
    val rows = listOf(
        // Cruise overview
        ComparisonRowData("Days", comparisons.map {
            val days = ChronoUnit.DAYS.between(it.cruise.sailDate, it.cruise.returnDate) + 1
            "$days"
        }),
        ComparisonRowData("Embark", comparisons.map { it.cruise.departurePortName }),
        ComparisonRowData("Debark", comparisons.map {
            it.cruise.returnPortName ?: it.cruise.departurePortName
        }),
        ComparisonRowData("Ports of Call", comparisons.map {
            val count = it.portBreakdowns.count { p -> p.port.type == PortType.PORT_OF_CALL }
            "$count"
        }),
        ComparisonRowData("Sea Days", comparisons.map {
            val totalDays = ChronoUnit.DAYS.between(it.cruise.sailDate, it.cruise.returnDate) + 1
            val portDays = it.portBreakdowns.count { p -> p.port.type != PortType.SEA_DAY }
            val seaDays = totalDays - portDays
            "$seaDays"
        }),
        // Weather
        ComparisonRowData("Avg High", comparisons.map { "${"%.0f".format(it.avgTempHighF)}°F" }),
        ComparisonRowData("Avg Low", comparisons.map { "${"%.0f".format(it.avgTempLowF)}°F" }),
        ComparisonRowData("Rain Chance", comparisons.map { "${"%.0f".format(it.rainProbabilityPct)}%" }),
        ComparisonRowData("Avg Precip", comparisons.map { "${"%.1f".format(it.avgPrecipMm)} mm" }),
        ComparisonRowData("Avg Wind", comparisons.map { "${"%.0f".format(it.avgWindMaxMph)} mph" }),
        ComparisonRowData("Avg UV", comparisons.map { "${"%.1f".format(it.avgUvIndexMax)}" }),
        ComparisonRowData("Avg Humidity", comparisons.map { "${"%.0f".format(it.avgHumidityPct)}%" }),
        ComparisonRowData("Sunshine hrs", comparisons.map { "${"%.1f".format(it.avgSunshineMins / 60.0)}" }),
        ComparisonRowData("Avg Sunrise", comparisons.map { it.avgSunriseFormatted }),
        ComparisonRowData("Avg Sunset", comparisons.map { it.avgSunsetFormatted }),
        ComparisonRowData("Rainiest Port", comparisons.map { c ->
            if (c.rainiestPortName != null && c.rainiestPortRainPct != null) {
                "${c.rainiestPortName} (${"%.0f".format(c.rainiestPortRainPct)}%)"
            } else "—"
        }),
    )

    // Shared scroll state so all rows scroll in sync
    val dataScrollState = rememberScrollState()

    Column(modifier = Modifier.padding(8.dp)) {
        // Header row
        ComparisonTableRow(
            label = "",
            values = comparisons.map { it.cruise.name },
            isHeader = true,
            dataScrollState = dataScrollState,
        )
        HorizontalDivider()
        // Data rows
        rows.forEach { row ->
            ComparisonTableRow(
                label = row.label,
                values = row.values,
                isHeader = false,
                dataScrollState = dataScrollState,
            )
            HorizontalDivider()
        }
    }
}

@Composable
private fun ComparisonTableRow(
    label: String,
    values: List<String>,
    isHeader: Boolean,
    dataScrollState: ScrollState,
) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        // Fixed label
        Text(
            text = label,
            modifier = Modifier
                .width(100.dp)
                .padding(horizontal = 8.dp, vertical = 6.dp),
            style = MaterialTheme.typography.bodySmall,
            fontWeight = FontWeight.Medium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        // Scrollable data cells
        Row(
            modifier = Modifier
                .weight(1f)
                .horizontalScroll(dataScrollState),
        ) {
            values.forEach { value ->
                Text(
                    text = value,
                    modifier = Modifier
                        .width(120.dp)
                        .padding(horizontal = 8.dp, vertical = 6.dp),
                    style = if (isHeader) MaterialTheme.typography.labelMedium else MaterialTheme.typography.bodySmall,
                    fontWeight = if (isHeader) FontWeight.Bold else FontWeight.Normal,
                )
            }
        }
    }
}
