// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import org.jewzaam.cruiseweather.domain.usecase.GeocodePortUseCase
import java.time.LocalDate
import javax.inject.Inject

data class CruiseEditUiState(
    val isLoading: Boolean = false,
    val isSaved: Boolean = false,
    val savedCruiseId: Long? = null,
    val error: String? = null,
    // Cruise fields
    val cruiseId: Long = 0L,
    val name: String = "",
    val sailDate: LocalDate = LocalDate.now(),
    val returnDate: LocalDate = LocalDate.now().plusDays(7),
    // Departure port
    val departurePortName: String = "",
    val selectedDeparture: GeocodingCandidate? = null,
    // Return port
    val hasDifferentReturnPort: Boolean = false,
    val returnPortName: String = "",
    val selectedReturn: GeocodingCandidate? = null,
    // Ports of call (local staging — not persisted until save)
    val portsOfCall: List<PortOfCall> = emptyList(),
)

@HiltViewModel
class CruiseEditViewModel @Inject constructor(
    private val cruiseRepository: CruiseRepository,
    private val geocodePortUseCase: GeocodePortUseCase,
) : ViewModel() {

    private val _uiState = MutableStateFlow(CruiseEditUiState())
    val uiState: StateFlow<CruiseEditUiState> = _uiState.asStateFlow()

    // Original port IDs loaded from DB — used to diff on save
    private var originalPortIds: Set<Long> = emptySet()

    fun loadCruise(cruiseId: Long) {
        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true) }
            val cruiseWithPorts = cruiseRepository.getCruiseWithPorts(cruiseId).first()
            if (cruiseWithPorts != null) {
                val cruise = cruiseWithPorts.cruise
                val departure = cruiseWithPorts.departurePort
                val returnPort = cruiseWithPorts.returnPort
                val hasDifferentReturn = cruise.returnPortName != null
                val portsOfCall = cruiseWithPorts.portsOfCall
                originalPortIds = portsOfCall.map { it.id }.toSet()
                _uiState.update { state ->
                    state.copy(
                        isLoading = false,
                        cruiseId = cruise.id,
                        name = cruise.name,
                        sailDate = cruise.sailDate,
                        returnDate = cruise.returnDate,
                        departurePortName = departure?.resolvedDisplayName
                            ?: departure?.portName ?: cruise.departurePortName,
                        selectedDeparture = departure?.let {
                            val lat = it.latitude
                            val lon = it.longitude
                            if (lat != null && lon != null) {
                                GeocodingCandidate(
                                    id = it.id,
                                    displayName = it.resolvedDisplayName ?: it.portName,
                                    latitude = lat,
                                    longitude = lon,
                                )
                            } else null
                        },
                        hasDifferentReturnPort = hasDifferentReturn,
                        returnPortName = returnPort?.takeIf { hasDifferentReturn }?.let {
                            it.resolvedDisplayName ?: it.portName
                        } ?: cruise.returnPortName ?: "",
                        selectedReturn = returnPort?.takeIf { hasDifferentReturn }?.let {
                            val lat = it.latitude
                            val lon = it.longitude
                            if (lat != null && lon != null) {
                                GeocodingCandidate(
                                    id = it.id,
                                    displayName = it.resolvedDisplayName ?: it.portName,
                                    latitude = lat,
                                    longitude = lon,
                                )
                            } else null
                        },
                        portsOfCall = portsOfCall,
                    )
                }
            } else {
                _uiState.update { it.copy(isLoading = false) }
            }
        }
    }

    fun onNameChange(value: String) = _uiState.update { it.copy(name = value) }
    fun onSailDateChange(value: LocalDate) = _uiState.update { it.copy(sailDate = value) }
    fun onReturnDateChange(value: LocalDate) = _uiState.update { it.copy(returnDate = value) }
    fun onDateRangeChange(sailDate: LocalDate, returnDate: LocalDate) =
        _uiState.update { it.copy(sailDate = sailDate, returnDate = returnDate) }

    fun onDepartureChanged(displayName: String, candidate: GeocodingCandidate?) {
        _uiState.update { it.copy(departurePortName = displayName, selectedDeparture = candidate) }
    }

    fun onHasDifferentReturnPortChange(value: Boolean) {
        _uiState.update {
            it.copy(
                hasDifferentReturnPort = value,
                returnPortName = "",
                selectedReturn = null,
            )
        }
    }

    fun onReturnChanged(displayName: String, candidate: GeocodingCandidate?) {
        _uiState.update { it.copy(returnPortName = displayName, selectedReturn = candidate) }
    }

    fun saveCruise() {
        val state = _uiState.value
        if (state.name.isBlank()) {
            _uiState.update { it.copy(error = "Cruise name is required") }
            return
        }
        if (state.selectedDeparture == null) {
            _uiState.update { it.copy(error = "Departure port must be geocoded") }
            return
        }
        if (state.returnDate < state.sailDate) {
            _uiState.update { it.copy(error = "Return date must be on or after sail date") }
            return
        }

        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true, error = null) }
            try {
                val dep = state.selectedDeparture
                val cruise = Cruise(
                    id = state.cruiseId,
                    name = state.name.trim(),
                    sailDate = state.sailDate,
                    returnDate = state.returnDate,
                    departurePortName = dep.displayName,
                    returnPortName = if (state.hasDifferentReturnPort) {
                        state.selectedReturn?.displayName ?: state.returnPortName.trim()
                    } else null,
                )

                val departurePorts = buildDeparturePorts(cruise = cruise, state = state)
                val currentPortIds = state.portsOfCall.filter { it.id != 0L }.map { it.id }.toSet()
                val deletedPortIds = originalPortIds - currentPortIds
                val savedId = cruiseRepository.saveCruise(
                    cruise = cruise,
                    departurePorts = departurePorts,
                    portsOfCall = state.portsOfCall,
                    deletedPortIds = deletedPortIds,
                )

                _uiState.update { it.copy(isLoading = false, isSaved = true, savedCruiseId = savedId) }
            } catch (e: Exception) {
                _uiState.update { it.copy(isLoading = false, error = e.message ?: "Failed to save cruise") }
            }
        }
    }

    private fun buildDeparturePorts(cruise: Cruise, state: CruiseEditUiState): List<PortOfCall> {
        val ports = mutableListOf<PortOfCall>()
        val dep = state.selectedDeparture
        ports.add(
            PortOfCall(
                cruiseId = cruise.id,
                portName = state.departurePortName.trim(),
                date = cruise.sailDate,
                type = PortType.DEPARTURE,
                latitude = dep?.latitude,
                longitude = dep?.longitude,
                resolvedDisplayName = dep?.displayName,
                sortOrder = 0,
            ),
        )
        val returnName = cruise.returnPortName
        if (returnName != null) {
            val ret = state.selectedReturn
            ports.add(
                PortOfCall(
                    cruiseId = cruise.id,
                    portName = state.returnPortName.trim(),
                    date = cruise.returnDate,
                    type = PortType.RETURN,
                    latitude = ret?.latitude,
                    longitude = ret?.longitude,
                    resolvedDisplayName = ret?.displayName,
                    sortOrder = Int.MAX_VALUE,
                ),
            )
        } else {
            ports.add(
                PortOfCall(
                    cruiseId = cruise.id,
                    portName = state.departurePortName.trim(),
                    date = cruise.returnDate,
                    type = PortType.RETURN,
                    latitude = dep?.latitude,
                    longitude = dep?.longitude,
                    resolvedDisplayName = dep?.displayName,
                    sortOrder = Int.MAX_VALUE,
                ),
            )
        }
        return ports
    }

    // All port operations are local-only — persisted on saveCruise()
    fun addPortOfCall(port: PortOfCall) {
        _uiState.update { it.copy(portsOfCall = it.portsOfCall + port) }
    }

    fun updatePortOfCall(port: PortOfCall) {
        _uiState.update { state ->
            state.copy(portsOfCall = state.portsOfCall.map { if (it.localId == port.localId) port else it })
        }
    }

    fun deletePortOfCall(port: PortOfCall) {
        _uiState.update { state ->
            state.copy(portsOfCall = state.portsOfCall.filter { it.localId != port.localId })
        }
    }

    fun clearError() = _uiState.update { it.copy(error = null) }

    suspend fun geocodeQuery(query: String): List<GeocodingCandidate> =
        geocodePortUseCase(query = query).getOrDefault(emptyList())
}
