// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.DateRangePicker
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.ListItem
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.rememberDateRangePickerState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.ui.components.LocationPicker
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle
import java.time.temporal.ChronoUnit

private val DATE_FORMAT = DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CruiseEditScreen(
    cruiseId: Long?,
    onNavigateUp: () -> Unit,
    onCruiseSaved: ((Long) -> Unit)? = null,
    viewModel: CruiseEditViewModel = hiltViewModel(),
) {
    val isNewCruise = cruiseId == null || cruiseId == 0L

    LaunchedEffect(cruiseId) {
        if (cruiseId != null && cruiseId != 0L) {
            viewModel.loadCruise(cruiseId)
        }
    }

    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
    val snackbarHostState = remember { SnackbarHostState() }
    var showPortSheet by remember { mutableStateOf(false) }
    var editingPort by remember { mutableStateOf<PortOfCall?>(null) }
    var showDateRangePicker by remember { mutableStateOf(false) }

    LaunchedEffect(uiState.isSaved) {
        if (uiState.isSaved) {
            val savedId = uiState.savedCruiseId
            if (isNewCruise && savedId != null && onCruiseSaved != null) {
                onCruiseSaved(savedId)
            } else {
                onNavigateUp()
            }
        }
    }

    LaunchedEffect(uiState.error) {
        uiState.error?.let { error ->
            snackbarHostState.showSnackbar(error)
            viewModel.clearError()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(if (isNewCruise) "New Cruise" else "Edit Cruise") },
                navigationIcon = {
                    TextButton(onClick = onNavigateUp) {
                        Text("Cancel")
                    }
                },
            )
        },
        snackbarHost = { SnackbarHost(snackbarHostState) },
        bottomBar = {
            Button(
                onClick = viewModel::saveCruise,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                enabled = !uiState.isLoading,
            ) {
                if (uiState.isLoading) {
                    CircularProgressIndicator()
                } else {
                    Text("Save Cruise")
                }
            }
        },
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
        ) {
            OutlinedTextField(
                value = uiState.name,
                onValueChange = viewModel::onNameChange,
                label = { Text("Cruise Name") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
            )

            Spacer(modifier = Modifier.height(12.dp))

            // Date range display — tap to open range picker
            val dateLabel = "${DATE_FORMAT.format(uiState.sailDate)} – ${DATE_FORMAT.format(uiState.returnDate)}"
            val totalDays = ChronoUnit.DAYS.between(uiState.sailDate, uiState.returnDate) + 1
            OutlinedTextField(
                value = dateLabel,
                onValueChange = {},
                label = { Text("Dates ($totalDays days)") },
                modifier = Modifier
                    .fillMaxWidth()
                    .clickable { showDateRangePicker = true },
                readOnly = true,
                singleLine = true,
                enabled = false,
            )
            TextButton(onClick = { showDateRangePicker = true }) {
                Text("Change dates")
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Departure port — uses shared LocationPicker
            LocationPicker(
                label = "Departure Port",
                initialDisplayName = uiState.departurePortName,
                initialCandidate = uiState.selectedDeparture,
                onSelectionChanged = viewModel::onDepartureChanged,
                onGeocode = { query -> viewModel.geocodeQuery(query) },
            )

            Spacer(modifier = Modifier.height(12.dp))

            // Different return port checkbox
            Row(verticalAlignment = Alignment.CenterVertically) {
                Checkbox(
                    checked = uiState.hasDifferentReturnPort,
                    onCheckedChange = viewModel::onHasDifferentReturnPortChange,
                )
                Text("Different return port")
            }

            if (uiState.hasDifferentReturnPort) {
                Spacer(modifier = Modifier.height(8.dp))
                LocationPicker(
                    label = "Return Port",
                    initialDisplayName = uiState.returnPortName,
                    initialCandidate = uiState.selectedReturn,
                    onSelectionChanged = viewModel::onReturnChanged,
                    onGeocode = { query -> viewModel.geocodeQuery(query) },
                )
            }

            // Ports of call section — only shown when editing existing cruise
            if (!isNewCruise) {
                Spacer(modifier = Modifier.height(16.dp))
                HorizontalDivider()
                Spacer(modifier = Modifier.height(8.dp))

                Text(text = "Ports of Call")

                if (uiState.portsOfCall.isEmpty()) {
                    Text(
                        text = "No ports of call yet.",
                        modifier = Modifier.padding(vertical = 8.dp),
                    )
                } else {
                    uiState.portsOfCall.forEach { port ->
                        val dayOfCruise = ChronoUnit.DAYS.between(uiState.sailDate, port.date) + 1
                        val displayName = port.portName
                        val geocodeStatus = if (port.latitude != null) "geocoded" else "not geocoded"
                        ListItem(
                            headlineContent = { Text(displayName) },
                            supportingContent = { Text("Day $dayOfCruise  \u2022  ${port.date}  \u2022  $geocodeStatus") },
                            trailingContent = {
                                Icon(
                                    imageVector = Icons.Default.Edit,
                                    contentDescription = "Edit $displayName",
                                    tint = MaterialTheme.colorScheme.onSurfaceVariant,
                                )
                            },
                            modifier = Modifier.clickable { editingPort = port },
                        )
                        HorizontalDivider()
                    }
                }

                OutlinedButton(
                    onClick = { showPortSheet = true },
                    modifier = Modifier.padding(top = 8.dp),
                ) {
                    Text("+ Add Port of Call")
                }
            }
        }
    }

    // Port of call add/edit sheets — only for existing cruises
    if (!isNewCruise) {
        if (showPortSheet) {
            val lastPortDate = uiState.portsOfCall.maxByOrNull { it.date }?.date
            PortOfCallSheet(
                cruiseId = uiState.cruiseId,
                sailDate = uiState.sailDate,
                returnDate = uiState.returnDate,
                lastPortDate = lastPortDate,
                onSave = { port -> viewModel.addPortOfCall(port) },
                onDismiss = { showPortSheet = false },
                onGeocode = { query -> viewModel.geocodeQuery(query) },
            )
        }

        editingPort?.let { port ->
            PortOfCallSheet(
                cruiseId = uiState.cruiseId,
                sailDate = uiState.sailDate,
                returnDate = uiState.returnDate,
                existingPort = port,
                onSave = { updated -> viewModel.updatePortOfCall(updated) },
                onDelete = { deleted -> viewModel.deletePortOfCall(deleted) },
                onDismiss = { editingPort = null },
                onGeocode = { query -> viewModel.geocodeQuery(query) },
            )
        }
    }

    if (showDateRangePicker) {
        DateRangePickerDialog(
            initialSailDate = uiState.sailDate,
            initialReturnDate = uiState.returnDate,
            onConfirm = { sail, ret ->
                viewModel.onDateRangeChange(sail, ret)
                showDateRangePicker = false
            },
            onDismiss = { showDateRangePicker = false },
        )
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun DateRangePickerDialog(
    initialSailDate: LocalDate,
    initialReturnDate: LocalDate,
    onConfirm: (LocalDate, LocalDate) -> Unit,
    onDismiss: () -> Unit,
) {
    val startMillis = initialSailDate.atStartOfDay(ZoneOffset.UTC).toInstant().toEpochMilli()
    val endMillis = initialReturnDate.atStartOfDay(ZoneOffset.UTC).toInstant().toEpochMilli()
    val dateRangePickerState = rememberDateRangePickerState(
        initialSelectedStartDateMillis = startMillis,
        initialSelectedEndDateMillis = endMillis,
    )

    val hasValidRange = dateRangePickerState.selectedStartDateMillis != null
        && dateRangePickerState.selectedEndDateMillis != null

    Dialog(
        onDismissRequest = onDismiss,
        properties = DialogProperties(usePlatformDefaultWidth = false),
    ) {
        Column(
            modifier = Modifier.padding(16.dp),
        ) {
            DateRangePicker(
                state = dateRangePickerState,
                modifier = Modifier.weight(1f),
                title = {
                    Text(
                        text = "Select cruise dates",
                        modifier = Modifier.padding(start = 24.dp, top = 16.dp),
                    )
                },
                headline = null,
                showModeToggle = true,
            )
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 12.dp, bottom = 8.dp),
            ) {
                Spacer(modifier = Modifier.weight(1f))
                OutlinedButton(
                    onClick = onDismiss,
                    modifier = Modifier.padding(end = 8.dp),
                ) {
                    Text("Cancel", style = MaterialTheme.typography.labelLarge)
                }
                Button(
                    onClick = {
                        val startMs = dateRangePickerState.selectedStartDateMillis!!
                        val endMs = dateRangePickerState.selectedEndDateMillis!!
                        val sail = Instant.ofEpochMilli(startMs).atZone(ZoneOffset.UTC).toLocalDate()
                        val ret = Instant.ofEpochMilli(endMs).atZone(ZoneOffset.UTC).toLocalDate()
                        onConfirm(sail, ret)
                    },
                    enabled = hasValidRange,
                ) {
                    Text("Confirm", style = MaterialTheme.typography.labelLarge)
                }
            }
        }
    }
}
