// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.PressInteraction
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.DatePicker
import androidx.compose.material3.DatePickerDialog
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.ListItem
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.rememberDatePickerState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.ui.components.GeocodingConfirmation
import java.time.Instant
import java.time.ZoneOffset
import java.time.temporal.ChronoUnit

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CruiseEditScreen(
    cruiseId: Long?,
    onNavigateUp: () -> Unit,
    viewModel: CruiseEditViewModel = hiltViewModel(),
) {
    LaunchedEffect(cruiseId) {
        if (cruiseId != null && cruiseId != 0L) {
            viewModel.loadCruise(cruiseId)
        }
    }

    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
    val snackbarHostState = remember { SnackbarHostState() }
    var showPortSheet by remember { mutableStateOf(false) }
    var editingPort by remember { mutableStateOf<PortOfCall?>(null) }
    var showSailDatePicker by remember { mutableStateOf(false) }
    var showReturnDatePicker by remember { mutableStateOf(false) }

    LaunchedEffect(uiState.isSaved) {
        if (uiState.isSaved) onNavigateUp()
    }

    LaunchedEffect(uiState.error) {
        uiState.error?.let { error ->
            snackbarHostState.showSnackbar(error)
            viewModel.clearError()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(if (cruiseId == null) "New Cruise" else "Edit Cruise") },
                navigationIcon = {
                    TextButton(onClick = onNavigateUp) {
                        Text("Cancel")
                    }
                },
            )
        },
        snackbarHost = { SnackbarHost(snackbarHostState) },
        bottomBar = {
            Button(
                onClick = viewModel::saveCruise,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                enabled = !uiState.isLoading,
            ) {
                if (uiState.isLoading) {
                    CircularProgressIndicator()
                } else {
                    Text("Save Cruise")
                }
            }
        },
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
        ) {
            OutlinedTextField(
                value = uiState.name,
                onValueChange = viewModel::onNameChange,
                label = { Text("Cruise Name") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
            )

            Spacer(modifier = Modifier.height(12.dp))

            // Date row
            Row {
                OutlinedTextField(
                    value = uiState.sailDate.toString(),
                    onValueChange = {},
                    label = { Text("Sail Date") },
                    modifier = Modifier.weight(1f),
                    readOnly = true,
                    singleLine = true,
                    interactionSource = remember { MutableInteractionSource() }
                        .also { interactionSource ->
                            LaunchedEffect(interactionSource) {
                                interactionSource.interactions.collect { interaction ->
                                    if (interaction is PressInteraction.Release) {
                                        showSailDatePicker = true
                                    }
                                }
                            }
                        },
                )
                Spacer(modifier = Modifier.width(8.dp))
                OutlinedTextField(
                    value = uiState.returnDate.toString(),
                    onValueChange = {},
                    label = { Text("Return Date") },
                    modifier = Modifier.weight(1f),
                    readOnly = true,
                    singleLine = true,
                    interactionSource = remember { MutableInteractionSource() }
                        .also { interactionSource ->
                            LaunchedEffect(interactionSource) {
                                interactionSource.interactions.collect { interaction ->
                                    if (interaction is PressInteraction.Release) {
                                        showReturnDatePicker = true
                                    }
                                }
                            }
                        },
                )
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Departure port
            OutlinedTextField(
                value = uiState.departurePortName,
                onValueChange = viewModel::onDeparturePortNameChange,
                label = { Text("Departure Port") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                trailingIcon = {
                    if (uiState.isGeocodingDeparture) CircularProgressIndicator()
                },
            )
            if (uiState.departureCandidates.isNotEmpty()) {
                GeocodingConfirmation(
                    candidates = uiState.departureCandidates,
                    selectedId = uiState.selectedDeparture?.id,
                    onCandidateSelected = viewModel::onDepartureCandidateSelected,
                    modifier = Modifier.padding(top = 8.dp),
                )
            }
            uiState.selectedDeparture?.let {
                Text(
                    text = "Location confirmed",
                    modifier = Modifier.padding(top = 4.dp),
                    color = MaterialTheme.colorScheme.primary,
                )
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Different return port checkbox
            Row(verticalAlignment = Alignment.CenterVertically) {
                Checkbox(
                    checked = uiState.hasDifferentReturnPort,
                    onCheckedChange = viewModel::onHasDifferentReturnPortChange,
                )
                Text("Different return port")
            }

            if (uiState.hasDifferentReturnPort) {
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(
                    value = uiState.returnPortName,
                    onValueChange = viewModel::onReturnPortNameChange,
                    label = { Text("Return Port") },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true,
                    trailingIcon = {
                        if (uiState.isGeocodingReturn) CircularProgressIndicator()
                    },
                )
                if (uiState.returnCandidates.isNotEmpty()) {
                    GeocodingConfirmation(
                        candidates = uiState.returnCandidates,
                        selectedId = uiState.selectedReturn?.id,
                        onCandidateSelected = viewModel::onReturnCandidateSelected,
                        modifier = Modifier.padding(top = 8.dp),
                    )
                }
                uiState.selectedReturn?.let {
                    Text(
                        text = "Location confirmed",
                        modifier = Modifier.padding(top = 4.dp),
                        color = MaterialTheme.colorScheme.primary,
                    )
                }
            }

            Spacer(modifier = Modifier.height(16.dp))
            HorizontalDivider()
            Spacer(modifier = Modifier.height(8.dp))

            Text(text = "Ports of Call")

            if (uiState.portsOfCall.isEmpty()) {
                Text(
                    text = "No ports of call yet.",
                    modifier = Modifier.padding(vertical = 8.dp),
                )
            } else {
                uiState.portsOfCall.forEach { port ->
                    val dayOfCruise = ChronoUnit.DAYS.between(uiState.sailDate, port.date) + 1
                    val displayName = port.portName
                    val geocodeStatus = if (port.latitude != null) "geocoded" else "not geocoded"
                    ListItem(
                        headlineContent = { Text(displayName) },
                        supportingContent = { Text("Day $dayOfCruise  \u2022  ${port.date}  \u2022  $geocodeStatus") },
                        trailingContent = {
                            Icon(
                                imageVector = Icons.Default.Edit,
                                contentDescription = "Edit $displayName",
                                tint = MaterialTheme.colorScheme.onSurfaceVariant,
                            )
                        },
                        modifier = Modifier.clickable { editingPort = port },
                    )
                    HorizontalDivider()
                }
            }

            OutlinedButton(
                onClick = { showPortSheet = true },
                modifier = Modifier.padding(top = 8.dp),
            ) {
                Text("+ Add Port of Call")
            }
        }
    }

    if (showPortSheet) {
        val lastPortDate = uiState.portsOfCall.maxByOrNull { it.date }?.date
        PortOfCallSheet(
            cruiseId = uiState.cruiseId,
            sailDate = uiState.sailDate,
            returnDate = uiState.returnDate,
            lastPortDate = lastPortDate,
            onSave = { port -> viewModel.addPortOfCall(port) },
            onDismiss = { showPortSheet = false },
            onGeocode = { query -> viewModel.geocodeQuery(query) },
        )
    }

    editingPort?.let { port ->
        PortOfCallSheet(
            cruiseId = uiState.cruiseId,
            sailDate = uiState.sailDate,
            returnDate = uiState.returnDate,
            existingPort = port,
            onSave = { updated -> viewModel.updatePortOfCall(updated) },
            onDelete = { deleted -> viewModel.deletePortOfCall(deleted) },
            onDismiss = { editingPort = null },
            onGeocode = { query -> viewModel.geocodeQuery(query) },
        )
    }

    if (showSailDatePicker) {
        val sailDatePickerState = rememberDatePickerState(
            initialSelectedDateMillis = uiState.sailDate.atStartOfDay(ZoneOffset.UTC).toInstant().toEpochMilli(),
        )
        DatePickerDialog(
            onDismissRequest = { showSailDatePicker = false },
            confirmButton = {
                TextButton(onClick = {
                    sailDatePickerState.selectedDateMillis?.let { millis ->
                        val date = Instant.ofEpochMilli(millis).atZone(ZoneOffset.UTC).toLocalDate()
                        viewModel.onSailDateChange(date)
                    }
                    showSailDatePicker = false
                }) { Text("OK") }
            },
            dismissButton = {
                TextButton(onClick = { showSailDatePicker = false }) { Text("Cancel") }
            },
        ) {
            DatePicker(state = sailDatePickerState)
        }
    }

    if (showReturnDatePicker) {
        val returnDatePickerState = rememberDatePickerState(
            initialSelectedDateMillis = uiState.returnDate.atStartOfDay(ZoneOffset.UTC).toInstant().toEpochMilli(),
        )
        DatePickerDialog(
            onDismissRequest = { showReturnDatePicker = false },
            confirmButton = {
                TextButton(onClick = {
                    returnDatePickerState.selectedDateMillis?.let { millis ->
                        val date = Instant.ofEpochMilli(millis).atZone(ZoneOffset.UTC).toLocalDate()
                        viewModel.onReturnDateChange(date)
                    }
                    showReturnDatePicker = false
                }) { Text("OK") }
            },
            dismissButton = {
                TextButton(onClick = { showReturnDatePicker = false }) { Text("Cancel") }
            },
        ) {
            DatePicker(state = returnDatePickerState)
        }
    }
}
