// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import org.jewzaam.cruiseweather.data.local.cruiseports.CruisePort
import org.jewzaam.cruiseweather.data.local.cruiseports.CruisePortMatcher
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import org.jewzaam.cruiseweather.domain.usecase.GeocodePortUseCase
import java.time.LocalDate
import java.time.temporal.ChronoUnit
import javax.inject.Inject

data class CruiseEditUiState(
    val isLoading: Boolean = false,
    val isSaved: Boolean = false,
    val savedCruiseId: Long? = null,
    val error: String? = null,
    // Cruise fields
    val cruiseId: Long = 0L,
    val name: String = "",
    val cruiseLine: String = "",
    val shipName: String = "",
    val sailDate: LocalDate = LocalDate.now(),
    val returnDate: LocalDate = LocalDate.now(),
    // Departure port
    val departurePortName: String = "",
    val selectedDeparture: GeocodingCandidate? = null,
    // Return port
    val hasDifferentReturnPort: Boolean = false,
    val returnPortName: String = "",
    val selectedReturn: GeocodingCandidate? = null,
    // Ports of call (local staging — not persisted until save)
    val portsOfCall: List<PortOfCall> = emptyList(),
)

@HiltViewModel
class CruiseEditViewModel @Inject constructor(
    private val cruiseRepository: CruiseRepository,
    private val weatherRepository: WeatherRepository,
    private val geocodePortUseCase: GeocodePortUseCase,
    private val cruisePortMatcher: CruisePortMatcher,
) : ViewModel() {

    private val _uiState = MutableStateFlow(CruiseEditUiState())
    val uiState: StateFlow<CruiseEditUiState> = _uiState.asStateFlow()

    // Original port IDs loaded from DB — used to diff on save
    private var originalPortIds: Set<Long> = emptySet()
    // Original sail date — used to detect date changes that invalidate weather
    private var originalSailDate: LocalDate? = null

    fun loadCruise(cruiseId: Long) {
        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true) }
            val cruiseWithPorts = cruiseRepository.getCruiseWithPorts(cruiseId).first()
            if (cruiseWithPorts != null) {
                val cruise = cruiseWithPorts.cruise
                val departure = cruiseWithPorts.departurePort
                val returnPort = cruiseWithPorts.returnPort
                val hasDifferentReturn = cruise.returnPortName != null
                val portsOfCall = cruiseWithPorts.portsOfCall
                originalPortIds = portsOfCall.map { it.id }.toSet()
                originalSailDate = cruise.sailDate
                _uiState.update { state ->
                    state.copy(
                        isLoading = false,
                        cruiseId = cruise.id,
                        name = cruise.name,
                        cruiseLine = cruise.cruiseLine,
                        shipName = cruise.shipName,
                        sailDate = cruise.sailDate,
                        returnDate = cruise.returnDate,
                        departurePortName = departure?.resolvedDisplayName
                            ?: departure?.portName ?: cruise.departurePortName,
                        selectedDeparture = departure?.let {
                            val lat = it.latitude
                            val lon = it.longitude
                            if (lat != null && lon != null) {
                                GeocodingCandidate(
                                    id = it.id,
                                    displayName = it.resolvedDisplayName ?: it.portName,
                                    latitude = lat,
                                    longitude = lon,
                                )
                            } else null
                        },
                        hasDifferentReturnPort = hasDifferentReturn,
                        returnPortName = returnPort?.takeIf { hasDifferentReturn }?.let {
                            it.resolvedDisplayName ?: it.portName
                        } ?: cruise.returnPortName ?: "",
                        selectedReturn = returnPort?.takeIf { hasDifferentReturn }?.let {
                            val lat = it.latitude
                            val lon = it.longitude
                            if (lat != null && lon != null) {
                                GeocodingCandidate(
                                    id = it.id,
                                    displayName = it.resolvedDisplayName ?: it.portName,
                                    latitude = lat,
                                    longitude = lon,
                                )
                            } else null
                        },
                        portsOfCall = portsOfCall,
                    )
                }
            } else {
                _uiState.update { it.copy(isLoading = false) }
            }
        }
    }

    fun onNameChange(value: String) = _uiState.update { it.copy(name = value) }
    fun onCruiseLineChange(value: String) = _uiState.update { it.copy(cruiseLine = value) }
    fun onShipNameChange(value: String) = _uiState.update { it.copy(shipName = value) }
    fun onSailDateChange(value: LocalDate) = _uiState.update {
        // Shift all dates to maintain the same trip structure
        val offset = ChronoUnit.DAYS.between(it.sailDate, value)
        it.copy(
            sailDate = value,
            returnDate = it.returnDate.plusDays(offset),
            portsOfCall = it.portsOfCall.map { port -> port.copy(date = port.date.plusDays(offset)) },
        )
    }
    fun onReturnDateChange(value: LocalDate) = _uiState.update { it.copy(returnDate = value) }
    fun onDateRangeChange(sailDate: LocalDate, returnDate: LocalDate) =
        _uiState.update { it.copy(sailDate = sailDate, returnDate = returnDate) }

    fun onDepartureChanged(displayName: String, candidate: GeocodingCandidate?) {
        _uiState.update { it.copy(departurePortName = displayName, selectedDeparture = candidate) }
    }

    fun onHasDifferentReturnPortChange(value: Boolean) {
        _uiState.update {
            it.copy(
                hasDifferentReturnPort = value,
                returnPortName = "",
                selectedReturn = null,
            )
        }
    }

    fun onReturnChanged(displayName: String, candidate: GeocodingCandidate?) {
        _uiState.update { it.copy(returnPortName = displayName, selectedReturn = candidate) }
    }

    fun saveCruise() {
        val state = _uiState.value
        if (state.name.isBlank()) {
            _uiState.update { it.copy(error = "Cruise name is required") }
            return
        }
        if (state.selectedDeparture == null) {
            _uiState.update { it.copy(error = "Build an itinerary first") }
            return
        }

        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true, error = null) }
            try {
                val dep = state.selectedDeparture
                val cruise = Cruise(
                    id = state.cruiseId,
                    name = state.name.trim(),
                    cruiseLine = state.cruiseLine,
                    shipName = state.shipName.trim(),
                    sailDate = state.sailDate,
                    returnDate = state.returnDate,
                    departurePortName = dep.displayName,
                    returnPortName = if (state.hasDifferentReturnPort) {
                        state.selectedReturn?.displayName ?: state.returnPortName.trim()
                    } else null,
                )

                val departurePorts = buildDeparturePorts(cruise = cruise, state = state)
                val currentPortIds = state.portsOfCall.filter { it.id != 0L }.map { it.id }.toSet()
                val deletedPortIds = originalPortIds - currentPortIds
                val savedId = cruiseRepository.saveCruise(
                    cruise = cruise,
                    departurePorts = departurePorts,
                    portsOfCall = state.portsOfCall,
                    deletedPortIds = deletedPortIds,
                )

                // Invalidate weather if sail date changed (dates shifted, old weather is wrong)
                if (originalSailDate != null && originalSailDate != state.sailDate) {
                    val allPortIds = (currentPortIds + originalPortIds).toList()
                    weatherRepository.invalidateWeatherForPorts(allPortIds)
                }

                _uiState.update { it.copy(isLoading = false, isSaved = true, savedCruiseId = savedId) }
            } catch (e: Exception) {
                _uiState.update { it.copy(isLoading = false, error = e.message ?: "Failed to save cruise") }
            }
        }
    }

    private fun buildDeparturePorts(cruise: Cruise, state: CruiseEditUiState): List<PortOfCall> {
        val ports = mutableListOf<PortOfCall>()
        val dep = state.selectedDeparture
        ports.add(
            PortOfCall(
                cruiseId = cruise.id,
                portName = state.departurePortName.trim(),
                date = cruise.sailDate,
                type = PortType.DEPARTURE,
                latitude = dep?.latitude,
                longitude = dep?.longitude,
                resolvedDisplayName = dep?.displayName,
                sortOrder = 0,
            ),
        )
        val returnName = cruise.returnPortName
        if (returnName != null) {
            val ret = state.selectedReturn
            ports.add(
                PortOfCall(
                    cruiseId = cruise.id,
                    portName = state.returnPortName.trim(),
                    date = cruise.returnDate,
                    type = PortType.RETURN,
                    latitude = ret?.latitude,
                    longitude = ret?.longitude,
                    resolvedDisplayName = ret?.displayName,
                    sortOrder = Int.MAX_VALUE,
                ),
            )
        } else {
            ports.add(
                PortOfCall(
                    cruiseId = cruise.id,
                    portName = state.departurePortName.trim(),
                    date = cruise.returnDate,
                    type = PortType.RETURN,
                    latitude = dep?.latitude,
                    longitude = dep?.longitude,
                    resolvedDisplayName = dep?.displayName,
                    sortOrder = Int.MAX_VALUE,
                ),
            )
        }
        return ports
    }

    // All port operations are local-only — persisted on saveCruise()
    fun addPortOfCall(port: PortOfCall) {
        _uiState.update { state ->
            // Replace any existing SEA_DAY on the same date, transferring notes
            val existingSeaDay = state.portsOfCall.firstOrNull {
                it.date == port.date && it.type == PortType.SEA_DAY
            }
            val portWithNotes = if (existingSeaDay != null && existingSeaDay.notes.isNotBlank() && port.notes.isBlank()) {
                port.copy(notes = existingSeaDay.notes)
            } else {
                port
            }
            val filtered = if (existingSeaDay != null) {
                state.portsOfCall.filter { it.localId != existingSeaDay.localId }
            } else {
                state.portsOfCall
            }
            state.copy(portsOfCall = filtered + portWithNotes)
        }
    }

    fun updatePortOfCall(port: PortOfCall) {
        _uiState.update { state ->
            state.copy(portsOfCall = state.portsOfCall.map { if (it.localId == port.localId) port else it })
        }
    }

    fun deletePortOfCall(port: PortOfCall) {
        _uiState.update { state ->
            state.copy(portsOfCall = state.portsOfCall.filter { it.localId != port.localId })
        }
    }

    fun clearError() = _uiState.update { it.copy(error = null) }

    fun searchLocalPorts(query: String): List<CruisePort> =
        cruisePortMatcher.search(query)

    fun generateItinerarySlots(): List<ItinerarySlot>? {
        val state = _uiState.value
        val totalDays = java.time.temporal.ChronoUnit.DAYS.between(state.sailDate, state.returnDate).toInt() + 1
        if (totalDays < 2) return null

        // Build a map of date → port for quick lookup
        val allPorts = state.portsOfCall.associateBy { it.date }

        // Find departure and return ports from DB
        // (these aren't in portsOfCall — they're separate)
        val depName = state.departurePortName
        val depCandidate = state.selectedDeparture
        val retName = if (state.hasDifferentReturnPort) state.returnPortName else ""
        val retCandidate = state.selectedReturn

        return (1..totalDays).map { dayNum ->
            val date = state.sailDate.plusDays(dayNum.toLong() - 1)
            val isFirst = dayNum == 1
            val isLast = dayNum == totalDays

            when {
                isFirst -> ItinerarySlot(
                    dayNumber = dayNum,
                    date = date,
                    portQuery = depName,
                    resolvedPort = depCandidate?.let {
                        CruisePort("dep", it.displayName, it.latitude, it.longitude, "", emptyList())
                    },
                )
                isLast -> ItinerarySlot(
                    dayNumber = dayNum,
                    date = date,
                    portQuery = retName,
                    resolvedPort = retCandidate?.let {
                        CruisePort("ret", it.displayName, it.latitude, it.longitude, "", emptyList())
                    },
                )
                else -> {
                    val port = allPorts[date]
                    ItinerarySlot(
                        dayNumber = dayNum,
                        date = date,
                        portQuery = when (port?.type) {
                            PortType.SEA_DAY -> ""
                            null -> ""
                            else -> port.portName
                        },
                        resolvedPort = port?.let {
                            if (it.latitude != null && it.longitude != null && it.type != PortType.SEA_DAY) {
                                CruisePort(
                                    "existing-${it.id}", it.resolvedDisplayName ?: it.portName,
                                    it.latitude, it.longitude, "", emptyList(),
                                )
                            } else null
                        },
                    )
                }
            }
        }
    }

    fun saveItinerary(slots: List<ItinerarySlot>) {
        val state = _uiState.value

        if (slots.isEmpty()) return

        // Last slot is always the return day.
        // Intermediate slots are everything except the last.
        val intermediateSlots = slots.dropLast(1)
        val returnSlot = slots.last()

        // Return date = sail date + (slots - 1). E.g. 4 slots → Day 1..4 → returnDate = sailDate + 3
        val returnDate = state.sailDate.plusDays(slots.size.toLong() - 1)

        // Departure port: if Day 1 was edited in the builder, update it
        val firstSlot = slots.firstOrNull()
        val updatedDepartureName: String?
        val updatedDepartureCandidate: GeocodingCandidate?
        if (firstSlot != null && firstSlot.dayNumber == 1 && firstSlot.resolvedPort != null) {
            updatedDepartureName = firstSlot.resolvedPort.displayName
            updatedDepartureCandidate = GeocodingCandidate(
                id = firstSlot.resolvedPort.id.hashCode().toLong(),
                displayName = firstSlot.resolvedPort.displayName,
                latitude = firstSlot.resolvedPort.latitude,
                longitude = firstSlot.resolvedPort.longitude,
            )
        } else {
            updatedDepartureName = null
            updatedDepartureCandidate = null
        }

        // Determine actual intermediate slots (skip Day 1 if it was the departure)
        val portSlots = if (intermediateSlots.firstOrNull()?.dayNumber == 1) {
            intermediateSlots.drop(1)
        } else {
            intermediateSlots
        }

        // Return port: filled return slot with a different port = different return port
        val dep = updatedDepartureCandidate ?: state.selectedDeparture
        val returnPortName: String?
        val returnCandidate: GeocodingCandidate?
        if (returnSlot.portQuery.isNotBlank() && returnSlot.resolvedPort != null &&
            returnSlot.resolvedPort.displayName != dep?.displayName
        ) {
            returnPortName = returnSlot.resolvedPort.displayName
            returnCandidate = GeocodingCandidate(
                id = returnSlot.resolvedPort.id.hashCode().toLong(),
                displayName = returnSlot.resolvedPort.displayName,
                latitude = returnSlot.resolvedPort.latitude,
                longitude = returnSlot.resolvedPort.longitude,
            )
        } else {
            returnPortName = null
            returnCandidate = null
        }

        // Build ports of call from intermediate slots only
        val intermediatePorts = portSlots.map { slot ->
            if (slot.portQuery.isBlank()) {
                PortOfCall(
                    cruiseId = state.cruiseId,
                    portName = "At Sea",
                    date = slot.date,
                    type = PortType.SEA_DAY,
                    sortOrder = slot.dayNumber * 10,
                )
            } else {
                val port = slot.resolvedPort
                PortOfCall(
                    cruiseId = state.cruiseId,
                    portName = slot.portQuery,
                    date = slot.date,
                    type = PortType.PORT_OF_CALL,
                    latitude = port?.latitude,
                    longitude = port?.longitude,
                    resolvedDisplayName = port?.displayName,
                    sortOrder = slot.dayNumber * 10,
                )
            }
        }

        _uiState.update {
            it.copy(
                returnDate = returnDate,
                departurePortName = updatedDepartureName ?: it.departurePortName,
                selectedDeparture = updatedDepartureCandidate ?: it.selectedDeparture,
                hasDifferentReturnPort = returnPortName != null,
                returnPortName = returnPortName ?: "",
                selectedReturn = returnCandidate,
                portsOfCall = intermediatePorts,
            )
        }
    }

    suspend fun geocodeQuery(query: String): List<GeocodingCandidate> =
        geocodePortUseCase(query = query).getOrDefault(emptyList())
}
