// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import org.jewzaam.cruiseweather.data.local.cruiseports.CruisePort
import org.jewzaam.cruiseweather.data.local.cruiseports.CruisePortMatcher
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import java.time.LocalDate
import java.time.temporal.ChronoUnit
import javax.inject.Inject

data class ItinerarySlot(
    val dayNumber: Int,
    val date: LocalDate,
    val portQuery: String = "",
    val resolvedPort: CruisePort? = null,
    val notes: String = "",
)

data class CruiseEditUiState(
    val isLoading: Boolean = false,
    val isSaved: Boolean = false,
    val savedCruiseId: Long? = null,
    val error: String? = null,
    val cruiseId: Long = 0L,
    val name: String = "",
    val cruiseLine: String = "",
    val shipName: String = "",
    val sailDate: LocalDate = LocalDate.now(),
    val loadedSlots: List<ItinerarySlot>? = null,
)

@HiltViewModel
class CruiseEditViewModel @Inject constructor(
    private val cruiseRepository: CruiseRepository,
    private val weatherRepository: WeatherRepository,
    private val cruisePortMatcher: CruisePortMatcher,
) : ViewModel() {

    private val _uiState = MutableStateFlow(CruiseEditUiState())
    val uiState: StateFlow<CruiseEditUiState> = _uiState.asStateFlow()

    // Original port IDs loaded from DB — used to diff on save
    private var originalPortIds: Set<Long> = emptySet()
    private var originalSailDate: LocalDate? = null

    // loadedSlots is in uiState for compose reactivity

    fun loadCruise(cruiseId: Long) {
        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true) }
            val cruiseWithPorts = cruiseRepository.getCruiseWithPorts(cruiseId).first()
            if (cruiseWithPorts != null) {
                val cruise = cruiseWithPorts.cruise
                val departure = cruiseWithPorts.departurePort
                val returnPort = cruiseWithPorts.returnPort
                val portsOfCall = cruiseWithPorts.portsOfCall
                originalPortIds = portsOfCall.map { it.id }.toSet()
                originalSailDate = cruise.sailDate

                // Build slots from existing data
                val totalDays = ChronoUnit.DAYS.between(cruise.sailDate, cruise.returnDate).toInt() + 1
                val portsByDate = portsOfCall.associateBy { it.date }
                val hasDifferentReturn = cruise.returnPortName != null

                val builtSlots = (1..totalDays).map { dayNum ->
                    val date = cruise.sailDate.plusDays(dayNum.toLong() - 1)
                    val isFirst = dayNum == 1
                    val isLast = dayNum == totalDays
                    when {
                        isFirst -> ItinerarySlot(
                            dayNumber = dayNum, date = date,
                            portQuery = departure?.resolvedDisplayName ?: departure?.portName ?: cruise.departurePortName,
                            resolvedPort = departure?.let {
                                val lat = it.latitude; val lon = it.longitude
                                if (lat != null && lon != null) CruisePort("dep", it.resolvedDisplayName ?: it.portName, lat, lon, "", emptyList()) else null
                            },
                            notes = departure?.notes ?: "",
                        )
                        isLast -> ItinerarySlot(
                            dayNumber = dayNum, date = date,
                            portQuery = if (hasDifferentReturn) (returnPort?.resolvedDisplayName ?: returnPort?.portName ?: cruise.returnPortName ?: "") else "",
                            resolvedPort = returnPort?.takeIf { hasDifferentReturn }?.let {
                                val lat = it.latitude; val lon = it.longitude
                                if (lat != null && lon != null) CruisePort("ret", it.resolvedDisplayName ?: it.portName, lat, lon, "", emptyList()) else null
                            },
                            notes = returnPort?.notes ?: "",
                        )
                        else -> {
                            val port = portsByDate[date]
                            ItinerarySlot(
                                dayNumber = dayNum, date = date,
                                portQuery = when (port?.type) { PortType.SEA_DAY -> ""; null -> ""; else -> port.portName },
                                resolvedPort = port?.let {
                                    if (it.latitude != null && it.longitude != null && it.type != PortType.SEA_DAY)
                                        CruisePort("existing-${it.id}", it.resolvedDisplayName ?: it.portName, it.latitude, it.longitude, "", emptyList())
                                    else null
                                },
                                notes = port?.notes ?: "",
                            )
                        }
                    }
                }

                _uiState.update { state ->
                    state.copy(
                        isLoading = false,
                        cruiseId = cruise.id,
                        name = cruise.name,
                        cruiseLine = cruise.cruiseLine,
                        shipName = cruise.shipName,
                        sailDate = cruise.sailDate,
                        loadedSlots = builtSlots,
                    )
                }
            } else {
                _uiState.update { it.copy(isLoading = false) }
            }
        }
    }

    fun onNameChange(value: String) = _uiState.update { it.copy(name = value) }
    fun onCruiseLineChange(value: String) = _uiState.update { it.copy(cruiseLine = value) }
    fun onShipNameChange(value: String) = _uiState.update { it.copy(shipName = value) }

    fun onSailDateChange(value: LocalDate) = _uiState.update {
        it.copy(sailDate = value)
    }

    fun clearError() = _uiState.update { it.copy(error = null) }

    fun searchLocalPorts(query: String): List<CruisePort> =
        cruisePortMatcher.search(query)

    fun saveFromSlots(slots: List<ItinerarySlot>) {
        val state = _uiState.value
        if (state.name.isBlank()) {
            _uiState.update { it.copy(error = "Cruise name is required") }
            return
        }
        if (slots.size < 2) {
            _uiState.update { it.copy(error = "Itinerary must have at least embark and debark") }
            return
        }
        val firstSlot = slots.first()
        if (firstSlot.resolvedPort == null) {
            _uiState.update { it.copy(error = "Select an embark port") }
            return
        }

        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true, error = null) }
            try {
                val sailDate = state.sailDate
                val returnDate = sailDate.plusDays(slots.size.toLong() - 1)

                // Build departure port
                val depPort = firstSlot.resolvedPort
                val departurePortName = depPort.displayName

                // Build return port
                val lastSlot = slots.last()
                val hasDifferentReturn = lastSlot.portQuery.isNotBlank() && lastSlot.resolvedPort != null
                    && lastSlot.resolvedPort.displayName != depPort.displayName
                val returnPortName = if (hasDifferentReturn) lastSlot.resolvedPort!!.displayName else null

                val cruise = Cruise(
                    id = state.cruiseId,
                    name = state.name.trim(),
                    cruiseLine = state.cruiseLine,
                    shipName = state.shipName.trim(),
                    sailDate = sailDate,
                    returnDate = returnDate,
                    departurePortName = departurePortName,
                    returnPortName = returnPortName,
                )

                // Build departure/return PortOfCall list
                val departurePorts = mutableListOf<PortOfCall>()
                departurePorts.add(PortOfCall(
                    cruiseId = cruise.id, portName = departurePortName,
                    date = sailDate, type = PortType.DEPARTURE,
                    latitude = depPort.latitude, longitude = depPort.longitude,
                    resolvedDisplayName = depPort.displayName, sortOrder = 0,
                    notes = firstSlot.notes,
                ))
                if (hasDifferentReturn) {
                    val retPort = lastSlot.resolvedPort!!
                    departurePorts.add(PortOfCall(
                        cruiseId = cruise.id, portName = retPort.displayName,
                        date = returnDate, type = PortType.RETURN,
                        latitude = retPort.latitude, longitude = retPort.longitude,
                        resolvedDisplayName = retPort.displayName, sortOrder = Int.MAX_VALUE,
                        notes = lastSlot.notes,
                    ))
                } else {
                    departurePorts.add(PortOfCall(
                        cruiseId = cruise.id, portName = departurePortName,
                        date = returnDate, type = PortType.RETURN,
                        latitude = depPort.latitude, longitude = depPort.longitude,
                        resolvedDisplayName = depPort.displayName, sortOrder = Int.MAX_VALUE,
                        notes = lastSlot.notes,
                    ))
                }

                // Build intermediate ports from slots (skip first and last)
                val intermediateSlots = slots.drop(1).dropLast(1)
                val portsOfCall = intermediateSlots.mapIndexed { index, slot ->
                    val slotDate = sailDate.plusDays(index.toLong() + 1)
                    if (slot.portQuery.isBlank()) {
                        PortOfCall(
                            cruiseId = cruise.id, portName = "At Sea",
                            date = slotDate, type = PortType.SEA_DAY,
                            sortOrder = (index + 2) * 10, notes = slot.notes,
                        )
                    } else {
                        val port = slot.resolvedPort
                        PortOfCall(
                            cruiseId = cruise.id, portName = slot.portQuery,
                            date = slotDate, type = PortType.PORT_OF_CALL,
                            latitude = port?.latitude, longitude = port?.longitude,
                            resolvedDisplayName = port?.displayName,
                            sortOrder = (index + 2) * 10, notes = slot.notes,
                        )
                    }
                }

                val deletedPortIds = originalPortIds - emptySet<Long>() // all old ports replaced
                val savedId = cruiseRepository.saveCruise(
                    cruise = cruise,
                    departurePorts = departurePorts,
                    portsOfCall = portsOfCall,
                    deletedPortIds = deletedPortIds,
                )

                // Invalidate weather if sail date changed
                if (originalSailDate != null && originalSailDate != state.sailDate) {
                    val allPortIds = originalPortIds.toList()
                    weatherRepository.invalidateWeatherForPorts(allPortIds)
                }

                _uiState.update { it.copy(isLoading = false, isSaved = true, savedCruiseId = savedId) }
            } catch (e: Exception) {
                _uiState.update { it.copy(isLoading = false, error = e.message ?: "Failed to save cruise") }
            }
        }
    }
}
