// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Close
import androidx.compose.material3.Button
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ExposedDropdownMenuBox
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.MenuAnchorType
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import kotlinx.coroutines.delay
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import org.jewzaam.cruiseweather.data.local.cruiseports.CruisePort
import java.time.LocalDate

data class ItinerarySlot(
    val dayNumber: Int,
    val date: LocalDate,
    val portQuery: String = "",
    val resolvedPort: CruisePort? = null,
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ItineraryBuilderSheet(
    sailDate: LocalDate,
    departurePortName: String,
    existingSlots: List<ItinerarySlot>?,
    onSearchPorts: (String) -> List<CruisePort>,
    onDone: (List<ItinerarySlot>) -> Unit,
    onDismiss: () -> Unit,
) {
    // All slots including Day 1 (departure) and last (return).
    // Day 1 is editable. Last slot is the return day.
    val slots = remember {
        mutableStateListOf<ItinerarySlot>().apply {
            if (existingSlots != null && existingSlots.isNotEmpty()) {
                addAll(existingSlots)
            } else {
                // Day 1 (departure), 2 intermediate, Return
                add(ItinerarySlot(dayNumber = 1, date = sailDate, portQuery = departurePortName))
                add(ItinerarySlot(dayNumber = 2, date = sailDate.plusDays(1)))
                add(ItinerarySlot(dayNumber = 3, date = sailDate.plusDays(2)))
                add(ItinerarySlot(dayNumber = 4, date = sailDate.plusDays(3))) // Return
            }
        }
    }

    fun renumberSlots() {
        for (i in slots.indices) {
            val newDay = i + 1
            val newDate = sailDate.plusDays(i.toLong())
            if (slots[i].dayNumber != newDay || slots[i].date != newDate) {
                slots[i] = slots[i].copy(dayNumber = newDay, date = newDate)
            }
        }
    }

    Dialog(
        onDismissRequest = onDismiss,
        properties = DialogProperties(usePlatformDefaultWidth = false),
    ) {
        Surface(
            shape = MaterialTheme.shapes.extraLarge,
            tonalElevation = 6.dp,
            modifier = Modifier.padding(8.dp),
        ) {
            Column {
                TopAppBar(
                    title = { Text("Build Itinerary") },
                    navigationIcon = {
                        TextButton(onClick = onDismiss) { Text("Cancel") }
                    },
                    actions = {
                        Button(
                            onClick = { onDone(slots.toList()) },
                            modifier = Modifier.padding(end = 8.dp),
                        ) {
                            Text("Done")
                        }
                    },
                )

                LazyColumn(
                    modifier = Modifier
                        .weight(1f)
                        .padding(horizontal = 8.dp),
                ) {
                    itemsIndexed(slots, key = { index, _ -> index }) { index, slot ->
                        val isFirst = index == 0
                        val isLast = index == slots.size - 1
                        val label = when {
                            isFirst -> "Day 1"
                            isLast -> "Return"
                            else -> "Day ${slot.dayNumber}"
                        }
                        val placeholder = when {
                            isFirst -> "Departure port"
                            isLast -> "Same as departure"
                            else -> "Sea day"
                        }

                        ItineraryRow(
                            slot = slot,
                            label = label,
                            placeholder = placeholder,
                            canRemove = !isFirst && !isLast && slots.size > 3,
                            onSearchPorts = onSearchPorts,
                            onSlotUpdated = { updated -> slots[index] = updated },
                            onRemove = {
                                slots.removeAt(index)
                                renumberSlots()
                            },
                        )

                        // "+ Add Day" button between the last intermediate day and Return
                        if (!isLast && index == slots.size - 2) {
                            TextButton(
                                onClick = {
                                    // Insert before the return slot
                                    val newDay = slots.size // will be renumbered
                                    slots.add(
                                        slots.size - 1,
                                        ItinerarySlot(dayNumber = newDay, date = sailDate.plusDays(newDay.toLong() - 1)),
                                    )
                                    renumberSlots()
                                },
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(start = 56.dp),
                            ) {
                                Text("+ Add Day")
                            }
                        }
                    }
                }
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun ItineraryRow(
    slot: ItinerarySlot,
    label: String,
    placeholder: String,
    canRemove: Boolean,
    onSearchPorts: (String) -> List<CruisePort>,
    onSlotUpdated: (ItinerarySlot) -> Unit,
    onRemove: () -> Unit,
) {
    var expanded by remember { mutableStateOf(false) }
    var suggestions by remember { mutableStateOf<List<CruisePort>>(emptyList()) }
    var localQuery by remember(slot.portQuery) { mutableStateOf(slot.portQuery) }

    // Debounce search to avoid ANR
    LaunchedEffect(localQuery) {
        if (localQuery.length < 2 || slot.resolvedPort != null) {
            suggestions = emptyList()
            expanded = false
            return@LaunchedEffect
        }
        delay(200)
        suggestions = onSearchPorts(localQuery)
        expanded = suggestions.isNotEmpty()
    }

    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 2.dp),
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.labelLarge,
            modifier = Modifier.width(56.dp),
        )

        ExposedDropdownMenuBox(
            expanded = expanded && suggestions.isNotEmpty(),
            onExpandedChange = {},
            modifier = Modifier.weight(1f),
        ) {
            OutlinedTextField(
                value = localQuery,
                onValueChange = { query ->
                    localQuery = query
                    onSlotUpdated(slot.copy(portQuery = query, resolvedPort = null))
                },
                placeholder = { Text(placeholder) },
                modifier = Modifier
                    .fillMaxWidth()
                    .menuAnchor(MenuAnchorType.PrimaryEditable),
                singleLine = true,
                textStyle = MaterialTheme.typography.bodyMedium,
            )
            ExposedDropdownMenu(
                expanded = expanded && suggestions.isNotEmpty(),
                onDismissRequest = { expanded = false },
            ) {
                suggestions.forEach { port ->
                    DropdownMenuItem(
                        text = { Text(port.displayName) },
                        onClick = {
                            onSlotUpdated(
                                slot.copy(
                                    portQuery = port.displayName,
                                    resolvedPort = port,
                                ),
                            )
                            expanded = false
                            suggestions = emptyList()
                        },
                    )
                }
            }
        }

        if (canRemove) {
            IconButton(onClick = onRemove, modifier = Modifier.size(36.dp)) {
                Icon(
                    imageVector = Icons.Default.Close,
                    contentDescription = "Remove day",
                    tint = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.size(18.dp),
                )
            }
        } else {
            Spacer(modifier = Modifier.width(36.dp))
        }
    }
}
