// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import org.jewzaam.cruiseweather.ui.components.LocationPicker
import java.time.LocalDate
import java.time.temporal.ChronoUnit

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PortOfCallSheet(
    cruiseId: Long,
    sailDate: LocalDate,
    returnDate: LocalDate,
    existingPort: PortOfCall? = null,
    lastPortDate: LocalDate? = null,
    portType: PortType = PortType.PORT_OF_CALL,
    onSave: (PortOfCall) -> Unit,
    onDelete: ((PortOfCall) -> Unit)? = null,
    onDismiss: () -> Unit,
    onGeocode: suspend (String) -> List<GeocodingCandidate>,
) {
    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    val scope = rememberCoroutineScope()
    val effectiveType = existingPort?.type ?: portType
    val isSeaDay = effectiveType == PortType.SEA_DAY
    val needsLocation = !isSeaDay

    val title = when {
        existingPort != null -> when (effectiveType) {
            PortType.DEPARTURE -> "Edit Embark Port"
            PortType.RETURN -> "Edit Debark Port"
            PortType.SEA_DAY -> "Edit Sea Day Note"
            else -> "Edit Port of Call"
        }
        isSeaDay -> "Add Sea Day Note"
        else -> "Add Port of Call"
    }

    var displayName by remember { mutableStateOf(existingPort?.portName ?: "") }
    var selectedCandidate by remember {
        mutableStateOf(
            existingPort?.let { port ->
                val lat = port.latitude
                val lon = port.longitude
                if (lat != null && lon != null) {
                    GeocodingCandidate(
                        id = port.id,
                        displayName = port.resolvedDisplayName ?: port.portName,
                        latitude = lat,
                        longitude = lon,
                    )
                } else null
            },
        )
    }
    val defaultDate = existingPort?.date
        ?: (lastPortDate?.plusDays(1) ?: sailDate.plusDays(1)).coerceAtMost(returnDate)
    var date by remember { mutableStateOf(defaultDate) }
    var dateError by remember { mutableStateOf<String?>(null) }
    var notes by remember { mutableStateOf(existingPort?.notes ?: "") }
    var showDeleteConfirm by remember { mutableStateOf(false) }

    // For departure/return, date is fixed and location is always required
    val isDepartureOrReturn = effectiveType == PortType.DEPARTURE || effectiveType == PortType.RETURN
    val showDateControls = !isDepartureOrReturn

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
    ) {
        Column(modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp)) {
            Text(text = title)
            Spacer(modifier = Modifier.height(16.dp))

            if (needsLocation) {
                LocationPicker(
                    label = if (isDepartureOrReturn) "Port" else "Search location",
                    initialDisplayName = existingPort?.portName ?: "",
                    initialCandidate = selectedCandidate,
                    onSelectionChanged = { name, candidate ->
                        displayName = name
                        selectedCandidate = candidate
                    },
                    onGeocode = onGeocode,
                    autoFocus = existingPort == null,
                )
                Spacer(modifier = Modifier.height(16.dp))
            }

            if (showDateControls) {
                val dayOfCruise = ChronoUnit.DAYS.between(sailDate, date) + 1
                Text("Date: $date  (Day $dayOfCruise)")
                dateError?.let { Text(text = it) }
                Row {
                    OutlinedButton(onClick = {
                        val newDate = date.minusDays(1)
                        if (newDate >= sailDate) {
                            date = newDate
                            dateError = null
                        } else {
                            dateError = "Must be within cruise dates"
                        }
                    }) { Text("\u2212") }
                    Spacer(modifier = Modifier.width(8.dp))
                    OutlinedButton(onClick = {
                        val newDate = date.plusDays(1)
                        if (newDate <= returnDate) {
                            date = newDate
                            dateError = null
                        } else {
                            dateError = "Must be within cruise dates"
                        }
                    }) { Text("+") }
                }
                Spacer(modifier = Modifier.height(16.dp))
            }

            // Notes
            OutlinedTextField(
                value = notes,
                onValueChange = { notes = it },
                label = { Text("Notes") },
                modifier = Modifier.fillMaxWidth(),
                minLines = 3,
                maxLines = 6,
                placeholder = { Text("Excursions, dinner plans, reminders…") },
            )

            Spacer(modifier = Modifier.height(16.dp))

            // Action buttons
            Row {
                OutlinedButton(
                    onClick = {
                        scope.launch {
                            sheetState.hide()
                            onDismiss()
                        }
                    },
                    modifier = Modifier.weight(1f),
                ) {
                    Text("Cancel")
                }
                Spacer(modifier = Modifier.width(8.dp))
                Button(
                    onClick = {
                        val resolvedGeoName = selectedCandidate?.displayName
                            ?: existingPort?.resolvedDisplayName
                        val portName = when {
                            isSeaDay -> "At Sea"
                            displayName.isNotBlank() -> displayName.trim()
                            else -> return@Button
                        }
                        val saved = (existingPort ?: PortOfCall(
                            cruiseId = cruiseId,
                            portName = portName,
                            date = date,
                            type = effectiveType,
                        )).copy(
                            portName = portName,
                            date = if (isDepartureOrReturn) existingPort!!.date else date,
                            latitude = selectedCandidate?.latitude ?: existingPort?.latitude,
                            longitude = selectedCandidate?.longitude ?: existingPort?.longitude,
                            resolvedDisplayName = if (needsLocation) resolvedGeoName else null,
                            notes = notes,
                        )
                        onSave(saved)
                        scope.launch {
                            sheetState.hide()
                            onDismiss()
                        }
                    },
                    modifier = Modifier.weight(1f),
                    enabled = isSeaDay || (selectedCandidate != null && displayName.isNotBlank()),
                ) {
                    Text("Save")
                }
            }

            // Delete button (only when editing, not for departure/return)
            if (existingPort != null && onDelete != null && !isDepartureOrReturn) {
                Spacer(modifier = Modifier.height(8.dp))
                TextButton(
                    onClick = { showDeleteConfirm = true },
                    modifier = Modifier.fillMaxWidth(),
                    colors = ButtonDefaults.textButtonColors(
                        contentColor = MaterialTheme.colorScheme.error,
                    ),
                ) {
                    Text("Delete")
                }
            }

            Spacer(modifier = Modifier.height(16.dp))
        }
    }

    if (showDeleteConfirm && existingPort != null && onDelete != null) {
        AlertDialog(
            onDismissRequest = { showDeleteConfirm = false },
            title = { Text("Delete?") },
            text = { Text("Remove ${existingPort.resolvedDisplayName ?: existingPort.portName} from this cruise?") },
            confirmButton = {
                TextButton(
                    onClick = {
                        showDeleteConfirm = false
                        onDelete(existingPort)
                        scope.launch {
                            sheetState.hide()
                            onDismiss()
                        }
                    },
                    colors = ButtonDefaults.textButtonColors(
                        contentColor = MaterialTheme.colorScheme.error,
                    ),
                ) { Text("Delete") }
            },
            dismissButton = {
                TextButton(onClick = { showDeleteConfirm = false }) { Text("Keep") }
            },
        )
    }
}
