// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import org.jewzaam.cruiseweather.ui.components.GeocodingConfirmation
import java.time.LocalDate
import java.time.temporal.ChronoUnit
import java.util.Locale

/**
 * Title-case a string: capitalize the first letter of each word,
 * preserve any mid-word capitals (e.g. "mcdonald" → "Mcdonald", "McDonald" → "McDonald").
 */
private fun String.toTitleCase(): String =
    split(" ").joinToString(" ") { word ->
        if (word.isEmpty()) word
        else word[0].uppercaseChar() + word.substring(1)
    }

/**
 * Returns true if the geocoded display name is substantially different from the search query,
 * meaning the user likely wants a custom display name.
 */
private fun isNameMismatch(searchQuery: String, geoDisplayName: String): Boolean {
    // Strip commas and split into significant words (3+ chars)
    val searchWords = searchQuery.replace(",", " ").lowercase(Locale.ROOT)
        .split("\\s+".toRegex()).filter { it.length >= 3 }
    if (searchWords.isEmpty()) return false
    val geoLower = geoDisplayName.lowercase(Locale.ROOT)
    val matchCount = searchWords.count { word -> geoLower.contains(word) }
    // Mismatch if fewer than half the significant search words appear in the geocoded name
    return matchCount < (searchWords.size + 1) / 2
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PortOfCallSheet(
    cruiseId: Long,
    sailDate: LocalDate,
    returnDate: LocalDate,
    existingPort: PortOfCall? = null,
    lastPortDate: LocalDate? = null,
    onSave: (PortOfCall) -> Unit,
    onDelete: ((PortOfCall) -> Unit)? = null,
    onDismiss: () -> Unit,
    onGeocode: suspend (String) -> List<GeocodingCandidate>,
) {
    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    val scope = rememberCoroutineScope()

    // Search query — what the user types to find the location
    var searchQuery by remember { mutableStateOf(existingPort?.portName ?: "") }
    // Display name — what shows in the UI, editable after geocode selection
    var displayName by remember { mutableStateOf(existingPort?.portName ?: "") }
    val defaultDate = existingPort?.date
        ?: (lastPortDate?.plusDays(1) ?: sailDate.plusDays(1)).coerceAtMost(returnDate)
    var date by remember { mutableStateOf(defaultDate) }
    var candidates by remember { mutableStateOf<List<GeocodingCandidate>>(emptyList()) }
    var selectedCandidate by remember { mutableStateOf<GeocodingCandidate?>(null) }
    var isGeocoding by remember { mutableStateOf(false) }
    var dateError by remember { mutableStateOf<String?>(null) }
    var showDeleteConfirm by remember { mutableStateOf(false) }
    // Override is pre-checked when existing port has a custom display name
    var overrideDisplayName by remember {
        mutableStateOf(
            existingPort != null
                && existingPort.resolvedDisplayName != null
                && existingPort.portName != existingPort.resolvedDisplayName,
        )
    }
    val focusRequester = remember { FocusRequester() }
    val hasExistingCoords = existingPort?.latitude != null
    val isLocationLocked = selectedCandidate != null || hasExistingCoords

    // Auto-focus location field after sheet is composed
    LaunchedEffect(Unit) {
        delay(300)
        try {
            focusRequester.requestFocus()
        } catch (_: IllegalStateException) {
            // FocusRequester not yet attached
        }
    }

    // Auto-geocode after user stops typing for 800ms
    LaunchedEffect(searchQuery) {
        if (searchQuery.isBlank() || selectedCandidate != null) return@LaunchedEffect
        // Don't re-geocode when loading an existing port's name
        if (existingPort != null && searchQuery == existingPort.portName) return@LaunchedEffect
        delay(800)
        if (searchQuery.length >= 2) {
            isGeocoding = true
            val results = try {
                onGeocode(searchQuery)
            } catch (_: Exception) {
                emptyList()
            }
            isGeocoding = false
            if (results.size == 1) {
                val candidate = results.first()
                selectedCandidate = candidate
                if (isNameMismatch(searchQuery, candidate.displayName)) {
                    overrideDisplayName = true
                    displayName = searchQuery.toTitleCase()
                } else {
                    displayName = candidate.displayName
                }
                candidates = emptyList()
            } else {
                candidates = results
            }
        }
    }

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
    ) {
        Column(modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp)) {
            Text(text = if (existingPort != null) "Edit Port of Call" else "Add Port of Call")
            Spacer(modifier = Modifier.height(16.dp))

            if (!isLocationLocked) {
                // Search mode — user is typing to find a location
                OutlinedTextField(
                    value = searchQuery,
                    onValueChange = {
                        searchQuery = it
                        candidates = emptyList()
                        selectedCandidate = null
                    },
                    label = { Text("Search location") },
                    modifier = Modifier
                        .fillMaxWidth()
                        .focusRequester(focusRequester),
                    singleLine = true,
                    trailingIcon = {
                        if (isGeocoding) CircularProgressIndicator()
                    },
                )

                if (candidates.isNotEmpty()) {
                    GeocodingConfirmation(
                        candidates = candidates,
                        selectedId = null,
                        onCandidateSelected = { candidate ->
                            selectedCandidate = candidate
                            if (isNameMismatch(searchQuery, candidate.displayName)) {
                                overrideDisplayName = true
                                displayName = searchQuery.toTitleCase()
                            } else {
                                displayName = candidate.displayName
                            }
                            candidates = emptyList()
                        },
                        modifier = Modifier.padding(top = 8.dp),
                    )
                }
            } else {
                // Location locked — display name as text or editable field
                val geoName = selectedCandidate?.displayName
                    ?: existingPort?.resolvedDisplayName ?: ""
                if (overrideDisplayName) {
                    OutlinedTextField(
                        value = displayName,
                        onValueChange = { displayName = it },
                        label = { Text("Display name") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true,
                    )
                    if (geoName.isNotEmpty()) {
                        Text(
                            text = "Based on: $geoName",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                    }
                } else {
                    Text(
                        text = displayName,
                        style = MaterialTheme.typography.titleMedium,
                    )
                }
                TextButton(
                    onClick = {
                        selectedCandidate = null
                        candidates = emptyList()
                        searchQuery = ""
                    },
                ) {
                    Text("Change location", style = MaterialTheme.typography.labelSmall)
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(
                        checked = overrideDisplayName,
                        onCheckedChange = {
                            overrideDisplayName = it
                            if (!it) displayName = geoName
                        },
                    )
                    Text("Custom display name", style = MaterialTheme.typography.bodySmall)
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Date display with day-of-cruise indicator
            val dayOfCruise = ChronoUnit.DAYS.between(sailDate, date) + 1
            Text("Date: $date  (Day $dayOfCruise)")
            dateError?.let { Text(text = it) }
            Row {
                OutlinedButton(onClick = {
                    val newDate = date.minusDays(1)
                    if (newDate >= sailDate) {
                        date = newDate
                        dateError = null
                    } else {
                        dateError = "Must be within cruise dates"
                    }
                }) { Text("\u2212") }
                Spacer(modifier = Modifier.width(8.dp))
                OutlinedButton(onClick = {
                    val newDate = date.plusDays(1)
                    if (newDate <= returnDate) {
                        date = newDate
                        dateError = null
                    } else {
                        dateError = "Must be within cruise dates"
                    }
                }) { Text("+") }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Action buttons
            Row {
                OutlinedButton(
                    onClick = {
                        scope.launch {
                            sheetState.hide()
                            onDismiss()
                        }
                    },
                    modifier = Modifier.weight(1f),
                ) {
                    Text("Cancel")
                }
                Spacer(modifier = Modifier.width(8.dp))
                Button(
                    onClick = {
                        if (displayName.isBlank()) return@Button
                        val resolvedGeoName = selectedCandidate?.displayName
                            ?: existingPort?.resolvedDisplayName
                        val saved = (existingPort ?: PortOfCall(
                            cruiseId = cruiseId,
                            portName = displayName.trim(),
                            date = date,
                            type = PortType.PORT_OF_CALL,
                        )).copy(
                            portName = displayName.trim(),
                            date = date,
                            latitude = selectedCandidate?.latitude ?: existingPort?.latitude,
                            longitude = selectedCandidate?.longitude ?: existingPort?.longitude,
                            resolvedDisplayName = resolvedGeoName,
                        )
                        onSave(saved)
                        scope.launch {
                            sheetState.hide()
                            onDismiss()
                        }
                    },
                    modifier = Modifier.weight(1f),
                    enabled = isLocationLocked && displayName.isNotBlank(),
                ) {
                    Text("Save Port")
                }
            }

            // Delete button (only when editing an existing port)
            if (existingPort != null && onDelete != null) {
                Spacer(modifier = Modifier.height(8.dp))
                TextButton(
                    onClick = { showDeleteConfirm = true },
                    modifier = Modifier.fillMaxWidth(),
                    colors = ButtonDefaults.textButtonColors(
                        contentColor = MaterialTheme.colorScheme.error,
                    ),
                ) {
                    Text("Delete Port")
                }
            }

            Spacer(modifier = Modifier.height(16.dp))
        }
    }

    if (showDeleteConfirm && existingPort != null && onDelete != null) {
        AlertDialog(
            onDismissRequest = { showDeleteConfirm = false },
            title = { Text("Delete Port?") },
            text = { Text("Remove ${existingPort.resolvedDisplayName ?: existingPort.portName} from this cruise?") },
            confirmButton = {
                TextButton(
                    onClick = {
                        showDeleteConfirm = false
                        onDelete(existingPort)
                        scope.launch {
                            sheetState.hide()
                            onDismiss()
                        }
                    },
                    colors = ButtonDefaults.textButtonColors(
                        contentColor = MaterialTheme.colorScheme.error,
                    ),
                ) { Text("Delete") }
            },
            dismissButton = {
                TextButton(onClick = { showDeleteConfirm = false }) { Text("Keep") }
            },
        )
    }
}
