// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.data.local.cruiseports

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.serialization.json.Json
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class CruisePortRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val json: Json,
) {
    private val ports: List<CruisePort> by lazy {
        try {
            val text = context.assets.open("cruise_ports.json").bufferedReader().use { it.readText() }
            json.decodeFromString<List<CruisePort>>(text)
        } catch (e: Exception) {
            Timber.e(e, "Failed to load cruise_ports.json")
            emptyList()
        }
    }

    fun allPorts(): List<CruisePort> = ports
}
