// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.data.local.cruiseports

import kotlinx.serialization.Serializable

@Serializable
data class CruisePort(
    val id: String,
    val displayName: String,
    val latitude: Double,
    val longitude: Double,
    val country: String,
    val aliases: List<String>,
)
