// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.data.local.cruiseports

import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class CruisePortMatcher @Inject constructor(
    private val repository: CruisePortRepository,
) {
    fun search(query: String, limit: Int = 5): List<CruisePort> {
        val normalized = normalize(query)
        if (normalized.length < 2) return emptyList()

        return repository.allPorts()
            .mapNotNull { port -> scorePort(port, normalized)?.let { score -> port to score } }
            .filter { (_, score) -> score > 50 }
            .sortedByDescending { (_, score) -> score }
            .take(limit)
            .map { (port, _) -> port }
    }

    private fun scorePort(port: CruisePort, normalizedQuery: String): Int? {
        val allNames = port.aliases + port.displayName
        val bestAliasScore = allNames.maxOfOrNull { alias ->
            scoreAlias(normalize(alias), normalizedQuery)
        } ?: return null

        if (bestAliasScore <= 0) return null

        // Bonus if query contains the country name
        val countryBonus = if (normalizedQuery.contains(normalize(port.country))) 50 else 0
        return bestAliasScore + countryBonus
    }

    private fun scoreAlias(normalizedAlias: String, normalizedQuery: String): Int {
        // Exact match
        if (normalizedAlias == normalizedQuery) return 1000

        // Starts-with match
        if (normalizedAlias.startsWith(normalizedQuery)) {
            return 500 + (normalizedQuery.length * 100 / normalizedAlias.length)
        }

        // Contains match
        if (normalizedAlias.contains(normalizedQuery)) {
            return 300 + (normalizedQuery.length * 100 / normalizedAlias.length)
        }

        // Word overlap
        val queryWords = normalizedQuery.split("\\s+".toRegex()).filter { it.length >= 2 }
        if (queryWords.isEmpty()) return 0

        val aliasLower = normalizedAlias
        val matchedWords = queryWords.count { word -> aliasLower.contains(word) }
        if (matchedWords == 0) return 0

        return 100 * matchedWords / queryWords.size
    }

    companion object {
        fun normalize(input: String): String =
            input.lowercase()
                .replace(Regex("\\(.*?\\)"), "") // strip parenthetical content
                .replace(",", " ")
                .replace(Regex("\\s+"), " ")
                .trim()
    }
}
