// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.theme

import androidx.compose.ui.graphics.Color

val CruisePrimary = Color(0xFF006B5E)
val CruiseOnPrimary = Color(0xFFFFFFFF)
val CruisePrimaryContainer = Color(0xFF78F8E4)
val CruiseOnPrimaryContainer = Color(0xFF00201C)

val CruiseSecondary = Color(0xFF4B6360)
val CruiseOnSecondary = Color(0xFFFFFFFF)
val CruiseSecondaryContainer = Color(0xFFCDE8E4)
val CruiseOnSecondaryContainer = Color(0xFF051F1D)

val CruiseBackground = Color(0xFFFAFDFB)
val CruiseOnBackground = Color(0xFF191C1C)
val CruiseSurface = Color(0xFFFAFDFB)
val CruiseOnSurface = Color(0xFF191C1C)

// Used for metric color-coding in comparison table
val WeatherGood = Color(0xFF4CAF50)
val WeatherNeutral = Color(0xFFFFC107)
val WeatherCaution = Color(0xFFF44336)
