// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.theme

import android.app.Activity
import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.SideEffect
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalView
import androidx.core.view.WindowCompat

private val LightColorScheme = lightColorScheme(
    primary = CruisePrimary,
    onPrimary = CruiseOnPrimary,
    primaryContainer = CruisePrimaryContainer,
    onPrimaryContainer = CruiseOnPrimaryContainer,
    secondary = CruiseSecondary,
    onSecondary = CruiseOnSecondary,
    secondaryContainer = CruiseSecondaryContainer,
    onSecondaryContainer = CruiseOnSecondaryContainer,
    background = CruiseBackground,
    onBackground = CruiseOnBackground,
    surface = CruiseSurface,
    onSurface = CruiseOnSurface,
)

private val DarkColorScheme = darkColorScheme(
    primary = CruisePrimaryContainer,
    onPrimary = CruiseOnPrimaryContainer,
    primaryContainer = CruisePrimary,
    onPrimaryContainer = CruiseOnPrimary,
)

@Composable
fun CruiseWeatherTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    dynamicColor: Boolean = true,
    content: @Composable () -> Unit,
) {
    val colorScheme = when {
        dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
            val context = LocalContext.current
            if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
        }
        darkTheme -> DarkColorScheme
        else -> LightColorScheme
    }

    val view = LocalView.current
    if (!view.isInEditMode) {
        SideEffect {
            val activity = view.context as? Activity ?: return@SideEffect
            val window = activity.window
            WindowCompat.getInsetsController(window, view).isAppearanceLightStatusBars = !darkTheme
        }
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = Typography,
        content = content,
    )
}
