// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.navigation

import androidx.compose.runtime.Composable
import androidx.navigation.NavType
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import androidx.navigation.navArgument
import org.jewzaam.cruiseweather.ui.comparison.ComparisonScreen
import org.jewzaam.cruiseweather.ui.cruisedetail.CruiseDetailScreen
import org.jewzaam.cruiseweather.ui.cruiseedit.CruiseEditScreen
import org.jewzaam.cruiseweather.ui.cruiselist.CruiseListScreen

private const val CRUISE_LIST = "cruise_list"
private const val CRUISE_EDIT = "cruise_edit"
private const val CRUISE_DETAIL = "cruise_detail"
private const val COMPARISON = "comparison"
private const val ARG_CRUISE_ID = "cruiseId"

@Composable
fun NavGraph() {
    val navController = rememberNavController()
    NavHost(navController = navController, startDestination = CRUISE_LIST) {
        composable(CRUISE_LIST) {
            CruiseListScreen(
                onAddCruise = { navController.navigate(CRUISE_EDIT) },
                onCruiseClick = { cruiseId -> navController.navigate("$CRUISE_DETAIL/$cruiseId") },
                onCompareClick = { navController.navigate(COMPARISON) },
            )
        }
        composable(route = CRUISE_EDIT) {
            CruiseEditScreen(
                cruiseId = null,
                onNavigateUp = { navController.navigateUp() },
            )
        }
        composable(
            route = "$CRUISE_EDIT/{$ARG_CRUISE_ID}",
            arguments = listOf(navArgument(ARG_CRUISE_ID) { type = NavType.LongType }),
        ) { backStackEntry ->
            CruiseEditScreen(
                cruiseId = backStackEntry.arguments?.getLong(ARG_CRUISE_ID),
                onNavigateUp = { navController.navigateUp() },
            )
        }
        composable(
            route = "$CRUISE_DETAIL/{$ARG_CRUISE_ID}",
            arguments = listOf(navArgument(ARG_CRUISE_ID) { type = NavType.LongType }),
        ) { backStackEntry ->
            val cruiseId = backStackEntry.arguments?.getLong(ARG_CRUISE_ID) ?: return@composable
            CruiseDetailScreen(
                cruiseId = cruiseId,
                onNavigateUp = { navController.navigateUp() },
                onEditCruise = { navController.navigate("$CRUISE_EDIT/$cruiseId") },
            )
        }
        composable(COMPARISON) {
            ComparisonScreen(onNavigateUp = { navController.navigateUp() })
        }
    }
}
