// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather

import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherYear
import org.jewzaam.cruiseweather.data.remote.dto.DailyWeatherData
import org.jewzaam.cruiseweather.data.remote.dto.GeocodingResult
import org.jewzaam.cruiseweather.data.remote.dto.HistoricalWeatherResponse
import org.jewzaam.cruiseweather.domain.model.CruiseWithPorts
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import java.time.Instant
import java.time.LocalDate

fun cruise(
    id: Long = 0L,
    name: String = "Test Cruise",
    sailDate: LocalDate = LocalDate.of(2026, 12, 14),
    returnDate: LocalDate = LocalDate.of(2026, 12, 21),
    departurePortName: String = "Miami",
    returnPortName: String? = null,
    createdAt: Instant = Instant.parse("2026-01-01T00:00:00Z"),
    updatedAt: Instant = Instant.parse("2026-01-01T00:00:00Z"),
) = Cruise(
    id = id,
    name = name,
    sailDate = sailDate,
    returnDate = returnDate,
    departurePortName = departurePortName,
    returnPortName = returnPortName,
    createdAt = createdAt,
    updatedAt = updatedAt,
)

fun port(
    id: Long = 0L,
    cruiseId: Long = 1L,
    portName: String = "Cozumel",
    date: LocalDate = LocalDate.of(2026, 12, 16),
    type: PortType = PortType.PORT_OF_CALL,
    latitude: Double? = 20.43,
    longitude: Double? = -86.92,
    resolvedDisplayName: String? = null,
    sortOrder: Int = 0,
) = PortOfCall(
    id = id,
    cruiseId = cruiseId,
    portName = portName,
    date = date,
    type = type,
    latitude = latitude,
    longitude = longitude,
    resolvedDisplayName = resolvedDisplayName,
    sortOrder = sortOrder,
)

fun portWeatherYear(
    id: Long = 0L,
    portOfCallId: Long = 1L,
    year: Int = 2025,
    tempHighF: Double = 82.0,
    tempLowF: Double = 72.0,
    precipMm: Double = 2.5,
    precipHours: Double = 1.0,
    windMaxMph: Double = 12.0,
    windGustMph: Double = 18.0,
    humidityPct: Double = 75.0,
    uvIndexMax: Double = 9.0,
    sunshineDurationSec: Double = 25000.0,
) = PortWeatherYear(
    id = id,
    portOfCallId = portOfCallId,
    year = year,
    tempHighF = tempHighF,
    tempLowF = tempLowF,
    precipMm = precipMm,
    precipHours = precipHours,
    windMaxMph = windMaxMph,
    windGustMph = windGustMph,
    humidityPct = humidityPct,
    uvIndexMax = uvIndexMax,
    sunshineDurationSec = sunshineDurationSec,
)

fun portWeatherSummary(
    id: Long = 0L,
    portOfCallId: Long = 1L,
    dataSource: String = "historical_avg",
    yearsUsed: String = "2021,2022,2023,2024,2025",
    avgTempHighF: Double = 80.0,
    avgTempLowF: Double = 70.0,
    tempHighMin: Double = 78.0,
    tempHighMax: Double = 83.0,
    tempLowMin: Double = 68.0,
    tempLowMax: Double = 72.0,
    avgPrecipMm: Double = 1.0,
    avgPrecipHours: Double = 0.5,
    rainyYearCount: Int = 1,
    totalYearCount: Int = 5,
    avgWindMaxMph: Double = 12.0,
    avgWindGustMph: Double = 18.0,
    avgHumidityPct: Double = 75.0,
    avgUvIndexMax: Double = 9.0,
    avgSunshineMins: Double = 400.0,
    fetchedAt: Instant = Instant.parse("2026-01-01T00:00:00Z"),
) = PortWeatherSummary(
    id = id,
    portOfCallId = portOfCallId,
    dataSource = dataSource,
    yearsUsed = yearsUsed,
    avgTempHighF = avgTempHighF,
    avgTempLowF = avgTempLowF,
    tempHighMin = tempHighMin,
    tempHighMax = tempHighMax,
    tempLowMin = tempLowMin,
    tempLowMax = tempLowMax,
    avgPrecipMm = avgPrecipMm,
    avgPrecipHours = avgPrecipHours,
    rainyYearCount = rainyYearCount,
    totalYearCount = totalYearCount,
    avgWindMaxMph = avgWindMaxMph,
    avgWindGustMph = avgWindGustMph,
    avgHumidityPct = avgHumidityPct,
    avgUvIndexMax = avgUvIndexMax,
    avgSunshineMins = avgSunshineMins,
    fetchedAt = fetchedAt,
)

fun geocodingCandidate(
    id: Long = 1L,
    displayName: String = "Miami, Florida, United States",
    latitude: Double = 25.77,
    longitude: Double = -80.19,
) = GeocodingCandidate(
    id = id,
    displayName = displayName,
    latitude = latitude,
    longitude = longitude,
)

fun geocodingResult(
    id: Long = 1L,
    name: String = "Miami",
    latitude: Double = 25.77,
    longitude: Double = -80.19,
    country: String? = "United States",
    countryCode: String? = "US",
    admin1: String? = "Florida",
    admin2: String? = null,
    featureCode: String? = "PPL",
    population: Int? = 500000,
) = GeocodingResult(
    id = id,
    name = name,
    latitude = latitude,
    longitude = longitude,
    country = country,
    countryCode = countryCode,
    admin1 = admin1,
    admin2 = admin2,
    featureCode = featureCode,
    population = population,
)

fun cruiseWithPorts(
    cruise: Cruise = cruise(id = 1L),
    ports: List<PortOfCall> = listOf(
        port(id = 10L, cruiseId = 1L, portName = "Miami", type = PortType.DEPARTURE, date = LocalDate.of(2026, 12, 14)),
        port(id = 11L, cruiseId = 1L, portName = "Cozumel", date = LocalDate.of(2026, 12, 16)),
        port(id = 12L, cruiseId = 1L, portName = "Miami", type = PortType.RETURN, date = LocalDate.of(2026, 12, 21), sortOrder = Int.MAX_VALUE),
    ),
) = CruiseWithPorts(cruise = cruise, ports = ports)

fun dailyWeatherData(
    time: List<String> = listOf("2025-12-16"),
    tempMaxF: List<Double?> = listOf(82.0),
    tempMinF: List<Double?> = listOf(72.0),
    precipMm: List<Double?> = listOf(0.0),
    precipHours: List<Double?> = listOf(0.0),
    windMaxMph: List<Double?> = listOf(12.0),
    windGustMph: List<Double?> = listOf(18.0),
    humidityPct: List<Double?> = listOf(75.0),
    uvIndexMax: List<Double?> = listOf(9.0),
    sunshineDurationSec: List<Double?> = listOf(25000.0),
) = DailyWeatherData(
    time = time,
    tempMaxF = tempMaxF,
    tempMinF = tempMinF,
    precipMm = precipMm,
    precipHours = precipHours,
    windMaxMph = windMaxMph,
    windGustMph = windGustMph,
    humidityPct = humidityPct,
    uvIndexMax = uvIndexMax,
    sunshineDurationSec = sunshineDurationSec,
)

fun historicalWeatherResponse(
    latitude: Double = 20.43,
    longitude: Double = -86.92,
    daily: DailyWeatherData? = dailyWeatherData(),
    error: Boolean = false,
    reason: String? = null,
) = HistoricalWeatherResponse(
    latitude = latitude,
    longitude = longitude,
    daily = daily,
    error = error,
    reason = reason,
)
