// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.components

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.selection.selectable
import androidx.compose.material3.Card
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.unit.dp
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import kotlin.math.abs

/**
 * Shows geocoding candidate results for the user to confirm.
 * Displayed inline below the location text field.
 */
@Composable
fun GeocodingConfirmation(
    candidates: List<GeocodingCandidate>,
    selectedId: Long?,
    onCandidateSelected: (GeocodingCandidate) -> Unit,
    modifier: Modifier = Modifier,
) {
    if (candidates.isEmpty()) return

    Card(modifier = modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(vertical = 4.dp)) {
            Text(
                text = "Select location:",
                style = MaterialTheme.typography.labelMedium,
                modifier = Modifier.padding(horizontal = 16.dp, vertical = 4.dp),
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
            candidates.forEach { candidate ->
                val isSelected = candidate.id == selectedId
                CandidateRow(
                    candidate = candidate,
                    isSelected = isSelected,
                    onSelected = { onCandidateSelected(candidate) },
                )
            }
        }
    }
}

@Composable
private fun CandidateRow(
    candidate: GeocodingCandidate,
    isSelected: Boolean,
    onSelected: () -> Unit,
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .selectable(
                selected = isSelected,
                onClick = onSelected,
                role = Role.RadioButton,
            )
            .padding(horizontal = 16.dp, vertical = 4.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        RadioButton(
            selected = isSelected,
            onClick = null, // handled by Row selectable
        )
        val latDir = if (candidate.latitude >= 0) "N" else "S"
        val lonDir = if (candidate.longitude >= 0) "E" else "W"
        Column(modifier = Modifier.padding(start = 8.dp)) {
            Text(
                text = candidate.displayName,
                style = MaterialTheme.typography.bodyMedium,
            )
            Text(
                text = "%.4f° %s, %.4f° %s".format(
                    abs(candidate.latitude),
                    latDir,
                    abs(candidate.longitude),
                    lonDir,
                ),
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
    }
}
