// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.ui.components

import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary

// Thresholds for icon derivation. All based on summary averages.
private const val PRECIP_RAINY_MM = 5.0          // avg precip above this = rainy
private const val PRECIP_HOURS_RAINY = 3.0       // avg precip hours above this = rainy
private const val SUNSHINE_SUNNY_MINS = 360.0    // avg sunshine above this = sunny (6 hrs)
private const val WIND_HIGH_MPH = 20.0           // avg wind above this = windy

enum class WeatherCondition {
    SUNNY,
    PARTLY_CLOUDY,
    RAINY,
    WINDY,
    UNKNOWN,
}

/**
 * Derives a simple weather condition from a port weather summary.
 * Rules applied in priority order:
 * 1. Rainy: high precip + high precip hours
 * 2. Sunny: low precip + high sunshine
 * 3. Windy: high wind
 * 4. Partly cloudy: everything else
 */
fun deriveWeatherCondition(summary: PortWeatherSummary?): WeatherCondition {
    summary ?: return WeatherCondition.UNKNOWN
    return when {
        summary.avgPrecipMm >= PRECIP_RAINY_MM && summary.avgPrecipHours >= PRECIP_HOURS_RAINY ->
            WeatherCondition.RAINY
        summary.avgPrecipMm < PRECIP_RAINY_MM && summary.avgSunshineMins >= SUNSHINE_SUNNY_MINS ->
            WeatherCondition.SUNNY
        summary.avgWindMaxMph >= WIND_HIGH_MPH ->
            WeatherCondition.WINDY
        else ->
            WeatherCondition.PARTLY_CLOUDY
    }
}

fun WeatherCondition.toEmoji(): String = when (this) {
    WeatherCondition.SUNNY -> "\u2600\uFE0F"        // ☀️
    WeatherCondition.PARTLY_CLOUDY -> "\u26C5"      // ⛅
    WeatherCondition.RAINY -> "\uD83C\uDF27\uFE0F"  // 🌧️
    WeatherCondition.WINDY -> "\uD83D\uDCA8"        // 💨
    WeatherCondition.UNKNOWN -> "—"
}
