// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.jewzaam.cruiseweather.cruise
import org.jewzaam.cruiseweather.cruiseWithPorts
import org.jewzaam.cruiseweather.data.local.cruiseports.CruisePort
import org.jewzaam.cruiseweather.data.local.cruiseports.CruisePortMatcher
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.usecase.GeocodePortUseCase
import org.jewzaam.cruiseweather.geocodingCandidate
import org.jewzaam.cruiseweather.port
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.time.LocalDate

@OptIn(ExperimentalCoroutinesApi::class)
class CruiseEditViewModelTest {

    private val cruiseRepository = mockk<CruiseRepository>(relaxed = true)
    private val weatherRepository = mockk<WeatherRepository>(relaxed = true)
    private val geocodePortUseCase = mockk<GeocodePortUseCase>()
    private val cruisePortMatcher = mockk<CruisePortMatcher>()
    private val testDispatcher = StandardTestDispatcher()
    private lateinit var viewModel: CruiseEditViewModel

    @Before
    fun setUp() {
        Dispatchers.setMain(testDispatcher)
        every { cruisePortMatcher.search(any(), any()) } returns emptyList()
        viewModel = CruiseEditViewModel(
            cruiseRepository = cruiseRepository,
            weatherRepository = weatherRepository,
            geocodePortUseCase = geocodePortUseCase,
            cruisePortMatcher = cruisePortMatcher,
        )
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    // --- Initial State ---

    @Test
    fun `initial state has empty name and default dates`() {
        val state = viewModel.uiState.value
        assertThat(state.name).isEmpty()
        assertThat(state.cruiseId).isEqualTo(0L)
        assertThat(state.isSaved).isFalse()
        assertThat(state.isLoading).isFalse()
        assertThat(state.error).isNull()
    }

    // --- Field Updates ---

    @Test
    fun `onNameChange updates name in state`() {
        viewModel.onNameChange("Caribbean Dream")
        assertThat(viewModel.uiState.value.name).isEqualTo("Caribbean Dream")
    }

    @Test
    fun `onSailDateChange updates sailDate in state`() {
        val date = LocalDate.of(2027, 1, 15)
        viewModel.onSailDateChange(date)
        assertThat(viewModel.uiState.value.sailDate).isEqualTo(date)
    }

    @Test
    fun `onSailDateChange shifts returnDate and port dates by same offset`() {
        val sailDate = LocalDate.of(2026, 12, 14)
        val returnDate = LocalDate.of(2026, 12, 21)
        viewModel.onSailDateChange(sailDate)
        viewModel.onReturnDateChange(returnDate)
        viewModel.onDepartureChanged("Miami", geocodingCandidate())

        val seaDay = port(portName = "At Sea", date = LocalDate.of(2026, 12, 15),
            type = PortType.SEA_DAY, latitude = null, longitude = null)
        val portDay = port(portName = "Cozumel", date = LocalDate.of(2026, 12, 16))
        viewModel.addPortOfCall(seaDay)
        viewModel.addPortOfCall(portDay)

        // Move sail date forward by 5 days
        viewModel.onSailDateChange(LocalDate.of(2026, 12, 19))
        val state = viewModel.uiState.value

        assertThat(state.sailDate).isEqualTo(LocalDate.of(2026, 12, 19))
        assertThat(state.returnDate).isEqualTo(LocalDate.of(2026, 12, 26))
        assertThat(state.portsOfCall[0].date).isEqualTo(LocalDate.of(2026, 12, 20))
        assertThat(state.portsOfCall[1].date).isEqualTo(LocalDate.of(2026, 12, 21))
    }

    @Test
    fun `onReturnDateChange updates returnDate in state`() {
        val date = LocalDate.of(2027, 1, 22)
        viewModel.onReturnDateChange(date)
        assertThat(viewModel.uiState.value.returnDate).isEqualTo(date)
    }

    @Test
    fun `onDateRangeChange updates both dates`() {
        val sail = LocalDate.of(2027, 1, 15)
        val ret = LocalDate.of(2027, 1, 22)
        viewModel.onDateRangeChange(sail, ret)
        val state = viewModel.uiState.value
        assertThat(state.sailDate).isEqualTo(sail)
        assertThat(state.returnDate).isEqualTo(ret)
    }

    @Test
    fun `onHasDifferentReturnPortChange clears return port state`() {
        viewModel.onHasDifferentReturnPortChange(true)
        val state = viewModel.uiState.value
        assertThat(state.hasDifferentReturnPort).isTrue()
        assertThat(state.returnPortName).isEmpty()
        assertThat(state.selectedReturn).isNull()
    }

    // --- Departure/Return Selection ---

    @Test
    fun `onDepartureChanged sets selected and display name`() {
        val candidate = geocodingCandidate()
        viewModel.onDepartureChanged("Miami, Florida, United States", candidate)
        val state = viewModel.uiState.value
        assertThat(state.selectedDeparture).isEqualTo(candidate)
        assertThat(state.departurePortName).isEqualTo("Miami, Florida, United States")
    }

    @Test
    fun `onDepartureChanged clears selection when candidate is null`() {
        viewModel.onDepartureChanged("Mia", null)
        val state = viewModel.uiState.value
        assertThat(state.selectedDeparture).isNull()
        assertThat(state.departurePortName).isEqualTo("Mia")
    }

    @Test
    fun `onReturnChanged sets selected and display name`() {
        val candidate = geocodingCandidate(displayName = "Barcelona, Spain")
        viewModel.onReturnChanged("Barcelona, Spain", candidate)
        val state = viewModel.uiState.value
        assertThat(state.selectedReturn).isEqualTo(candidate)
        assertThat(state.returnPortName).isEqualTo("Barcelona, Spain")
    }

    // --- Validation ---

    @Test
    fun `saveCruise rejects blank name`() = runTest {
        viewModel.onNameChange("   ")
        viewModel.onDepartureChanged("Miami", geocodingCandidate())
        viewModel.saveCruise()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Cruise name is required")
        assertThat(viewModel.uiState.value.isSaved).isFalse()
    }

    @Test
    fun `saveCruise rejects missing itinerary`() = runTest {
        viewModel.onNameChange("Test")
        viewModel.saveCruise()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Build an itinerary first")
    }

    // --- Save ---

    @Test
    fun `saveCruise creates cruise with departure and return ports`() = runTest {
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 5L

        viewModel.onNameChange("Caribbean")
        viewModel.onDepartureChanged("Miami", geocodingCandidate())
        viewModel.onSailDateChange(LocalDate.of(2026, 12, 14))
        viewModel.onReturnDateChange(LocalDate.of(2026, 12, 21))
        viewModel.saveCruise()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.isSaved).isTrue()
        assertThat(viewModel.uiState.value.savedCruiseId).isEqualTo(5L)
        coVerify {
            cruiseRepository.saveCruise(
                match { it.name == "Caribbean" && it.returnPortName == null },
                match { ports -> ports.size == 2 && ports[0].type == PortType.DEPARTURE && ports[1].type == PortType.RETURN },
                any(),
                any(),
            )
        }
    }

    @Test
    fun `saveCruise with different return port sets returnPortName`() = runTest {
        val returnCandidate = geocodingCandidate(id = 2, displayName = "Fort Lauderdale")
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 5L

        viewModel.onNameChange("Caribbean")
        viewModel.onDepartureChanged("Miami", geocodingCandidate())
        viewModel.onHasDifferentReturnPortChange(true)
        viewModel.onReturnChanged("Fort Lauderdale", returnCandidate)
        viewModel.saveCruise()
        advanceUntilIdle()

        coVerify {
            cruiseRepository.saveCruise(
                match { it.returnPortName == "Fort Lauderdale" },
                any(),
                any(),
                any(),
            )
        }
    }

    @Test
    fun `saveCruise sets error on exception`() = runTest {
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } throws RuntimeException("DB error")

        viewModel.onNameChange("Test")
        viewModel.onDepartureChanged("Miami", geocodingCandidate())
        viewModel.saveCruise()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("DB error")
        assertThat(viewModel.uiState.value.isSaved).isFalse()
    }

    // --- Port Staging ---

    @Test
    fun `addPortOfCall appends to local list`() {
        val p = port(portName = "Cozumel")
        viewModel.addPortOfCall(p)
        assertThat(viewModel.uiState.value.portsOfCall).containsExactly(p)
    }

    @Test
    fun `updatePortOfCall replaces matching port`() {
        val p = port(id = 10, portName = "Cozumel")
        viewModel.addPortOfCall(p)
        val updated = p.copy(portName = "Updated Cozumel")
        viewModel.updatePortOfCall(updated)
        assertThat(viewModel.uiState.value.portsOfCall).containsExactly(updated)
    }

    @Test
    fun `deletePortOfCall removes matching port`() {
        val p = port(id = 10, portName = "Cozumel")
        viewModel.addPortOfCall(p)
        viewModel.deletePortOfCall(p)
        assertThat(viewModel.uiState.value.portsOfCall).isEmpty()
    }

    // --- Save Diffing ---

    @Test
    fun `saveCruise passes deleted port ids and new ports to repository`() = runTest {
        // Simulate loading a cruise with existing ports
        val existingPort = port(id = 100, cruiseId = 1, portName = "Jamaica")
        val cwp = cruiseWithPorts(
            cruise = cruise(id = 1, name = "Test"),
            ports = listOf(
                port(id = 10, cruiseId = 1, portName = "Miami", type = PortType.DEPARTURE, date = LocalDate.of(2026, 12, 14)),
                existingPort,
                port(id = 12, cruiseId = 1, portName = "Miami", type = PortType.RETURN, date = LocalDate.of(2026, 12, 21), sortOrder = Int.MAX_VALUE),
            ),
        )
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 1L

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        // Remove existing port and add a new one
        viewModel.deletePortOfCall(existingPort)
        val newPort = port(id = 0, cruiseId = 1, portName = "Grand Cayman")
        viewModel.addPortOfCall(newPort)
        viewModel.saveCruise()
        advanceUntilIdle()

        coVerify {
            cruiseRepository.saveCruise(
                any(),
                any(),
                match { ports -> ports.size == 1 && ports[0].portName == "Grand Cayman" },
                match { ids -> ids == setOf(100L) },
            )
        }
    }

    // --- Load ---

    @Test
    fun `loadCruise populates state from repository`() = runTest {
        val cwp = cruiseWithPorts(
            cruise = cruise(id = 1, name = "Caribbean", departurePortName = "Miami"),
            ports = listOf(
                port(
                    id = 10, cruiseId = 1, portName = "Miami", type = PortType.DEPARTURE,
                    latitude = 25.77, longitude = -80.19, resolvedDisplayName = "Miami, FL, US",
                    date = LocalDate.of(2026, 12, 14),
                ),
                port(id = 11, cruiseId = 1, portName = "Cozumel", type = PortType.PORT_OF_CALL, date = LocalDate.of(2026, 12, 16)),
                port(
                    id = 12, cruiseId = 1, portName = "Miami", type = PortType.RETURN,
                    latitude = 25.77, longitude = -80.19, resolvedDisplayName = "Miami, FL, US",
                    date = LocalDate.of(2026, 12, 21), sortOrder = Int.MAX_VALUE,
                ),
            ),
        )
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertThat(state.cruiseId).isEqualTo(1L)
        assertThat(state.name).isEqualTo("Caribbean")
        assertThat(state.departurePortName).isEqualTo("Miami, FL, US")
        assertThat(state.selectedDeparture).isNotNull()
        assertThat(state.portsOfCall).hasSize(1)
        assertThat(state.portsOfCall[0].portName).isEqualTo("Cozumel")
    }

    @Test
    fun `loadCruise handles null cruise`() = runTest {
        every { cruiseRepository.getCruiseWithPorts(999L) } returns flowOf(null)

        viewModel.loadCruise(999L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.isLoading).isFalse()
        assertThat(viewModel.uiState.value.cruiseId).isEqualTo(0L)
    }

    // --- Error ---

    @Test
    fun `clearError clears error state`() {
        viewModel.onNameChange("") // trigger empty state
        viewModel.saveCruise() // sets error
        viewModel.clearError()
        assertThat(viewModel.uiState.value.error).isNull()
    }

    // --- saveItinerary ---

    @Test
    fun `saveItinerary sets returnDate to last slot date`() {
        val sailDate = LocalDate.of(2026, 12, 14)
        viewModel.onSailDateChange(sailDate)
        viewModel.onDepartureChanged("Miami", geocodingCandidate())

        val slots = listOf(
            ItinerarySlot(dayNumber = 1, date = sailDate, portQuery = "Miami",
                resolvedPort = CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())),
            ItinerarySlot(dayNumber = 2, date = sailDate.plusDays(1)),
            ItinerarySlot(dayNumber = 3, date = sailDate.plusDays(2)),
            ItinerarySlot(dayNumber = 4, date = sailDate.plusDays(3), portQuery = ""),
        )
        viewModel.saveItinerary(slots)

        // 4 slots: Day 1 = Dec 14, Day 4 = Dec 17. returnDate should be Dec 17.
        assertThat(viewModel.uiState.value.returnDate).isEqualTo(LocalDate.of(2026, 12, 17))
    }

    @Test
    fun `saveItinerary creates SEA_DAY ports for blank intermediate slots`() {
        val sailDate = LocalDate.of(2026, 12, 14)
        viewModel.onSailDateChange(sailDate)
        viewModel.onDepartureChanged("Miami", geocodingCandidate())

        val slots = listOf(
            ItinerarySlot(dayNumber = 1, date = sailDate, portQuery = "Miami",
                resolvedPort = CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())),
            ItinerarySlot(dayNumber = 2, date = sailDate.plusDays(1)), // blank = sea day
            ItinerarySlot(dayNumber = 3, date = sailDate.plusDays(2), portQuery = "Cozumel",
                resolvedPort = CruisePort("coz", "Cozumel", 20.43, -86.92, "", emptyList())),
            ItinerarySlot(dayNumber = 4, date = sailDate.plusDays(3), portQuery = ""),
        )
        viewModel.saveItinerary(slots)

        val ports = viewModel.uiState.value.portsOfCall
        val seaDays = ports.filter { it.type == PortType.SEA_DAY }
        assertThat(seaDays).hasSize(1)
        assertThat(seaDays[0].portName).isEqualTo("At Sea")
        assertThat(seaDays[0].date).isEqualTo(sailDate.plusDays(1))
    }

    @Test
    fun `saveItinerary preserves PORT_OF_CALL for resolved slots`() {
        val sailDate = LocalDate.of(2026, 12, 14)
        viewModel.onSailDateChange(sailDate)
        viewModel.onDepartureChanged("Miami", geocodingCandidate())

        val slots = listOf(
            ItinerarySlot(dayNumber = 1, date = sailDate, portQuery = "Miami",
                resolvedPort = CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())),
            ItinerarySlot(dayNumber = 2, date = sailDate.plusDays(1), portQuery = "Cozumel",
                resolvedPort = CruisePort("coz", "Cozumel", 20.43, -86.92, "", emptyList())),
            ItinerarySlot(dayNumber = 3, date = sailDate.plusDays(2), portQuery = ""),
        )
        viewModel.saveItinerary(slots)

        val portOfCalls = viewModel.uiState.value.portsOfCall.filter { it.type == PortType.PORT_OF_CALL }
        assertThat(portOfCalls).hasSize(1)
        assertThat(portOfCalls[0].portName).isEqualTo("Cozumel")
        assertThat(portOfCalls[0].latitude).isEqualTo(20.43)
        assertThat(portOfCalls[0].longitude).isEqualTo(-86.92)
    }

    @Test
    fun `portsOfCall includes both sea days and ports after saveItinerary`() {
        val sailDate = LocalDate.of(2026, 12, 14)
        viewModel.onSailDateChange(sailDate)
        viewModel.onDepartureChanged("Miami", geocodingCandidate())

        val slots = listOf(
            ItinerarySlot(dayNumber = 1, date = sailDate, portQuery = "Miami",
                resolvedPort = CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())),
            ItinerarySlot(dayNumber = 2, date = sailDate.plusDays(1)), // sea day
            ItinerarySlot(dayNumber = 3, date = sailDate.plusDays(2), portQuery = "Cozumel",
                resolvedPort = CruisePort("coz", "Cozumel", 20.43, -86.92, "", emptyList())),
            ItinerarySlot(dayNumber = 4, date = sailDate.plusDays(3), portQuery = ""),
        )
        viewModel.saveItinerary(slots)

        val ports = viewModel.uiState.value.portsOfCall
        assertThat(ports).hasSize(2)
        val types = ports.map { it.type }.toSet()
        assertThat(types).containsExactly(PortType.SEA_DAY, PortType.PORT_OF_CALL)
    }

    // --- addPortOfCall replaces SEA_DAY ---

    @Test
    fun `addPortOfCall replaces sea day on same date and transfers notes`() {
        val date = LocalDate.of(2026, 12, 15)
        val seaDay = port(portName = "At Sea", date = date, type = PortType.SEA_DAY,
            latitude = null, longitude = null, notes = "Rest day")
        viewModel.addPortOfCall(seaDay)

        val newPort = port(portName = "Cozumel", date = date, type = PortType.PORT_OF_CALL)
        viewModel.addPortOfCall(newPort)

        val ports = viewModel.uiState.value.portsOfCall
        assertThat(ports).hasSize(1)
        assertThat(ports[0].type).isEqualTo(PortType.PORT_OF_CALL)
        assertThat(ports[0].portName).isEqualTo("Cozumel")
        assertThat(ports[0].notes).isEqualTo("Rest day")
    }

    // --- geocodeQuery ---

    @Test
    fun `geocodeQuery returns candidates from use case`() = runTest {
        val candidates = listOf(geocodingCandidate())
        coEvery { geocodePortUseCase(query = "Miami") } returns Result.success(candidates)

        val result = viewModel.geocodeQuery("Miami")

        assertThat(result).isEqualTo(candidates)
    }

    @Test
    fun `geocodeQuery returns empty list on failure`() = runTest {
        coEvery { geocodePortUseCase(query = "fail") } returns Result.failure(RuntimeException("error"))

        val result = viewModel.geocodeQuery("fail")

        assertThat(result).isEmpty()
    }
}
