// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceTimeBy
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.jewzaam.cruiseweather.cruise
import org.jewzaam.cruiseweather.cruiseWithPorts
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.domain.model.GeocodingCandidate
import org.jewzaam.cruiseweather.domain.usecase.GeocodePortUseCase
import org.jewzaam.cruiseweather.geocodingCandidate
import org.jewzaam.cruiseweather.port
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.time.LocalDate

@OptIn(ExperimentalCoroutinesApi::class)
class CruiseEditViewModelTest {

    private val cruiseRepository = mockk<CruiseRepository>(relaxed = true)
    private val geocodePortUseCase = mockk<GeocodePortUseCase>()
    private val testDispatcher = StandardTestDispatcher()
    private lateinit var viewModel: CruiseEditViewModel

    @Before
    fun setUp() {
        Dispatchers.setMain(testDispatcher)
        viewModel = CruiseEditViewModel(
            cruiseRepository = cruiseRepository,
            geocodePortUseCase = geocodePortUseCase,
        )
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    // --- Initial State ---

    @Test
    fun `initial state has empty name and default dates`() {
        val state = viewModel.uiState.value
        assertThat(state.name).isEmpty()
        assertThat(state.cruiseId).isEqualTo(0L)
        assertThat(state.isSaved).isFalse()
        assertThat(state.isLoading).isFalse()
        assertThat(state.error).isNull()
    }

    // --- Field Updates ---

    @Test
    fun `onNameChange updates name in state`() {
        viewModel.onNameChange("Caribbean Dream")
        assertThat(viewModel.uiState.value.name).isEqualTo("Caribbean Dream")
    }

    @Test
    fun `onSailDateChange updates sailDate in state`() {
        val date = LocalDate.of(2027, 1, 15)
        viewModel.onSailDateChange(date)
        assertThat(viewModel.uiState.value.sailDate).isEqualTo(date)
    }

    @Test
    fun `onReturnDateChange updates returnDate in state`() {
        val date = LocalDate.of(2027, 1, 22)
        viewModel.onReturnDateChange(date)
        assertThat(viewModel.uiState.value.returnDate).isEqualTo(date)
    }

    @Test
    fun `onHasDifferentReturnPortChange clears return port state`() {
        viewModel.onHasDifferentReturnPortChange(true)
        val state = viewModel.uiState.value
        assertThat(state.hasDifferentReturnPort).isTrue()
        assertThat(state.returnPortName).isEmpty()
        assertThat(state.selectedReturn).isNull()
    }

    // --- Departure Geocoding ---

    @Test
    fun `onDeparturePortNameChange clears candidates and selected`() {
        viewModel.onDeparturePortNameChange("Mi")
        val state = viewModel.uiState.value
        assertThat(state.departurePortName).isEqualTo("Mi")
        assertThat(state.departureCandidates).isEmpty()
        assertThat(state.selectedDeparture).isNull()
    }

    @Test
    fun `onDeparturePortNameChange triggers geocoding after debounce`() = runTest {
        val candidate = geocodingCandidate()
        coEvery { geocodePortUseCase(query = "Miami") } returns Result.success(listOf(candidate))

        viewModel.onDeparturePortNameChange("Miami")
        advanceTimeBy(800)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        // Single result auto-selects
        assertThat(state.selectedDeparture).isEqualTo(candidate)
        assertThat(state.departurePortName).isEqualTo(candidate.displayName)
    }

    @Test
    fun `onDeparturePortNameChange cancels previous geocode on rapid typing`() = runTest {
        coEvery { geocodePortUseCase(query = "Mia") } returns Result.success(
            listOf(geocodingCandidate(displayName = "Mia result")),
        )
        coEvery { geocodePortUseCase(query = "Miami") } returns Result.success(
            listOf(geocodingCandidate(displayName = "Miami result")),
        )

        viewModel.onDeparturePortNameChange("Mia")
        advanceTimeBy(400) // Not yet debounced
        viewModel.onDeparturePortNameChange("Miami")
        advanceTimeBy(800)
        advanceUntilIdle()

        // Only "Miami" should have been geocoded (auto-selected since single result)
        assertThat(viewModel.uiState.value.departurePortName).isEqualTo("Miami result")
    }

    @Test
    fun `departure geocoding auto-selects single candidate via debounce`() = runTest {
        val candidate = geocodingCandidate()
        coEvery { geocodePortUseCase(query = "Miami") } returns Result.success(listOf(candidate))

        viewModel.onDeparturePortNameChange("Miami")
        advanceTimeBy(800)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.selectedDeparture).isEqualTo(candidate)
    }

    @Test
    fun `departure geocoding shows multiple candidates without auto-selecting`() = runTest {
        val candidates = listOf(
            geocodingCandidate(id = 1, displayName = "Miami, FL, US"),
            geocodingCandidate(id = 2, displayName = "Miami Beach, FL, US"),
        )
        coEvery { geocodePortUseCase(query = "Miami") } returns Result.success(candidates)

        viewModel.onDeparturePortNameChange("Miami")
        advanceTimeBy(800)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertThat(state.departureCandidates).hasSize(2)
        assertThat(state.selectedDeparture).isNull()
    }

    @Test
    fun `departure geocoding sets error on failure`() = runTest {
        coEvery { geocodePortUseCase(query = "fail") } returns Result.failure(RuntimeException("Network error"))

        viewModel.onDeparturePortNameChange("fail")
        advanceTimeBy(800)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Network error")
    }

    @Test
    fun `departure geocoding skipped when port name is blank`() = runTest {
        viewModel.onDeparturePortNameChange("")
        advanceTimeBy(800)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.isGeocodingDeparture).isFalse()
    }

    // --- Return Port Geocoding ---

    @Test
    fun `onReturnPortNameChange triggers geocoding after debounce`() = runTest {
        val candidate = geocodingCandidate(displayName = "Barcelona, Spain")
        coEvery { geocodePortUseCase(query = "Barcelona") } returns Result.success(listOf(candidate))

        viewModel.onReturnPortNameChange("Barcelona")
        advanceTimeBy(800)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.selectedReturn).isEqualTo(candidate)
    }

    @Test
    fun `return geocoding sets error on failure`() = runTest {
        coEvery { geocodePortUseCase(query = "fail") } returns Result.failure(RuntimeException("error"))

        viewModel.onReturnPortNameChange("fail")
        advanceTimeBy(800)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("error")
    }

    // --- Candidate Selection ---

    @Test
    fun `onDepartureCandidateSelected sets selected and clears candidates`() {
        val candidate = geocodingCandidate()
        viewModel.onDepartureCandidateSelected(candidate)
        val state = viewModel.uiState.value
        assertThat(state.selectedDeparture).isEqualTo(candidate)
        assertThat(state.departureCandidates).isEmpty()
        assertThat(state.departurePortName).isEqualTo(candidate.displayName)
    }

    @Test
    fun `onReturnCandidateSelected sets selected and clears candidates`() {
        val candidate = geocodingCandidate(displayName = "Barcelona")
        viewModel.onReturnCandidateSelected(candidate)
        val state = viewModel.uiState.value
        assertThat(state.selectedReturn).isEqualTo(candidate)
        assertThat(state.returnCandidates).isEmpty()
        assertThat(state.returnPortName).isEqualTo("Barcelona")
    }

    // --- Validation ---

    @Test
    fun `saveCruise rejects blank name`() = runTest {
        viewModel.onNameChange("   ")
        viewModel.onDepartureCandidateSelected(geocodingCandidate())
        viewModel.saveCruise()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Cruise name is required")
        assertThat(viewModel.uiState.value.isSaved).isFalse()
    }

    @Test
    fun `saveCruise rejects missing departure geocode`() = runTest {
        viewModel.onNameChange("Test")
        viewModel.saveCruise()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Departure port must be geocoded")
    }

    @Test
    fun `saveCruise rejects return date before sail date`() = runTest {
        viewModel.onNameChange("Test")
        viewModel.onDepartureCandidateSelected(geocodingCandidate())
        viewModel.onSailDateChange(LocalDate.of(2027, 1, 20))
        viewModel.onReturnDateChange(LocalDate.of(2027, 1, 15))
        viewModel.saveCruise()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Return date must be on or after sail date")
    }

    // --- Save ---

    @Test
    fun `saveCruise creates cruise with departure and return ports`() = runTest {
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 5L

        viewModel.onNameChange("Caribbean")
        viewModel.onDepartureCandidateSelected(geocodingCandidate())
        viewModel.onSailDateChange(LocalDate.of(2026, 12, 14))
        viewModel.onReturnDateChange(LocalDate.of(2026, 12, 21))
        viewModel.saveCruise()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.isSaved).isTrue()
        coVerify {
            cruiseRepository.saveCruise(
                match { it.name == "Caribbean" && it.returnPortName == null },
                match { ports -> ports.size == 2 && ports[0].type == PortType.DEPARTURE && ports[1].type == PortType.RETURN },
                any(),
                any(),
            )
        }
    }

    @Test
    fun `saveCruise with different return port sets returnPortName`() = runTest {
        val returnCandidate = geocodingCandidate(id = 2, displayName = "Fort Lauderdale")
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 5L

        viewModel.onNameChange("Caribbean")
        viewModel.onDepartureCandidateSelected(geocodingCandidate())
        viewModel.onHasDifferentReturnPortChange(true)
        viewModel.onReturnCandidateSelected(returnCandidate)
        viewModel.saveCruise()
        advanceUntilIdle()

        coVerify {
            cruiseRepository.saveCruise(
                match { it.returnPortName == "Fort Lauderdale" },
                any(),
                any(),
                any(),
            )
        }
    }

    @Test
    fun `saveCruise sets error on exception`() = runTest {
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } throws RuntimeException("DB error")

        viewModel.onNameChange("Test")
        viewModel.onDepartureCandidateSelected(geocodingCandidate())
        viewModel.saveCruise()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("DB error")
        assertThat(viewModel.uiState.value.isSaved).isFalse()
    }

    // --- Port Staging ---

    @Test
    fun `addPortOfCall appends to local list`() {
        val p = port(portName = "Cozumel")
        viewModel.addPortOfCall(p)
        assertThat(viewModel.uiState.value.portsOfCall).containsExactly(p)
    }

    @Test
    fun `updatePortOfCall replaces matching port`() {
        val p = port(id = 10, portName = "Cozumel")
        viewModel.addPortOfCall(p)
        val updated = p.copy(portName = "Updated Cozumel")
        viewModel.updatePortOfCall(updated)
        assertThat(viewModel.uiState.value.portsOfCall).containsExactly(updated)
    }

    @Test
    fun `deletePortOfCall removes matching port`() {
        val p = port(id = 10, portName = "Cozumel")
        viewModel.addPortOfCall(p)
        viewModel.deletePortOfCall(p)
        assertThat(viewModel.uiState.value.portsOfCall).isEmpty()
    }

    // --- Save Diffing ---

    @Test
    fun `saveCruise passes deleted port ids and new ports to repository`() = runTest {
        // Simulate loading a cruise with existing ports
        val existingPort = port(id = 100, cruiseId = 1, portName = "Jamaica")
        val cwp = cruiseWithPorts(
            cruise = cruise(id = 1, name = "Test"),
            ports = listOf(
                port(id = 10, cruiseId = 1, portName = "Miami", type = PortType.DEPARTURE, date = LocalDate.of(2026, 12, 14)),
                existingPort,
                port(id = 12, cruiseId = 1, portName = "Miami", type = PortType.RETURN, date = LocalDate.of(2026, 12, 21), sortOrder = Int.MAX_VALUE),
            ),
        )
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 1L

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        // Remove existing port and add a new one
        viewModel.deletePortOfCall(existingPort)
        val newPort = port(id = 0, cruiseId = 1, portName = "Grand Cayman")
        viewModel.addPortOfCall(newPort)
        viewModel.saveCruise()
        advanceUntilIdle()

        coVerify {
            cruiseRepository.saveCruise(
                any(),
                any(),
                match { ports -> ports.size == 1 && ports[0].portName == "Grand Cayman" },
                match { ids -> ids == setOf(100L) },
            )
        }
    }

    // --- Load ---

    @Test
    fun `loadCruise populates state from repository`() = runTest {
        val cwp = cruiseWithPorts(
            cruise = cruise(id = 1, name = "Caribbean", departurePortName = "Miami"),
            ports = listOf(
                port(
                    id = 10, cruiseId = 1, portName = "Miami", type = PortType.DEPARTURE,
                    latitude = 25.77, longitude = -80.19, resolvedDisplayName = "Miami, FL, US",
                    date = LocalDate.of(2026, 12, 14),
                ),
                port(id = 11, cruiseId = 1, portName = "Cozumel", type = PortType.PORT_OF_CALL, date = LocalDate.of(2026, 12, 16)),
                port(
                    id = 12, cruiseId = 1, portName = "Miami", type = PortType.RETURN,
                    latitude = 25.77, longitude = -80.19, resolvedDisplayName = "Miami, FL, US",
                    date = LocalDate.of(2026, 12, 21), sortOrder = Int.MAX_VALUE,
                ),
            ),
        )
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertThat(state.cruiseId).isEqualTo(1L)
        assertThat(state.name).isEqualTo("Caribbean")
        assertThat(state.departurePortName).isEqualTo("Miami, FL, US")
        assertThat(state.selectedDeparture).isNotNull()
        assertThat(state.portsOfCall).hasSize(1)
        assertThat(state.portsOfCall[0].portName).isEqualTo("Cozumel")
    }

    @Test
    fun `loadCruise handles null cruise`() = runTest {
        every { cruiseRepository.getCruiseWithPorts(999L) } returns flowOf(null)

        viewModel.loadCruise(999L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.isLoading).isFalse()
        assertThat(viewModel.uiState.value.cruiseId).isEqualTo(0L)
    }

    // --- Error ---

    @Test
    fun `clearError clears error state`() {
        viewModel.onNameChange("") // trigger empty state
        viewModel.saveCruise() // sets error
        viewModel.clearError()
        assertThat(viewModel.uiState.value.error).isNull()
    }

    // --- geocodeQuery ---

    @Test
    fun `geocodeQuery returns candidates from use case`() = runTest {
        val candidates = listOf(geocodingCandidate())
        coEvery { geocodePortUseCase(query = "Miami") } returns Result.success(candidates)

        val result = viewModel.geocodeQuery("Miami")

        assertThat(result).isEqualTo(candidates)
    }

    @Test
    fun `geocodeQuery returns empty list on failure`() = runTest {
        coEvery { geocodePortUseCase(query = "fail") } returns Result.failure(RuntimeException("error"))

        val result = viewModel.geocodeQuery("fail")

        assertThat(result).isEmpty()
    }
}
