// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.ui.cruiseedit

import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.jewzaam.cruiseweather.cruise
import org.jewzaam.cruiseweather.cruiseWithPorts
import org.jewzaam.cruiseweather.data.local.cruiseports.CruisePort
import org.jewzaam.cruiseweather.data.local.cruiseports.CruisePortMatcher
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.port
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.time.LocalDate

@OptIn(ExperimentalCoroutinesApi::class)
class CruiseEditViewModelTest {

    private val cruiseRepository = mockk<CruiseRepository>(relaxed = true)
    private val weatherRepository = mockk<WeatherRepository>(relaxed = true)
    private val cruisePortMatcher = mockk<CruisePortMatcher>()
    private val testDispatcher = StandardTestDispatcher()
    private lateinit var viewModel: CruiseEditViewModel

    @Before
    fun setUp() {
        Dispatchers.setMain(testDispatcher)
        every { cruisePortMatcher.search(any(), any()) } returns emptyList()
        viewModel = CruiseEditViewModel(
            cruiseRepository = cruiseRepository,
            weatherRepository = weatherRepository,
            cruisePortMatcher = cruisePortMatcher,
        )
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    // --- Initial State ---

    @Test
    fun `initial state has empty name and default dates`() {
        val state = viewModel.uiState.value
        assertThat(state.name).isEmpty()
        assertThat(state.cruiseId).isEqualTo(0L)
        assertThat(state.isSaved).isFalse()
        assertThat(state.isLoading).isFalse()
        assertThat(state.error).isNull()
    }

    // --- Field Updates ---

    @Test
    fun `onNameChange updates name in state`() {
        viewModel.onNameChange("Caribbean Dream")
        assertThat(viewModel.uiState.value.name).isEqualTo("Caribbean Dream")
    }

    @Test
    fun `onSailDateChange updates sailDate in state`() {
        val date = LocalDate.of(2027, 1, 15)
        viewModel.onSailDateChange(date)
        assertThat(viewModel.uiState.value.sailDate).isEqualTo(date)
    }

    // --- Load ---

    @Test
    fun `loadCruise populates state and slots from repository`() = runTest {
        val cwp = cruiseWithPorts(
            cruise = cruise(id = 1, name = "Caribbean", departurePortName = "Miami"),
            ports = listOf(
                port(id = 10, cruiseId = 1, portName = "Miami", type = PortType.DEPARTURE,
                    latitude = 25.77, longitude = -80.19, resolvedDisplayName = "Miami, FL, US",
                    date = LocalDate.of(2026, 12, 14)),
                port(id = 11, cruiseId = 1, portName = "Cozumel", type = PortType.PORT_OF_CALL,
                    date = LocalDate.of(2026, 12, 16)),
                port(id = 12, cruiseId = 1, portName = "Miami", type = PortType.RETURN,
                    latitude = 25.77, longitude = -80.19, resolvedDisplayName = "Miami, FL, US",
                    date = LocalDate.of(2026, 12, 21), sortOrder = Int.MAX_VALUE),
            ),
        )
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        val state = viewModel.uiState.value
        assertThat(state.cruiseId).isEqualTo(1L)
        assertThat(state.name).isEqualTo("Caribbean")

        val slots = viewModel.uiState.value.loadedSlots
        assertThat(slots).isNotNull()
        assertThat(slots!!.first().portQuery).isEqualTo("Miami, FL, US")
        assertThat(slots.last().portQuery).isEmpty() // same return port = empty
    }

    @Test
    fun `loadCruise handles null cruise`() = runTest {
        every { cruiseRepository.getCruiseWithPorts(999L) } returns flowOf(null)

        viewModel.loadCruise(999L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.isLoading).isFalse()
        assertThat(viewModel.uiState.value.cruiseId).isEqualTo(0L)
    }

    // --- Validation ---

    @Test
    fun `saveFromSlots rejects blank name`() = runTest {
        viewModel.onNameChange("   ")
        val slots = listOf(
            ItinerarySlot(1, LocalDate.of(2026, 12, 14), "Miami",
                CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())),
            ItinerarySlot(2, LocalDate.of(2026, 12, 15)),
        )
        viewModel.saveFromSlots(slots)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Cruise name is required")
        assertThat(viewModel.uiState.value.isSaved).isFalse()
    }

    @Test
    fun `saveFromSlots rejects missing embark port`() = runTest {
        viewModel.onNameChange("Test")
        val slots = listOf(
            ItinerarySlot(1, LocalDate.of(2026, 12, 14), "Miami"), // no resolvedPort
            ItinerarySlot(2, LocalDate.of(2026, 12, 15)),
        )
        viewModel.saveFromSlots(slots)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Select an embark port")
    }

    // --- Save ---

    @Test
    fun `saveFromSlots creates cruise with correct structure`() = runTest {
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 5L

        viewModel.onNameChange("Caribbean")
        viewModel.onSailDateChange(LocalDate.of(2026, 12, 14))

        val depPort = CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())
        val cozPort = CruisePort("coz", "Cozumel", 20.43, -86.92, "", emptyList())
        val slots = listOf(
            ItinerarySlot(1, LocalDate.of(2026, 12, 14), "Miami", depPort),
            ItinerarySlot(2, LocalDate.of(2026, 12, 15)), // sea day
            ItinerarySlot(3, LocalDate.of(2026, 12, 16), "Cozumel", cozPort),
            ItinerarySlot(4, LocalDate.of(2026, 12, 17)), // debark (same as embark)
        )
        viewModel.saveFromSlots(slots)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.isSaved).isTrue()
        assertThat(viewModel.uiState.value.savedCruiseId).isEqualTo(5L)
        coVerify {
            cruiseRepository.saveCruise(
                match { it.name == "Caribbean" && it.departurePortName == "Miami" && it.returnPortName == null },
                match { ports -> ports.size == 2 && ports[0].type == PortType.DEPARTURE && ports[1].type == PortType.RETURN },
                match { ports -> ports.size == 2 }, // sea day + cozumel
                any(),
            )
        }
    }

    @Test
    fun `saveFromSlots with different debark port sets returnPortName`() = runTest {
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 5L

        viewModel.onNameChange("Transatlantic")
        viewModel.onSailDateChange(LocalDate.of(2026, 12, 14))

        val depPort = CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())
        val retPort = CruisePort("ret", "Barcelona", 41.39, 2.17, "", emptyList())
        val slots = listOf(
            ItinerarySlot(1, LocalDate.of(2026, 12, 14), "Miami", depPort),
            ItinerarySlot(2, LocalDate.of(2026, 12, 15)),
            ItinerarySlot(3, LocalDate.of(2026, 12, 16), "Barcelona", retPort),
        )
        viewModel.saveFromSlots(slots)
        advanceUntilIdle()

        coVerify {
            cruiseRepository.saveCruise(
                match { it.returnPortName == "Barcelona" },
                any(), any(), any(),
            )
        }
    }

    @Test
    fun `saveFromSlots sets error on exception`() = runTest {
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } throws RuntimeException("DB error")

        viewModel.onNameChange("Test")
        viewModel.onSailDateChange(LocalDate.of(2026, 12, 14))
        val depPort = CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())
        val slots = listOf(
            ItinerarySlot(1, LocalDate.of(2026, 12, 14), "Miami", depPort),
            ItinerarySlot(2, LocalDate.of(2026, 12, 15)),
        )
        viewModel.saveFromSlots(slots)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("DB error")
        assertThat(viewModel.uiState.value.isSaved).isFalse()
    }

    @Test
    fun `saveFromSlots preserves notes on intermediate ports`() = runTest {
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 5L

        viewModel.onNameChange("Test")
        viewModel.onSailDateChange(LocalDate.of(2026, 12, 14))
        val depPort = CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())
        val slots = listOf(
            ItinerarySlot(1, LocalDate.of(2026, 12, 14), "Miami", depPort),
            ItinerarySlot(2, LocalDate.of(2026, 12, 15), notes = "Rest day"),
            ItinerarySlot(3, LocalDate.of(2026, 12, 16)),
        )
        viewModel.saveFromSlots(slots)
        advanceUntilIdle()

        coVerify {
            cruiseRepository.saveCruise(
                any(), any(),
                match { ports -> ports[0].notes == "Rest day" },
                any(),
            )
        }
    }

    // --- Weather Invalidation ---

    @Test
    fun `saveFromSlots invalidates weather when sail date changed`() = runTest {
        val cwp = cruiseWithPorts(
            cruise = cruise(id = 1, name = "Test", sailDate = LocalDate.of(2026, 12, 14)),
            ports = listOf(
                port(id = 10, cruiseId = 1, portName = "Miami", type = PortType.DEPARTURE,
                    latitude = 25.77, longitude = -80.19, date = LocalDate.of(2026, 12, 14)),
                port(id = 11, cruiseId = 1, portName = "Cozumel",
                    date = LocalDate.of(2026, 12, 15)),
                port(id = 12, cruiseId = 1, portName = "Miami", type = PortType.RETURN,
                    latitude = 25.77, longitude = -80.19, date = LocalDate.of(2026, 12, 16),
                    sortOrder = Int.MAX_VALUE),
            ),
        )
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { cruiseRepository.saveCruise(any(), any(), any(), any()) } returns 1L

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        // Change sail date
        viewModel.onSailDateChange(LocalDate.of(2026, 12, 20))

        val depPort = CruisePort("dep", "Miami", 25.77, -80.19, "", emptyList())
        val slots = listOf(
            ItinerarySlot(1, LocalDate.of(2026, 12, 20), "Miami", depPort),
            ItinerarySlot(2, LocalDate.of(2026, 12, 21)),
            ItinerarySlot(3, LocalDate.of(2026, 12, 22)),
        )
        viewModel.saveFromSlots(slots)
        advanceUntilIdle()

        coVerify { weatherRepository.invalidateWeatherForPorts(any()) }
    }

    // --- Error ---

    @Test
    fun `clearError clears error state`() {
        viewModel.onNameChange("")
        viewModel.saveFromSlots(emptyList())
        viewModel.clearError()
        assertThat(viewModel.uiState.value.error).isNull()
    }
}
