// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import dagger.hilt.android.AndroidEntryPoint
import org.jewzaam.cruiseweather.ui.navigation.NavGraph
import org.jewzaam.cruiseweather.ui.theme.CruiseWeatherTheme

@AndroidEntryPoint
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            CruiseWeatherTheme {
                NavGraph()
            }
        }
    }
}
