// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.ui.comparison

import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.jewzaam.cruiseweather.cruise
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.domain.model.CruiseComparison
import org.jewzaam.cruiseweather.domain.usecase.CompareCruisesUseCase
import org.junit.After
import org.junit.Before
import org.junit.Test

@OptIn(ExperimentalCoroutinesApi::class)
class ComparisonViewModelTest {

    private val cruiseRepository = mockk<CruiseRepository>()
    private val compareCruisesUseCase = mockk<CompareCruisesUseCase>()
    private val testDispatcher = StandardTestDispatcher()
    private lateinit var viewModel: ComparisonViewModel

    @Before
    fun setUp() {
        Dispatchers.setMain(testDispatcher)
        every { cruiseRepository.getAllCruises() } returns flowOf(
            listOf(cruise(id = 1, name = "A"), cruise(id = 2, name = "B"), cruise(id = 3, name = "C")),
        )
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    private fun createViewModel() {
        viewModel = ComparisonViewModel(
            cruiseRepository = cruiseRepository,
            compareCruisesUseCase = compareCruisesUseCase,
        )
    }

    @Test
    fun `toggleCruise adds cruise to selection`() = runTest {
        createViewModel()
        // Start collecting uiState to activate WhileSubscribed
        val collectJob = launch(UnconfinedTestDispatcher(testScheduler)) {
            viewModel.uiState.collect {}
        }
        advanceUntilIdle()

        viewModel.toggleCruise(1L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.selectedIds).contains(1L)
        collectJob.cancel()
    }

    @Test
    fun `toggleCruise removes cruise on second toggle`() = runTest {
        createViewModel()
        val collectJob = launch(UnconfinedTestDispatcher(testScheduler)) {
            viewModel.uiState.collect {}
        }
        advanceUntilIdle()

        viewModel.toggleCruise(1L)
        advanceUntilIdle()
        viewModel.toggleCruise(1L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.selectedIds).doesNotContain(1L)
        collectJob.cancel()
    }

    @Test
    fun `comparison triggers when 2 or more cruises selected`() = runTest {
        val comparison = mockk<CruiseComparison>()
        coEvery { compareCruisesUseCase(cruiseIds = any()) } returns listOf(comparison)

        createViewModel()
        val collectJob = launch(UnconfinedTestDispatcher(testScheduler)) {
            viewModel.uiState.collect {}
        }
        advanceUntilIdle()

        viewModel.toggleCruise(1L)
        advanceUntilIdle()
        viewModel.toggleCruise(2L)
        advanceUntilIdle()

        coVerify { compareCruisesUseCase(cruiseIds = match { it.containsAll(listOf(1L, 2L)) }) }
        collectJob.cancel()
    }

    @Test
    fun `comparisons cleared when selection drops below 2`() = runTest {
        coEvery { compareCruisesUseCase(cruiseIds = any()) } returns emptyList()

        createViewModel()
        val collectJob = launch(UnconfinedTestDispatcher(testScheduler)) {
            viewModel.uiState.collect {}
        }
        advanceUntilIdle()

        viewModel.toggleCruise(1L)
        advanceUntilIdle()
        viewModel.toggleCruise(2L)
        advanceUntilIdle()
        viewModel.toggleCruise(2L) // deselect
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.comparisons).isEmpty()
        collectJob.cancel()
    }

    @Test
    fun `comparison cancels previous job on rapid toggles`() = runTest {
        coEvery { compareCruisesUseCase(cruiseIds = any()) } returns emptyList()

        createViewModel()
        val collectJob = launch(UnconfinedTestDispatcher(testScheduler)) {
            viewModel.uiState.collect {}
        }
        advanceUntilIdle()

        // Rapidly toggle to trigger and cancel
        viewModel.toggleCruise(1L)
        viewModel.toggleCruise(2L)
        viewModel.toggleCruise(3L) // now 3 selected, new comparison
        advanceUntilIdle()

        // Should complete without error
        assertThat(viewModel.uiState.value.isLoading).isFalse()
        collectJob.cancel()
    }

    @Test
    fun `error set when comparison fails`() = runTest {
        coEvery { compareCruisesUseCase(cruiseIds = any()) } throws RuntimeException("Comparison failed")

        createViewModel()
        val collectJob = launch(UnconfinedTestDispatcher(testScheduler)) {
            viewModel.uiState.collect {}
        }
        advanceUntilIdle()

        viewModel.toggleCruise(1L)
        advanceUntilIdle()
        viewModel.toggleCruise(2L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Comparison failed")
        collectJob.cancel()
    }

    @Test
    fun `single selection does not trigger comparison`() = runTest {
        createViewModel()
        val collectJob = launch(UnconfinedTestDispatcher(testScheduler)) {
            viewModel.uiState.collect {}
        }
        advanceUntilIdle()

        viewModel.toggleCruise(1L)
        advanceUntilIdle()

        coVerify(exactly = 0) { compareCruisesUseCase(cruiseIds = any()) }
        assertThat(viewModel.uiState.value.comparisons).isEmpty()
        collectJob.cancel()
    }

    @Test
    fun `uiState includes all cruises from repository`() = runTest {
        createViewModel()
        val collectJob = launch(UnconfinedTestDispatcher(testScheduler)) {
            viewModel.uiState.collect {}
        }
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.allCruises).hasSize(3)
        collectJob.cancel()
    }
}
