// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.data.local

import com.google.common.truth.Truth.assertThat
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.junit.Test
import java.time.Instant
import java.time.LocalDate

class ConvertersTest {

    private val converters = Converters()

    // --- LocalDate ---

    @Test
    fun `fromLocalDate parses valid date string`() {
        val result = converters.fromLocalDate("2026-12-14")
        assertThat(result).isEqualTo(LocalDate.of(2026, 12, 14))
    }

    @Test
    fun `fromLocalDate returns null for null input`() {
        assertThat(converters.fromLocalDate(null)).isNull()
    }

    @Test
    fun `toLocalDate formats date to ISO string`() {
        val result = converters.toLocalDate(LocalDate.of(2026, 12, 14))
        assertThat(result).isEqualTo("2026-12-14")
    }

    @Test
    fun `toLocalDate returns null for null input`() {
        assertThat(converters.toLocalDate(null)).isNull()
    }

    @Test
    fun `LocalDate round-trip preserves value`() {
        val original = LocalDate.of(2027, 2, 28)
        val serialized = converters.toLocalDate(original)
        val deserialized = converters.fromLocalDate(serialized)
        assertThat(deserialized).isEqualTo(original)
    }

    // --- Instant ---

    @Test
    fun `fromInstant converts epoch millis to Instant`() {
        val millis = 1700000000000L
        val result = converters.fromInstant(millis)
        assertThat(result).isEqualTo(Instant.ofEpochMilli(millis))
    }

    @Test
    fun `fromInstant returns null for null input`() {
        assertThat(converters.fromInstant(null)).isNull()
    }

    @Test
    fun `toInstant converts Instant to epoch millis`() {
        val instant = Instant.ofEpochMilli(1700000000000L)
        val result = converters.toInstant(instant)
        assertThat(result).isEqualTo(1700000000000L)
    }

    @Test
    fun `toInstant returns null for null input`() {
        assertThat(converters.toInstant(null)).isNull()
    }

    @Test
    fun `Instant round-trip preserves value`() {
        val original = Instant.ofEpochMilli(1700000000123L)
        val serialized = converters.toInstant(original)
        val deserialized = converters.fromInstant(serialized)
        assertThat(deserialized).isEqualTo(original)
    }

    // --- PortType ---

    @Test
    fun `fromPortType converts valid enum name`() {
        assertThat(converters.fromPortType("DEPARTURE")).isEqualTo(PortType.DEPARTURE)
        assertThat(converters.fromPortType("PORT_OF_CALL")).isEqualTo(PortType.PORT_OF_CALL)
        assertThat(converters.fromPortType("RETURN")).isEqualTo(PortType.RETURN)
    }

    @Test
    fun `fromPortType returns null for null input`() {
        assertThat(converters.fromPortType(null)).isNull()
    }

    @Test
    fun `toPortType converts enum to name string`() {
        assertThat(converters.toPortType(PortType.DEPARTURE)).isEqualTo("DEPARTURE")
        assertThat(converters.toPortType(PortType.PORT_OF_CALL)).isEqualTo("PORT_OF_CALL")
        assertThat(converters.toPortType(PortType.RETURN)).isEqualTo("RETURN")
    }

    @Test
    fun `toPortType returns null for null input`() {
        assertThat(converters.toPortType(null)).isNull()
    }

    @Test
    fun `PortType round-trip preserves all values`() {
        for (type in PortType.entries) {
            val serialized = converters.toPortType(type)
            val deserialized = converters.fromPortType(serialized)
            assertThat(deserialized).isEqualTo(type)
        }
    }
}
