// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.data.local

import com.google.common.truth.Truth.assertThat
import com.google.common.truth.Truth.assertWithMessage
import org.junit.Test

/**
 * Ensures every schema version has a corresponding migration and that
 * no version gaps exist. If this test fails, a Migration object is missing
 * in Migrations.kt for a schema version bump.
 */
class MigrationCoverageTest {

    private val currentVersion = 4 // Must match AppDatabase @Database(version = ...)

    @Test
    fun `all versions from 1 to current have migrations with no gaps`() {
        val coveredSteps = ALL_MIGRATIONS.map { it.startVersion to it.endVersion }.toSet()
        for (v in 1 until currentVersion) {
            assertWithMessage("Missing migration from version $v to ${v + 1}")
                .that(coveredSteps)
                .contains(v to v + 1)
        }
    }

    @Test
    fun `no migration jumps over versions`() {
        for (migration in ALL_MIGRATIONS) {
            assertWithMessage(
                "Migration ${migration.startVersion}→${migration.endVersion} " +
                    "skips versions — each migration must be exactly +1",
            )
                .that(migration.endVersion - migration.startVersion)
                .isEqualTo(1)
        }
    }

    @Test
    fun `ALL_MIGRATIONS is not empty`() {
        assertThat(ALL_MIGRATIONS).isNotEmpty()
    }

    @Test
    fun `migrations cover up to current database version`() {
        val maxEndVersion = ALL_MIGRATIONS.maxOf { it.endVersion }
        assertWithMessage("Highest migration end version must match current DB version")
            .that(maxEndVersion)
            .isEqualTo(currentVersion)
    }

    @Test
    fun `migrations start from version 1`() {
        val minStartVersion = ALL_MIGRATIONS.minOf { it.startVersion }
        assertWithMessage("Migrations must start from version 1")
            .that(minStartVersion)
            .isEqualTo(1)
    }
}
