// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.di

import android.content.Context
import androidx.room.Room
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import org.jewzaam.cruiseweather.data.local.ALL_MIGRATIONS
import org.jewzaam.cruiseweather.data.local.AppDatabase
import org.jewzaam.cruiseweather.data.local.CruiseDao
import org.jewzaam.cruiseweather.data.local.PortOfCallDao
import org.jewzaam.cruiseweather.data.local.WeatherDao
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object DatabaseModule {

    @Provides
    @Singleton
    fun provideDatabase(@ApplicationContext context: Context): AppDatabase =
        Room.databaseBuilder(
            context = context,
            klass = AppDatabase::class.java,
            name = "cruise_weather.db",
        )
            .addMigrations(*ALL_MIGRATIONS)
            .build()

    @Provides
    fun provideCruiseDao(db: AppDatabase): CruiseDao = db.cruiseDao()

    @Provides
    fun providePortOfCallDao(db: AppDatabase): PortOfCallDao = db.portOfCallDao()

    @Provides
    fun provideWeatherDao(db: AppDatabase): WeatherDao = db.weatherDao()
}
