// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.domain.model

import com.google.common.truth.Truth.assertThat
import org.jewzaam.cruiseweather.cruise
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.port
import org.junit.Test
import java.time.LocalDate

class CruiseWithPortsTest {

    @Test
    fun `departurePort returns the DEPARTURE port`() {
        val dep = port(id = 1, type = PortType.DEPARTURE, portName = "Miami")
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = listOf(dep))
        assertThat(cwp.departurePort).isEqualTo(dep)
    }

    @Test
    fun `departurePort returns null when no departure exists`() {
        val poc = port(id = 1, type = PortType.PORT_OF_CALL)
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = listOf(poc))
        assertThat(cwp.departurePort).isNull()
    }

    @Test
    fun `returnPort returns the RETURN port`() {
        val ret = port(id = 2, type = PortType.RETURN, portName = "Miami")
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = listOf(ret))
        assertThat(cwp.returnPort).isEqualTo(ret)
    }

    @Test
    fun `returnPort returns null when no return exists`() {
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = emptyList())
        assertThat(cwp.returnPort).isNull()
    }

    @Test
    fun `portsOfCall filters to PORT_OF_CALL only`() {
        val dep = port(id = 1, type = PortType.DEPARTURE)
        val poc1 = port(id = 2, type = PortType.PORT_OF_CALL, portName = "Cozumel")
        val poc2 = port(id = 3, type = PortType.PORT_OF_CALL, portName = "Jamaica")
        val ret = port(id = 4, type = PortType.RETURN)
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = listOf(dep, poc1, poc2, ret))
        assertThat(cwp.portsOfCall).containsExactly(poc1, poc2)
    }

    @Test
    fun `portsOfCall returns empty list when no ports of call exist`() {
        val dep = port(id = 1, type = PortType.DEPARTURE)
        val ret = port(id = 2, type = PortType.RETURN)
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = listOf(dep, ret))
        assertThat(cwp.portsOfCall).isEmpty()
    }

    @Test
    fun `allPortsChronological sorts by date then sortOrder`() {
        val ret = port(id = 3, type = PortType.RETURN, date = LocalDate.of(2026, 12, 21), sortOrder = Int.MAX_VALUE)
        val dep = port(id = 1, type = PortType.DEPARTURE, date = LocalDate.of(2026, 12, 14), sortOrder = 0)
        val poc = port(id = 2, type = PortType.PORT_OF_CALL, date = LocalDate.of(2026, 12, 16), sortOrder = 1)
        // Add out of order
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = listOf(ret, poc, dep))
        val sorted = cwp.allPortsChronological
        assertThat(sorted).containsExactly(dep, poc, ret).inOrder()
    }

    @Test
    fun `allPortsChronological with empty ports returns empty list`() {
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = emptyList())
        assertThat(cwp.allPortsChronological).isEmpty()
    }

    @Test
    fun `portsOfCall includes SEA_DAY and PORT_OF_CALL but excludes DEPARTURE and RETURN`() {
        val dep = port(id = 1, type = PortType.DEPARTURE, date = LocalDate.of(2026, 12, 14))
        val sea = port(id = 2, type = PortType.SEA_DAY, portName = "Sea Day", date = LocalDate.of(2026, 12, 15))
        val poc = port(id = 3, type = PortType.PORT_OF_CALL, portName = "Cozumel", date = LocalDate.of(2026, 12, 16))
        val ret = port(id = 4, type = PortType.RETURN, date = LocalDate.of(2026, 12, 21))
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = listOf(dep, sea, poc, ret))
        assertThat(cwp.portsOfCall).containsExactly(sea, poc)
    }

    @Test
    fun `allPortsChronological includes SEA_DAY`() {
        val dep = port(id = 1, type = PortType.DEPARTURE, date = LocalDate.of(2026, 12, 14), sortOrder = 0)
        val sea = port(id = 2, type = PortType.SEA_DAY, portName = "Sea Day", date = LocalDate.of(2026, 12, 15), sortOrder = 0)
        val poc = port(id = 3, type = PortType.PORT_OF_CALL, portName = "Cozumel", date = LocalDate.of(2026, 12, 16), sortOrder = 0)
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = listOf(dep, sea, poc))
        val sorted = cwp.allPortsChronological
        assertThat(sorted).containsExactly(dep, sea, poc).inOrder()
    }

    @Test
    fun `SEA_DAY is not departurePort or returnPort`() {
        val sea = port(id = 1, type = PortType.SEA_DAY, portName = "Sea Day")
        val cwp = CruiseWithPorts(cruise = cruise(id = 1), ports = listOf(sea))
        assertThat(cwp.departurePort).isNull()
        assertThat(cwp.returnPort).isNull()
    }
}
