// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.domain.model

import com.google.common.truth.Truth.assertThat
import org.jewzaam.cruiseweather.cruise
import org.junit.Test

class CruiseComparisonTest {

    private fun comparison(
        avgSunriseMinutes: Double = 390.0,
        avgSunsetMinutes: Double = 1080.0,
    ) = CruiseComparison(
        cruise = cruise(),
        avgTempHighF = 80.0,
        avgTempLowF = 70.0,
        rainProbabilityPct = 20.0,
        avgPrecipMm = 1.0,
        avgWindMaxMph = 12.0,
        avgUvIndexMax = 9.0,
        avgHumidityPct = 75.0,
        avgSunshineMins = 400.0,
        avgSunriseMinutes = avgSunriseMinutes,
        avgSunsetMinutes = avgSunsetMinutes,
        rainiestPortName = null,
        rainiestPortRainPct = null,
        portBreakdowns = emptyList(),
    )

    @Test
    fun `avgSunriseFormatted formats positive value correctly`() {
        val comp = comparison(avgSunriseMinutes = 390.0)
        assertThat(comp.avgSunriseFormatted).isEqualTo("6:30 AM")
    }

    @Test
    fun `avgSunriseFormatted returns dash for zero`() {
        val comp = comparison(avgSunriseMinutes = 0.0)
        assertThat(comp.avgSunriseFormatted).isEqualTo("\u2014")
    }

    @Test
    fun `avgSunsetFormatted formats positive value correctly`() {
        val comp = comparison(avgSunsetMinutes = 1080.0)
        assertThat(comp.avgSunsetFormatted).isEqualTo("6:00 PM")
    }

    @Test
    fun `avgSunsetFormatted returns dash for zero`() {
        val comp = comparison(avgSunsetMinutes = 0.0)
        assertThat(comp.avgSunsetFormatted).isEqualTo("\u2014")
    }
}
