// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.domain.model

import com.google.common.truth.Truth.assertThat
import org.jewzaam.cruiseweather.port
import org.jewzaam.cruiseweather.portWeatherSummary
import org.junit.Test

class PortWithWeatherTest {

    @Test
    fun `hasWeather returns true when summary exists`() {
        val pww = PortWithWeather(port = port(), summary = portWeatherSummary(), years = emptyList())
        assertThat(pww.hasWeather).isTrue()
    }

    @Test
    fun `hasWeather returns false when summary is null`() {
        val pww = PortWithWeather(port = port(), summary = null, years = emptyList())
        assertThat(pww.hasWeather).isFalse()
    }

    @Test
    fun `rainProbabilityPct computes percentage correctly`() {
        val summary = portWeatherSummary(rainyYearCount = 3, totalYearCount = 5)
        val pww = PortWithWeather(port = port(), summary = summary, years = emptyList())
        assertThat(pww.rainProbabilityPct).isWithin(0.01).of(60.0)
    }

    @Test
    fun `rainProbabilityPct returns null when totalYearCount is zero`() {
        val summary = portWeatherSummary(rainyYearCount = 0, totalYearCount = 0)
        val pww = PortWithWeather(port = port(), summary = summary, years = emptyList())
        assertThat(pww.rainProbabilityPct).isNull()
    }

    @Test
    fun `rainProbabilityPct returns null when summary is null`() {
        val pww = PortWithWeather(port = port(), summary = null, years = emptyList())
        assertThat(pww.rainProbabilityPct).isNull()
    }
}
