// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.remote

import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.client.request.parameter
import org.jewzaam.cruiseweather.data.remote.dto.GeocodingResponse
import org.jewzaam.cruiseweather.data.remote.dto.HistoricalWeatherResponse
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

private const val GEOCODING_BASE = "https://geocoding-api.open-meteo.com/v1"
private const val ARCHIVE_BASE = "https://archive-api.open-meteo.com/v1"

private const val DAILY_VARIABLES =
    "temperature_2m_max,temperature_2m_min,precipitation_sum," +
        "precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max," +
        "relative_humidity_2m_mean,uv_index_max,sunshine_duration," +
        "sunrise,sunset"

@Singleton
class OpenMeteoApi @Inject constructor(private val client: HttpClient) {

    suspend fun geocode(query: String, count: Int = 5): GeocodingResponse {
        Timber.d("Geocoding: query=%s count=%d", query, count)
        return client.get("$GEOCODING_BASE/search") {
            parameter("name", query)
            parameter("count", count)
            parameter("language", "en")
        }.body()
    }

    suspend fun fetchHistoricalWeather(
        latitude: Double,
        longitude: Double,
        startDate: String,
        endDate: String,
    ): HistoricalWeatherResponse {
        Timber.d(
            "Historical weather: lat=%f lon=%f start=%s end=%s",
            latitude,
            longitude,
            startDate,
            endDate,
        )
        return client.get("$ARCHIVE_BASE/archive") {
            parameter("latitude", latitude)
            parameter("longitude", longitude)
            parameter("start_date", startDate)
            parameter("end_date", endDate)
            parameter("daily", DAILY_VARIABLES)
            parameter("temperature_unit", "fahrenheit")
            parameter("wind_speed_unit", "mph")
            parameter("timezone", "auto")
        }.body()
    }
}
