// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.data.local.cruiseports

import com.google.common.truth.Truth.assertThat
import io.mockk.every
import io.mockk.mockk
import org.junit.Before
import org.junit.Test

class CruisePortMatcherTest {

    private val repository = mockk<CruisePortRepository>()
    private lateinit var matcher: CruisePortMatcher

    private val testPorts = listOf(
        CruisePort("cozumel-mx", "Cozumel, Mexico", 20.42, -86.92, "Mexico",
            listOf("Cozumel", "Isla de Cozumel", "San Miguel de Cozumel")),
        CruisePort("newcastle-gb", "Newcastle (Tyne), United Kingdom", 54.97, -1.61, "United Kingdom",
            listOf("Newcastle", "Newcastle upon Tyne", "Newcastle (Tyne)", "Port of Tyne")),
        CruisePort("civitavecchia-it", "Civitavecchia (Rome), Italy", 42.09, 11.79, "Italy",
            listOf("Civitavecchia", "Rome", "Civitavecchia (Rome)", "Port of Rome")),
        CruisePort("nassau-bs", "Nassau, Bahamas", 25.04, -77.35, "Bahamas",
            listOf("Nassau", "Nassau Bahamas", "New Providence")),
        CruisePort("southampton-gb", "Southampton, United Kingdom", 50.90, -1.40, "United Kingdom",
            listOf("Southampton", "Southampton England", "Southampton UK")),
    )

    @Before
    fun setUp() {
        every { repository.allPorts() } returns testPorts
        matcher = CruisePortMatcher(repository)
    }

    @Test
    fun `exact alias match returns the port`() {
        val results = matcher.search("Cozumel")
        assertThat(results).hasSize(1)
        assertThat(results[0].id).isEqualTo("cozumel-mx")
    }

    @Test
    fun `partial match returns correct port`() {
        val results = matcher.search("civi")
        assertThat(results).hasSize(1)
        assertThat(results[0].id).isEqualTo("civitavecchia-it")
    }

    @Test
    fun `parenthetical stripping matches aliases with parentheses`() {
        val results = matcher.search("Newcastle (Tyne)")
        assertThat(results).isNotEmpty()
        assertThat(results[0].id).isEqualTo("newcastle-gb")
    }

    @Test
    fun `port name with country format matches`() {
        val results = matcher.search("Nassau, Bahamas")
        assertThat(results).isNotEmpty()
        assertThat(results[0].id).isEqualTo("nassau-bs")
    }

    @Test
    fun `case insensitive matching`() {
        val results = matcher.search("SOUTHAMPTON")
        assertThat(results).hasSize(1)
        assertThat(results[0].id).isEqualTo("southampton-gb")
    }

    @Test
    fun `no results for garbage input`() {
        val results = matcher.search("xyzzyplugh")
        assertThat(results).isEmpty()
    }

    @Test
    fun `single character query returns empty`() {
        val results = matcher.search("c")
        assertThat(results).isEmpty()
    }

    @Test
    fun `results capped at limit`() {
        val results = matcher.search("na", limit = 2)
        assertThat(results.size).isAtMost(2)
    }

    @Test
    fun `exact match scores higher than partial`() {
        val results = matcher.search("Nassau")
        assertThat(results).isNotEmpty()
        assertThat(results[0].id).isEqualTo("nassau-bs")
    }

    @Test
    fun `country bonus boosts matching port`() {
        val results = matcher.search("Newcastle United Kingdom")
        assertThat(results).isNotEmpty()
        assertThat(results[0].id).isEqualTo("newcastle-gb")
    }

    @Test
    fun `displayName is also searchable`() {
        val results = matcher.search("Cozumel, Mexico")
        assertThat(results).isNotEmpty()
        assertThat(results[0].id).isEqualTo("cozumel-mx")
    }

    @Test
    fun `normalize strips parentheses and commas`() {
        assertThat(CruisePortMatcher.normalize("Newcastle (Tyne), England"))
            .isEqualTo("newcastle england")
    }

    @Test
    fun `word overlap matches multi-word aliases`() {
        val results = matcher.search("Port Tyne")
        assertThat(results).isNotEmpty()
        assertThat(results[0].id).isEqualTo("newcastle-gb")
    }
}
