// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.ui.util

import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle

/** Shared date formatters for consistent display across all screens. */
object DateFormatters {
    val MEDIUM_DATE: DateTimeFormatter = DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)
}
