// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.data.repository

import androidx.room.withTransaction
import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkStatic
import io.mockk.unmockkStatic
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.jewzaam.cruiseweather.data.local.AppDatabase
import org.jewzaam.cruiseweather.data.local.CruiseDao
import org.jewzaam.cruiseweather.data.local.PortOfCallDao
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.time.LocalDate

class CruiseRepositoryTest {

    private val db = mockk<AppDatabase>()
    private val cruiseDao = mockk<CruiseDao>()
    private val portOfCallDao = mockk<PortOfCallDao>()

    private lateinit var repository: CruiseRepository

    private val testCruise = Cruise(
        name = "Test Cruise",
        sailDate = LocalDate.of(2026, 12, 14),
        returnDate = LocalDate.of(2026, 12, 21),
        departurePortName = "Miami",
    )

    private val departurePorts = listOf(
        PortOfCall(
            cruiseId = 0L,
            portName = "Miami",
            date = LocalDate.of(2026, 12, 14),
            type = PortType.DEPARTURE,
            latitude = 25.77,
            longitude = -80.19,
            sortOrder = 0,
        ),
        PortOfCall(
            cruiseId = 0L,
            portName = "Miami",
            date = LocalDate.of(2026, 12, 21),
            type = PortType.RETURN,
            latitude = 25.77,
            longitude = -80.19,
            sortOrder = Int.MAX_VALUE,
        ),
    )

    @Before
    fun setUp() {
        mockkStatic("androidx.room.RoomDatabaseKt")
        coEvery { db.withTransaction(any<suspend () -> Any?>()) } coAnswers {
            val block = args[0] as suspend () -> Any?
            block()
        }
        repository = CruiseRepository(
            db = db,
            cruiseDao = cruiseDao,
            portOfCallDao = portOfCallDao,
        )
    }

    @After
    fun tearDown() {
        unmockkStatic("androidx.room.RoomDatabaseKt")
    }

    @Test
    fun `saveCruise inserts new cruise and departure-return ports`() = runTest {
        coEvery { cruiseDao.insert(any()) } returns 5L
        coEvery { portOfCallDao.insertAll(any()) } returns Unit

        val id = repository.saveCruise(cruise = testCruise, departurePorts = departurePorts)

        assertThat(id).isEqualTo(5L)
        coVerify { cruiseDao.insert(testCruise) }
        coVerify {
            portOfCallDao.insertAll(
                match { ports ->
                    ports.all { it.cruiseId == 5L && it.id == 0L } && ports.size == 2
                },
            )
        }
    }

    @Test
    fun `saveCruise updates existing cruise and replaces departure-return ports`() = runTest {
        val existingCruise = testCruise.copy(id = 3L)
        coEvery { cruiseDao.update(any()) } returns Unit
        coEvery { portOfCallDao.deleteDepartureReturnPorts(3L) } returns Unit
        coEvery { portOfCallDao.insertAll(any()) } returns Unit

        val id = repository.saveCruise(cruise = existingCruise, departurePorts = departurePorts)

        assertThat(id).isEqualTo(3L)
        coVerify { cruiseDao.update(match { it.id == 3L }) }
        coVerify { portOfCallDao.deleteDepartureReturnPorts(3L) }
        coVerify {
            portOfCallDao.insertAll(
                match { ports ->
                    ports.all { it.cruiseId == 3L && it.id == 0L }
                },
            )
        }
    }

    @Test
    fun `deleteCruise calls DAO delete`() = runTest {
        val cruise = testCruise.copy(id = 7L)
        coEvery { cruiseDao.delete(cruise) } returns Unit

        repository.deleteCruise(cruise)

        coVerify { cruiseDao.delete(cruise) }
    }

    @Test
    fun `getCruiseWithPorts combines cruise and ports flows`() = runTest {
        val cruise = testCruise.copy(id = 1L)
        val ports = listOf(
            PortOfCall(
                id = 10L,
                cruiseId = 1L,
                portName = "Miami",
                date = LocalDate.of(2026, 12, 14),
                type = PortType.DEPARTURE,
                sortOrder = 0,
            ),
        )
        every { cruiseDao.getCruiseById(1L) } returns flowOf(cruise)
        every { portOfCallDao.getPortsForCruise(1L) } returns flowOf(ports)

        val result = repository.getCruiseWithPorts(1L).first()

        assertThat(result).isNotNull()
        assertThat(result!!.cruise.name).isEqualTo("Test Cruise")
        assertThat(result.ports).hasSize(1)
        assertThat(result.ports.first().portName).isEqualTo("Miami")
    }
}
