// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.data.repository

import androidx.room.withTransaction
import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkStatic
import io.mockk.unmockkStatic
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.jewzaam.cruiseweather.data.local.AppDatabase
import org.jewzaam.cruiseweather.data.local.CruiseDao
import org.jewzaam.cruiseweather.data.local.PortOfCallDao
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.time.LocalDate

class CruiseRepositoryTest {

    private val db = mockk<AppDatabase>()
    private val cruiseDao = mockk<CruiseDao>()
    private val portOfCallDao = mockk<PortOfCallDao>()

    private lateinit var repository: CruiseRepository

    private val testCruise = Cruise(
        name = "Test Cruise",
        sailDate = LocalDate.of(2026, 12, 14),
        returnDate = LocalDate.of(2026, 12, 21),
        departurePortName = "Miami",
    )

    private val departurePorts = listOf(
        PortOfCall(
            cruiseId = 0L,
            portName = "Miami",
            date = LocalDate.of(2026, 12, 14),
            type = PortType.DEPARTURE,
            latitude = 25.77,
            longitude = -80.19,
            sortOrder = 0,
        ),
        PortOfCall(
            cruiseId = 0L,
            portName = "Miami",
            date = LocalDate.of(2026, 12, 21),
            type = PortType.RETURN,
            latitude = 25.77,
            longitude = -80.19,
            sortOrder = Int.MAX_VALUE,
        ),
    )

    @Before
    fun setUp() {
        mockkStatic("androidx.room.RoomDatabaseKt")
        coEvery { db.withTransaction(any<suspend () -> Any?>()) } coAnswers {
            val block = args[1] as suspend () -> Any?
            block()
        }
        repository = CruiseRepository(
            db = db,
            cruiseDao = cruiseDao,
            portOfCallDao = portOfCallDao,
        )
    }

    @After
    fun tearDown() {
        unmockkStatic("androidx.room.RoomDatabaseKt")
    }

    @Test
    fun `saveCruise inserts new cruise and departure-return ports`() = runTest {
        coEvery { cruiseDao.insert(any()) } returns 5L
        coEvery { portOfCallDao.insertAll(any()) } returns Unit

        val id = repository.saveCruise(cruise = testCruise, departurePorts = departurePorts)

        assertThat(id).isEqualTo(5L)
        coVerify { cruiseDao.insert(testCruise) }
        coVerify {
            portOfCallDao.insertAll(
                match { ports ->
                    ports.all { it.cruiseId == 5L && it.id == 0L } && ports.size == 2
                },
            )
        }
    }

    @Test
    fun `saveCruise updates existing cruise and updates departure-return ports in place`() = runTest {
        val existingCruise = testCruise.copy(id = 3L)
        val existingDep = departurePorts[0].copy(id = 10L, cruiseId = 3L)
        val existingRet = departurePorts[1].copy(id = 11L, cruiseId = 3L)
        coEvery { cruiseDao.update(any()) } returns Unit
        coEvery { portOfCallDao.getPortsForCruiseOnce(3L) } returns listOf(existingDep, existingRet)
        coEvery { portOfCallDao.update(any()) } returns Unit

        val id = repository.saveCruise(cruise = existingCruise, departurePorts = departurePorts)

        assertThat(id).isEqualTo(3L)
        coVerify { cruiseDao.update(match { it.id == 3L }) }
        // Should update existing ports, preserving their IDs
        coVerify { portOfCallDao.update(match { it.id == 10L && it.type == PortType.DEPARTURE }) }
        coVerify { portOfCallDao.update(match { it.id == 11L && it.type == PortType.RETURN }) }
        // Should NOT delete and recreate
        coVerify(exactly = 0) { portOfCallDao.deleteDepartureReturnPorts(any()) }
    }

    @Test
    fun `deleteCruise calls DAO delete`() = runTest {
        val cruise = testCruise.copy(id = 7L)
        coEvery { cruiseDao.delete(cruise) } returns Unit

        repository.deleteCruise(cruise)

        coVerify { cruiseDao.delete(cruise) }
    }

    @Test
    fun `getCruiseWithPorts combines cruise and ports flows`() = runTest {
        val cruise = testCruise.copy(id = 1L)
        val ports = listOf(
            PortOfCall(
                id = 10L,
                cruiseId = 1L,
                portName = "Miami",
                date = LocalDate.of(2026, 12, 14),
                type = PortType.DEPARTURE,
                sortOrder = 0,
            ),
        )
        every { cruiseDao.getCruiseById(1L) } returns flowOf(cruise)
        every { portOfCallDao.getPortsForCruise(1L) } returns flowOf(ports)

        val result = repository.getCruiseWithPorts(1L).first()

        assertThat(result).isNotNull()
        assertThat(result!!.cruise.name).isEqualTo("Test Cruise")
        assertThat(result.ports).hasSize(1)
        assertThat(result.ports.first().portName).isEqualTo("Miami")
    }

    @Test
    fun `getCruiseWithPorts returns null when cruise does not exist`() = runTest {
        every { cruiseDao.getCruiseById(999L) } returns flowOf(null)

        val result = repository.getCruiseWithPorts(999L).first()

        assertThat(result).isNull()
    }

    @Test
    fun `addPortOfCall delegates to DAO insert and returns id`() = runTest {
        val port = PortOfCall(
            cruiseId = 1L,
            portName = "Cozumel",
            date = LocalDate.of(2026, 12, 16),
            type = PortType.PORT_OF_CALL,
        )
        coEvery { portOfCallDao.insert(port) } returns 42L

        val id = repository.addPortOfCall(port)

        assertThat(id).isEqualTo(42L)
        coVerify { portOfCallDao.insert(port) }
    }

    @Test
    fun `updatePortOfCall delegates to DAO update`() = runTest {
        val port = PortOfCall(
            id = 10L,
            cruiseId = 1L,
            portName = "Updated Port",
            date = LocalDate.of(2026, 12, 17),
            type = PortType.PORT_OF_CALL,
        )
        coEvery { portOfCallDao.update(port) } returns Unit

        repository.updatePortOfCall(port)

        coVerify { portOfCallDao.update(port) }
    }

    @Test
    fun `deletePortOfCall delegates to DAO deleteById`() = runTest {
        coEvery { portOfCallDao.deleteById(10L) } returns Unit

        repository.deletePortOfCall(10L)

        coVerify { portOfCallDao.deleteById(10L) }
    }
}
