// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.repository

import androidx.room.withTransaction
import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.mockk
import io.mockk.mockkStatic
import io.mockk.unmockkStatic
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.jewzaam.cruiseweather.data.local.AppDatabase
import org.jewzaam.cruiseweather.data.local.PortOfCallDao
import org.jewzaam.cruiseweather.data.local.WeatherDao
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherYear
import org.jewzaam.cruiseweather.data.remote.OpenMeteoApi
import org.jewzaam.cruiseweather.data.remote.dto.DailyWeatherData
import org.jewzaam.cruiseweather.data.remote.dto.HistoricalWeatherResponse
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.time.Instant
import java.time.LocalDate

class WeatherRepositoryTest {

    private val db = mockk<AppDatabase>()
    private val weatherDao = mockk<WeatherDao>()
    private val portOfCallDao = mockk<PortOfCallDao>()
    private val api = mockk<OpenMeteoApi>()

    private lateinit var repository: WeatherRepository

    private val testPort = PortOfCall(
        id = 1L,
        cruiseId = 10L,
        portName = "Cozumel",
        date = LocalDate.of(2026, 12, 16),
        type = PortType.PORT_OF_CALL,
        latitude = 20.43,
        longitude = -86.92,
    )

    @Before
    fun setUp() {
        mockkStatic("androidx.room.RoomDatabaseKt")
        coEvery { db.withTransaction(any<suspend () -> Any?>()) } coAnswers {
            val block = args[0] as suspend () -> Any?
            block()
        }
        coEvery { weatherDao.deleteWeatherYearsForPort(any()) } returns Unit
        coEvery { weatherDao.deleteSummaryForPort(any()) } returns Unit
        coEvery { weatherDao.insertWeatherYears(any()) } returns Unit
        coEvery { weatherDao.insertSummary(any()) } returns Unit
        repository = WeatherRepository(
            db = db,
            weatherDao = weatherDao,
            portOfCallDao = portOfCallDao,
            api = api,
        )
    }

    @After
    fun tearDown() {
        unmockkStatic("androidx.room.RoomDatabaseKt")
    }

    @Test
    fun `fetchWeatherForPort returns NoCoordinates when port has no lat-lon`() = runTest {
        val portWithoutCoords = testPort.copy(latitude = null, longitude = null)
        val result = repository.fetchWeatherForPort(portWithoutCoords)
        assertThat(result).isEqualTo(WeatherFetchResult.NoCoordinates)
        coVerify(exactly = 0) { api.fetchHistoricalWeather(any(), any(), any(), any()) }
    }

    @Test
    fun `fetchWeatherForPort returns Failure when all year fetches fail`() = runTest {
        coEvery { api.fetchHistoricalWeather(any(), any(), any(), any()) } throws RuntimeException("network error")
        coEvery { weatherDao.getSummaryForPortOnce(any()) } returns null
        val result = repository.fetchWeatherForPort(testPort)
        assertThat(result).isInstanceOf(WeatherFetchResult.Failure::class.java)
    }

    @Test
    fun `fetchWeatherForPort stores summary and returns Success for full data`() = runTest {
        val fakeDaily = DailyWeatherData(
            time = listOf("2025-12-16"),
            tempMaxF = listOf(82.0),
            tempMinF = listOf(72.0),
            precipMm = listOf(0.0),
            precipHours = listOf(0.0),
            windMaxMph = listOf(12.0),
            windGustMph = listOf(18.0),
            humidityPct = listOf(75.0),
            uvIndexMax = listOf(9.0),
            sunshineDurationSec = listOf(25000.0),
        )
        val fakeResponse = HistoricalWeatherResponse(
            latitude = 20.43,
            longitude = -86.92,
            daily = fakeDaily,
        )
        coEvery { api.fetchHistoricalWeather(any(), any(), any(), any()) } returns fakeResponse
        coEvery { weatherDao.getSummaryForPortOnce(any()) } returns null

        val result = repository.fetchWeatherForPort(testPort)

        assertThat(result).isEqualTo(WeatherFetchResult.Success)
        coVerify { weatherDao.insertWeatherYears(any()) }
        coVerify { weatherDao.insertSummary(any()) }
    }

    @Test
    fun `isFetchNeeded returns true when no summary exists`() = runTest {
        coEvery { weatherDao.getSummaryForPortOnce(1L) } returns null
        assertThat(repository.isFetchNeeded(1L)).isTrue()
    }

    @Test
    fun `isFetchNeeded returns false when summary is fresh`() = runTest {
        val freshSummary = buildSummary(fetchedAt = Instant.now())
        coEvery { weatherDao.getSummaryForPortOnce(1L) } returns freshSummary
        assertThat(repository.isFetchNeeded(1L)).isFalse()
    }

    @Test
    fun `isFetchNeeded returns true when summary is stale`() = runTest {
        val staleSummary = buildSummary(
            fetchedAt = Instant.now().minusSeconds(8L * 24 * 3600), // 8 days ago
        )
        coEvery { weatherDao.getSummaryForPortOnce(1L) } returns staleSummary
        assertThat(repository.isFetchNeeded(1L)).isTrue()
    }

    @Test
    fun `computeSummary rain probability counts years above 1mm threshold`() = runTest {
        // 3 rainy, 2 dry — expect rainyYearCount = 3
        val fakeDaily = DailyWeatherData(
            time = listOf("2025-12-16"),
            tempMaxF = listOf(80.0),
            tempMinF = listOf(70.0),
            precipMm = listOf(0.0), // Will be overridden in the loop
            precipHours = listOf(0.0),
            windMaxMph = listOf(10.0),
            windGustMph = listOf(15.0),
            humidityPct = listOf(70.0),
            uvIndexMax = listOf(8.0),
            sunshineDurationSec = listOf(20000.0),
        )
        val rainyResponse = HistoricalWeatherResponse(
            latitude = 20.43,
            longitude = -86.92,
            daily = fakeDaily.copy(precipMm = listOf(5.0)),
        )
        val dryResponse = HistoricalWeatherResponse(
            latitude = 20.43,
            longitude = -86.92,
            daily = fakeDaily.copy(precipMm = listOf(0.0)),
        )

        var callCount = 0
        coEvery { api.fetchHistoricalWeather(any(), any(), any(), any()) } answers {
            callCount++
            // years: 2025, 2024, 2023 = rainy; 2022, 2021 = dry
            if (callCount <= 3) rainyResponse else dryResponse
        }
        coEvery { weatherDao.getSummaryForPortOnce(any()) } returns null

        repository.fetchWeatherForPort(testPort)

        coVerify {
            weatherDao.insertSummary(
                match { summary ->
                    summary.rainyYearCount == 3 && summary.totalYearCount == 5
                },
            )
        }
    }

    @Test
    fun `precipMm exactly 1_0 does not count as rainy`() = runTest {
        val fakeDaily = DailyWeatherData(
            time = listOf("2025-12-16"),
            tempMaxF = listOf(80.0),
            tempMinF = listOf(70.0),
            precipMm = listOf(1.0),
            precipHours = listOf(0.5),
            windMaxMph = listOf(10.0),
            windGustMph = listOf(15.0),
            humidityPct = listOf(70.0),
            uvIndexMax = listOf(8.0),
            sunshineDurationSec = listOf(20000.0),
        )
        val response = HistoricalWeatherResponse(
            latitude = 20.43,
            longitude = -86.92,
            daily = fakeDaily,
        )
        coEvery { api.fetchHistoricalWeather(any(), any(), any(), any()) } returns response

        repository.fetchWeatherForPort(testPort)

        coVerify {
            weatherDao.insertSummary(
                match { summary ->
                    summary.rainyYearCount == 0
                },
            )
        }
    }

    private fun buildSummary(fetchedAt: Instant): PortWeatherSummary = PortWeatherSummary(
        portOfCallId = 1L,
        dataSource = "historical_avg",
        yearsUsed = "2021,2022,2023,2024,2025",
        avgTempHighF = 80.0,
        avgTempLowF = 70.0,
        tempHighMin = 78.0,
        tempHighMax = 83.0,
        tempLowMin = 68.0,
        tempLowMax = 72.0,
        avgPrecipMm = 1.0,
        avgPrecipHours = 0.5,
        rainyYearCount = 1,
        totalYearCount = 5,
        avgWindMaxMph = 12.0,
        avgWindGustMph = 18.0,
        avgHumidityPct = 75.0,
        avgUvIndexMax = 9.0,
        avgSunshineMins = 400.0,
        fetchedAt = fetchedAt,
    )
}
