// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.time.LocalDate

@RunWith(AndroidJUnit4::class)
class CruiseDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var dao: CruiseDao

    @Before
    fun setUp() {
        database = Room.inMemoryDatabaseBuilder(
            context = ApplicationProvider.getApplicationContext(),
            klass = AppDatabase::class.java,
        ).build()
        dao = database.cruiseDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun insertAndRetrieveCruise() = runTest {
        val cruise = Cruise(
            name = "Test Cruise",
            sailDate = LocalDate.of(2026, 12, 14),
            returnDate = LocalDate.of(2026, 12, 21),
            departurePortName = "Miami",
        )
        val id = dao.insert(cruise)
        assertThat(id).isGreaterThan(0L)

        val retrieved = dao.getCruiseById(id).first()
        assertThat(retrieved).isNotNull()
        assertThat(retrieved!!.name).isEqualTo("Test Cruise")
        assertThat(retrieved.departurePortName).isEqualTo("Miami")
    }

    @Test
    fun getAllCruisesReturnsSortedBySailDate() = runTest {
        val cruise1 = Cruise(
            name = "Later Cruise",
            sailDate = LocalDate.of(2027, 3, 8),
            returnDate = LocalDate.of(2027, 3, 15),
            departurePortName = "Port Canaveral",
        )
        val cruise2 = Cruise(
            name = "Earlier Cruise",
            sailDate = LocalDate.of(2026, 12, 14),
            returnDate = LocalDate.of(2026, 12, 21),
            departurePortName = "Miami",
        )
        dao.insert(cruise1)
        dao.insert(cruise2)

        val cruises = dao.getAllCruises().first()
        assertThat(cruises).hasSize(2)
        assertThat(cruises[0].name).isEqualTo("Earlier Cruise")
        assertThat(cruises[1].name).isEqualTo("Later Cruise")
    }

    @Test
    fun deleteCruiseRemovesFromDatabase() = runTest {
        val cruise = Cruise(
            name = "Delete Me",
            sailDate = LocalDate.of(2026, 12, 14),
            returnDate = LocalDate.of(2026, 12, 21),
            departurePortName = "Miami",
        )
        val id = dao.insert(cruise)
        val inserted = dao.getCruiseById(id).first()!!

        dao.delete(inserted)

        val retrieved = dao.getCruiseById(id).first()
        assertThat(retrieved).isNull()
    }

    @Test
    fun updateCruisePersistsChanges() = runTest {
        val cruise = Cruise(
            name = "Original Name",
            sailDate = LocalDate.of(2026, 12, 14),
            returnDate = LocalDate.of(2026, 12, 21),
            departurePortName = "Miami",
        )
        val id = dao.insert(cruise)
        val inserted = dao.getCruiseById(id).first()!!

        dao.update(inserted.copy(name = "Updated Name"))

        val retrieved = dao.getCruiseById(id).first()
        assertThat(retrieved!!.name).isEqualTo("Updated Name")
    }
}
