// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.data.local

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.time.LocalDate

@RunWith(AndroidJUnit4::class)
class PortOfCallDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var cruiseDao: CruiseDao
    private lateinit var portDao: PortOfCallDao

    private var cruiseId = 0L

    @Before
    fun setUp() = runTest {
        database = Room.inMemoryDatabaseBuilder(
            context = ApplicationProvider.getApplicationContext(),
            klass = AppDatabase::class.java,
        ).build()
        cruiseDao = database.cruiseDao()
        portDao = database.portOfCallDao()

        cruiseId = cruiseDao.insert(
            Cruise(
                name = "Test Cruise",
                sailDate = LocalDate.of(2026, 12, 14),
                returnDate = LocalDate.of(2026, 12, 21),
                departurePortName = "Miami",
            ),
        )
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun insertAndRetrievePort() = runTest {
        val port = PortOfCall(
            cruiseId = cruiseId,
            portName = "Cozumel",
            date = LocalDate.of(2026, 12, 16),
            type = PortType.PORT_OF_CALL,
            latitude = 20.43,
            longitude = -86.92,
            sortOrder = 1,
        )
        val portId = portDao.insert(port)
        assertThat(portId).isGreaterThan(0L)

        val retrieved = portDao.getPortById(portId)
        assertThat(retrieved).isNotNull()
        assertThat(retrieved!!.portName).isEqualTo("Cozumel")
        assertThat(retrieved.latitude).isEqualTo(20.43)
    }

    @Test
    fun getPortsForCruiseReturnsSortedByDateThenSortOrder() = runTest {
        // Same date, different sortOrder
        portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Port B",
                date = LocalDate.of(2026, 12, 16),
                type = PortType.PORT_OF_CALL,
                sortOrder = 2,
            ),
        )
        portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Port A",
                date = LocalDate.of(2026, 12, 16),
                type = PortType.PORT_OF_CALL,
                sortOrder = 1,
            ),
        )
        // Earlier date
        portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Departure",
                date = LocalDate.of(2026, 12, 14),
                type = PortType.DEPARTURE,
                sortOrder = 0,
            ),
        )

        val ports = portDao.getPortsForCruise(cruiseId).first()
        assertThat(ports).hasSize(3)
        assertThat(ports[0].portName).isEqualTo("Departure")
        assertThat(ports[1].portName).isEqualTo("Port A")
        assertThat(ports[2].portName).isEqualTo("Port B")
    }

    @Test
    fun deleteDepartureReturnPortsOnlyDeletesDepartureAndReturnTypes() = runTest {
        portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Miami",
                date = LocalDate.of(2026, 12, 14),
                type = PortType.DEPARTURE,
                sortOrder = 0,
            ),
        )
        portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Cozumel",
                date = LocalDate.of(2026, 12, 16),
                type = PortType.PORT_OF_CALL,
                sortOrder = 1,
            ),
        )
        portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Miami",
                date = LocalDate.of(2026, 12, 21),
                type = PortType.RETURN,
                sortOrder = Int.MAX_VALUE,
            ),
        )

        portDao.deleteDepartureReturnPorts(cruiseId)

        val remaining = portDao.getPortsForCruise(cruiseId).first()
        assertThat(remaining).hasSize(1)
        assertThat(remaining.first().type).isEqualTo(PortType.PORT_OF_CALL)
    }

    @Test
    fun cascadeDeleteWhenCruiseIsDeleted() = runTest {
        portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Cozumel",
                date = LocalDate.of(2026, 12, 16),
                type = PortType.PORT_OF_CALL,
                sortOrder = 1,
            ),
        )
        portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Jamaica",
                date = LocalDate.of(2026, 12, 18),
                type = PortType.PORT_OF_CALL,
                sortOrder = 2,
            ),
        )

        val cruise = cruiseDao.getCruiseById(cruiseId).first()!!
        cruiseDao.delete(cruise)

        val ports = portDao.getPortsForCruise(cruiseId).first()
        assertThat(ports).isEmpty()
    }

    @Test
    fun deleteByIdRemovesSpecificPort() = runTest {
        val port1Id = portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Cozumel",
                date = LocalDate.of(2026, 12, 16),
                type = PortType.PORT_OF_CALL,
                sortOrder = 1,
            ),
        )
        portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Jamaica",
                date = LocalDate.of(2026, 12, 18),
                type = PortType.PORT_OF_CALL,
                sortOrder = 2,
            ),
        )

        portDao.deleteById(port1Id)

        val remaining = portDao.getPortsForCruise(cruiseId).first()
        assertThat(remaining).hasSize(1)
        assertThat(remaining.first().portName).isEqualTo("Jamaica")
    }
}
