// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.data.local

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherYear
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.time.Instant
import java.time.LocalDate

@RunWith(AndroidJUnit4::class)
class WeatherDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var weatherDao: WeatherDao
    private lateinit var cruiseDao: CruiseDao
    private lateinit var portDao: PortOfCallDao

    private var portId = 0L

    @Before
    fun setUp() = runTest {
        database = Room.inMemoryDatabaseBuilder(
            context = ApplicationProvider.getApplicationContext(),
            klass = AppDatabase::class.java,
        ).build()
        weatherDao = database.weatherDao()
        cruiseDao = database.cruiseDao()
        portDao = database.portOfCallDao()

        // Set up a cruise and port to satisfy foreign key constraints
        val cruiseId = cruiseDao.insert(
            Cruise(
                name = "Test",
                sailDate = LocalDate.of(2026, 12, 14),
                returnDate = LocalDate.of(2026, 12, 21),
                departurePortName = "Miami",
            ),
        )
        portId = portDao.insert(
            PortOfCall(
                cruiseId = cruiseId,
                portName = "Cozumel",
                date = LocalDate.of(2026, 12, 16),
                type = PortType.PORT_OF_CALL,
            ),
        )
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun insertAndRetrieveWeatherYear() = runTest {
        val year = PortWeatherYear(
            portOfCallId = portId,
            year = 2025,
            tempHighF = 82.0,
            tempLowF = 72.0,
            precipMm = 2.5,
            precipHours = 1.0,
            windMaxMph = 12.0,
            windGustMph = 18.0,
            humidityPct = 75.0,
            uvIndexMax = 9.0,
            sunshineDurationSec = 25000.0,
        )
        weatherDao.insertWeatherYear(year)

        val retrieved = weatherDao.getYearDataForPort(portId).first()
        assertThat(retrieved).hasSize(1)
        assertThat(retrieved[0].year).isEqualTo(2025)
        assertThat(retrieved[0].tempHighF).isEqualTo(82.0)
    }

    @Test
    fun insertSummaryReplacesDuplicate() = runTest {
        val summary = buildSummary(avgTempHighF = 80.0)
        weatherDao.insertSummary(summary)

        val updated = buildSummary(avgTempHighF = 85.0)
        weatherDao.insertSummary(updated)

        val retrieved = weatherDao.getSummaryForPort(portId).first()
        assertThat(retrieved).isNotNull()
        assertThat(retrieved!!.avgTempHighF).isEqualTo(85.0)
    }

    @Test
    fun deleteWeatherYearsClearsData() = runTest {
        weatherDao.insertWeatherYears(
            listOf(
                PortWeatherYear(
                    portOfCallId = portId,
                    year = 2025,
                    tempHighF = 82.0,
                    tempLowF = 72.0,
                    precipMm = 0.0,
                    precipHours = 0.0,
                    windMaxMph = 10.0,
                    windGustMph = 15.0,
                    humidityPct = 70.0,
                    uvIndexMax = 8.0,
                    sunshineDurationSec = 20000.0,
                ),
            ),
        )
        weatherDao.deleteWeatherYearsForPort(portId)

        val remaining = weatherDao.getYearDataForPort(portId).first()
        assertThat(remaining).isEmpty()
    }

    @Test
    fun getSummaryForPortOnceReturnsExistingSummary() = runTest {
        val summary = buildSummary(avgTempHighF = 82.0)
        weatherDao.insertSummary(summary)

        val result = weatherDao.getSummaryForPortOnce(portId)

        assertThat(result).isNotNull()
        assertThat(result!!.avgTempHighF).isEqualTo(82.0)
    }

    @Test
    fun getSummaryForPortOnceReturnsNullWhenMissing() = runTest {
        val result = weatherDao.getSummaryForPortOnce(portId)
        assertThat(result).isNull()
    }

    @Test
    fun getYearDataForPortOnceSortedByYear() = runTest {
        val year2023 = PortWeatherYear(
            portOfCallId = portId, year = 2023, tempHighF = 80.0, tempLowF = 70.0,
            precipMm = 0.0, precipHours = 0.0, windMaxMph = 10.0, windGustMph = 15.0,
            humidityPct = 70.0, uvIndexMax = 8.0, sunshineDurationSec = 20000.0,
        )
        val year2025 = year2023.copy(year = 2025, tempHighF = 84.0)
        val year2024 = year2023.copy(year = 2024, tempHighF = 82.0)
        // Insert out of order
        weatherDao.insertWeatherYears(listOf(year2025, year2023, year2024))

        val results = weatherDao.getYearDataForPortOnce(portId)

        assertThat(results).hasSize(3)
        assertThat(results.map { it.year }).isEqualTo(listOf(2023, 2024, 2025))
    }

    @Test
    fun deleteSummaryForPortRemovesSummary() = runTest {
        weatherDao.insertSummary(buildSummary(avgTempHighF = 80.0))

        weatherDao.deleteSummaryForPort(portId)

        val result = weatherDao.getSummaryForPortOnce(portId)
        assertThat(result).isNull()
    }

    @Test
    fun insertWeatherYearsBatchInsertsMultiple() = runTest {
        val years = (2021..2025).map { year ->
            PortWeatherYear(
                portOfCallId = portId, year = year, tempHighF = 80.0 + year % 5,
                tempLowF = 70.0, precipMm = 0.0, precipHours = 0.0,
                windMaxMph = 10.0, windGustMph = 15.0, humidityPct = 70.0,
                uvIndexMax = 8.0, sunshineDurationSec = 20000.0,
            )
        }
        weatherDao.insertWeatherYears(years)

        val results = weatherDao.getYearDataForPortOnce(portId)
        assertThat(results).hasSize(5)
    }

    private fun buildSummary(avgTempHighF: Double): PortWeatherSummary = PortWeatherSummary(
        portOfCallId = portId,
        dataSource = "historical_avg",
        yearsUsed = "2021,2022,2023,2024,2025",
        avgTempHighF = avgTempHighF,
        avgTempLowF = 70.0,
        tempHighMin = 78.0,
        tempHighMax = 85.0,
        tempLowMin = 68.0,
        tempLowMax = 73.0,
        avgPrecipMm = 1.0,
        avgPrecipHours = 0.5,
        rainyYearCount = 1,
        totalYearCount = 5,
        avgWindMaxMph = 12.0,
        avgWindGustMph = 18.0,
        avgHumidityPct = 75.0,
        avgUvIndexMax = 9.0,
        avgSunshineMins = 400.0,
        fetchedAt = Instant.now(),
    )
}
