// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.ui.cruisedetail

import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.jewzaam.cruiseweather.cruise
import org.jewzaam.cruiseweather.cruiseWithPorts
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherFetchResult
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.PortWithWeather
import org.jewzaam.cruiseweather.domain.usecase.FetchWeatherForCruiseUseCase
import org.jewzaam.cruiseweather.domain.usecase.GeocodePortUseCase
import org.jewzaam.cruiseweather.domain.usecase.PortFetchResult
import org.jewzaam.cruiseweather.geocodingCandidate
import org.jewzaam.cruiseweather.port
import org.jewzaam.cruiseweather.portWeatherSummary
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.time.LocalDate

@OptIn(ExperimentalCoroutinesApi::class)
class CruiseDetailViewModelTest {

    private val cruiseRepository = mockk<CruiseRepository>(relaxed = true)
    private val weatherRepository = mockk<WeatherRepository>(relaxed = true)
    private val fetchWeatherUseCase = mockk<FetchWeatherForCruiseUseCase>()
    private val geocodePortUseCase = mockk<GeocodePortUseCase>()
    private val testDispatcher = StandardTestDispatcher()
    private lateinit var viewModel: CruiseDetailViewModel

    @Before
    fun setUp() {
        Dispatchers.setMain(testDispatcher)
        viewModel = CruiseDetailViewModel(
            cruiseRepository = cruiseRepository,
            weatherRepository = weatherRepository,
            fetchWeatherUseCase = fetchWeatherUseCase,
            geocodePortUseCase = geocodePortUseCase,
        )
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    // --- Loading ---

    @Test
    fun `loadCruise populates state from Flow`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.cruiseWithPorts).isEqualTo(cwp)
    }

    @Test
    fun `loadCruise builds weather map from summaries`() = runTest {
        val cwp = cruiseWithPorts()
        val summary = portWeatherSummary(portOfCallId = 11L)
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(10L) } returns null
        coEvery { weatherRepository.getPortWithWeather(11L) } returns PortWithWeather(
            port = port(id = 11), summary = summary, years = emptyList(),
        )
        coEvery { weatherRepository.getPortWithWeather(12L) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        val portWeather = viewModel.uiState.value.portWeather
        assertThat(portWeather).containsKey(11L)
        assertThat(portWeather[11L]).isEqualTo(summary)
    }

    @Test
    fun `loadCruise handles null cruise gracefully`() = runTest {
        every { cruiseRepository.getCruiseWithPorts(999L) } returns flowOf(null)

        viewModel.loadCruise(999L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.cruiseWithPorts).isNull()
    }

    // --- Auto-fetch ---

    @Test
    fun `auto-fetch triggers when port needs data`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns true
        coEvery { fetchWeatherUseCase(any(), any()) } returns emptyList()

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        coVerify { fetchWeatherUseCase(any(), any()) }
    }

    @Test
    fun `auto-fetch skips when all ports are fresh`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        coVerify(exactly = 0) { fetchWeatherUseCase(any(), any()) }
    }

    @Test
    fun `auto-fetch only runs once even on re-emission`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns true
        coEvery { fetchWeatherUseCase(any(), any()) } returns emptyList()

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        // Second load should not auto-fetch again
        viewModel.loadCruise(1L)
        advanceUntilIdle()

        coVerify(exactly = 1) { fetchWeatherUseCase(any(), any()) }
    }

    // --- Fetch Weather ---

    @Test
    fun `fetchWeather success sets success message`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { fetchWeatherUseCase(any(), any()) } returns listOf(
            PortFetchResult(port = port(), result = WeatherFetchResult.Success),
        )

        viewModel.loadCruise(1L)
        advanceUntilIdle()
        viewModel.fetchWeather()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.fetchMessage).isEqualTo("Weather updated successfully")
    }

    @Test
    fun `fetchWeather failure sets failure message`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { fetchWeatherUseCase(any(), any()) } returns listOf(
            PortFetchResult(port = port(), result = WeatherFetchResult.Failure("API error")),
        )

        viewModel.loadCruise(1L)
        advanceUntilIdle()
        viewModel.fetchWeather()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.fetchMessage).contains("failed")
    }

    @Test
    fun `fetchWeather noCoords sets geocode message`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { fetchWeatherUseCase(any(), any()) } returns listOf(
            PortFetchResult(port = port(latitude = null, longitude = null), result = WeatherFetchResult.NoCoordinates),
        )

        viewModel.loadCruise(1L)
        advanceUntilIdle()
        viewModel.fetchWeather()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.fetchMessage).contains("geocode")
    }

    @Test
    fun `fetchWeather empty results sets up to date message`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { fetchWeatherUseCase(any(), any()) } returns emptyList()

        viewModel.loadCruise(1L)
        advanceUntilIdle()
        viewModel.fetchWeather()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.fetchMessage).isEqualTo("All weather data is up to date")
    }

    // --- Port CRUD ---

    @Test
    fun `addPortOfCall triggers weather fetch for new port`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { cruiseRepository.addPortOfCall(any()) } returns 50L
        coEvery { weatherRepository.fetchWeatherForPort(any()) } returns WeatherFetchResult.Success

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        val newPort = port(id = 0, cruiseId = 1, portName = "Jamaica", latitude = 18.11, longitude = -77.30)
        viewModel.addPortOfCall(newPort)
        advanceUntilIdle()

        coVerify { cruiseRepository.addPortOfCall(newPort) }
        coVerify { weatherRepository.fetchWeatherForPort(match { it.id == 50L }) }
    }

    @Test
    fun `addPortOfCall sets error on exception`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { cruiseRepository.addPortOfCall(any()) } throws RuntimeException("Insert failed")

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        viewModel.addPortOfCall(port())
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Insert failed")
    }

    @Test
    fun `updatePortOfCall triggers weather fetch when coords change`() = runTest {
        val existingPort = port(id = 11, cruiseId = 1, latitude = 20.0, longitude = -87.0)
        val cwp = cruiseWithPorts(
            ports = listOf(
                port(id = 10, cruiseId = 1, portName = "Miami", type = PortType.DEPARTURE, date = LocalDate.of(2026, 12, 14)),
                existingPort,
                port(id = 12, cruiseId = 1, portName = "Miami", type = PortType.RETURN, date = LocalDate.of(2026, 12, 21), sortOrder = Int.MAX_VALUE),
            ),
        )
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { cruiseRepository.updatePortOfCall(any()) } returns Unit
        coEvery { weatherRepository.fetchWeatherForPort(any()) } returns WeatherFetchResult.Success

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        val updatedPort = existingPort.copy(latitude = 21.0, longitude = -88.0)
        viewModel.updatePortOfCall(updatedPort)
        advanceUntilIdle()

        coVerify { weatherRepository.fetchWeatherForPort(updatedPort) }
    }

    @Test
    fun `updatePortOfCall skips weather fetch when coords unchanged`() = runTest {
        val existingPort = port(id = 11, cruiseId = 1, latitude = 20.0, longitude = -87.0)
        val cwp = cruiseWithPorts(
            ports = listOf(
                port(id = 10, cruiseId = 1, portName = "Miami", type = PortType.DEPARTURE, date = LocalDate.of(2026, 12, 14)),
                existingPort,
                port(id = 12, cruiseId = 1, portName = "Miami", type = PortType.RETURN, date = LocalDate.of(2026, 12, 21), sortOrder = Int.MAX_VALUE),
            ),
        )
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { cruiseRepository.updatePortOfCall(any()) } returns Unit

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        val updatedPort = existingPort.copy(portName = "Cozumel Updated")
        viewModel.updatePortOfCall(updatedPort)
        advanceUntilIdle()

        coVerify(exactly = 0) { weatherRepository.fetchWeatherForPort(any()) }
    }

    @Test
    fun `deletePortOfCall delegates to repository`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { cruiseRepository.deletePortOfCall(11L) } returns Unit

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        viewModel.deletePortOfCall(11L)
        advanceUntilIdle()

        coVerify { cruiseRepository.deletePortOfCall(11L) }
    }

    @Test
    fun `deletePortOfCall sets error on exception`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { cruiseRepository.deletePortOfCall(any()) } throws RuntimeException("Delete failed")

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        viewModel.deletePortOfCall(11L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Delete failed")
    }

    // --- Utility ---

    @Test
    fun `clearMessage clears fetchMessage and error`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { fetchWeatherUseCase(any(), any()) } returns emptyList()

        viewModel.loadCruise(1L)
        advanceUntilIdle()
        viewModel.fetchWeather()
        advanceUntilIdle()

        viewModel.clearMessage()
        val state = viewModel.uiState.value
        assertThat(state.fetchMessage).isNull()
        assertThat(state.error).isNull()
    }

    @Test
    fun `geocodeQuery returns candidates from use case`() = runTest {
        val candidates = listOf(geocodingCandidate())
        coEvery { geocodePortUseCase(query = "Miami") } returns Result.success(candidates)

        val result = viewModel.geocodeQuery("Miami")

        assertThat(result).isEqualTo(candidates)
    }

    @Test
    fun `geocodeQuery returns empty list on failure`() = runTest {
        coEvery { geocodePortUseCase(query = "fail") } returns Result.failure(RuntimeException("error"))

        val result = viewModel.geocodeQuery("fail")

        assertThat(result).isEmpty()
    }
}
