// Generated By: Claude Code (Claude Opus 4.6)
package org.jewzaam.cruiseweather.ui.cruisedetail

import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.jewzaam.cruiseweather.cruiseWithPorts
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherFetchResult
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.PortWithWeather
import org.jewzaam.cruiseweather.domain.usecase.FetchWeatherForCruiseUseCase
import org.jewzaam.cruiseweather.port
import org.jewzaam.cruiseweather.portWeatherSummary
import org.junit.After
import org.junit.Before
import org.junit.Test

@OptIn(ExperimentalCoroutinesApi::class)
class CruiseDetailViewModelTest {

    private val cruiseRepository = mockk<CruiseRepository>(relaxed = true)
    private val weatherRepository = mockk<WeatherRepository>(relaxed = true)
    private val fetchWeatherUseCase = mockk<FetchWeatherForCruiseUseCase>()
    private val testDispatcher = StandardTestDispatcher()
    private lateinit var viewModel: CruiseDetailViewModel

    @Before
    fun setUp() {
        Dispatchers.setMain(testDispatcher)
        viewModel = CruiseDetailViewModel(
            cruiseRepository = cruiseRepository,
            weatherRepository = weatherRepository,
            fetchWeatherUseCase = fetchWeatherUseCase,
        )
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    // --- Loading ---

    @Test
    fun `loadCruise populates state from Flow`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.cruiseWithPorts).isEqualTo(cwp)
    }

    @Test
    fun `loadCruise builds weather map from summaries`() = runTest {
        val cwp = cruiseWithPorts()
        val summary = portWeatherSummary(portOfCallId = 11L)
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(10L) } returns null
        coEvery { weatherRepository.getPortWithWeather(11L) } returns PortWithWeather(
            port = port(id = 11), summary = summary, years = emptyList(),
        )
        coEvery { weatherRepository.getPortWithWeather(12L) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        val portWeather = viewModel.uiState.value.portWeather
        assertThat(portWeather).containsKey(11L)
        assertThat(portWeather[11L]).isEqualTo(summary)
    }

    @Test
    fun `loadCruise handles null cruise gracefully`() = runTest {
        every { cruiseRepository.getCruiseWithPorts(999L) } returns flowOf(null)

        viewModel.loadCruise(999L)
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.cruiseWithPorts).isNull()
    }

    // --- Auto-fetch ---

    @Test
    fun `auto-fetch triggers when isFetchNeeded returns true`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns true
        coEvery { fetchWeatherUseCase(any(), any()) } returns emptyList()

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        coVerify { fetchWeatherUseCase(any(), any()) }
    }

    @Test
    fun `auto-fetch does not re-fetch when data is fresh`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        coVerify(exactly = 0) { fetchWeatherUseCase(any(), any()) }
    }

    // --- Fetch Weather ---

    @Test
    fun `fetchWeather success sets success message`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { fetchWeatherUseCase(any(), any()) } returns listOf(
            org.jewzaam.cruiseweather.domain.usecase.PortFetchResult(port(id = 11), WeatherFetchResult.Success),
        )

        viewModel.loadCruise(1L)
        advanceUntilIdle()
        viewModel.fetchWeather()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.fetchMessage).isEqualTo("Weather updated successfully")
    }

    @Test
    fun `fetchWeather reports failures`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { fetchWeatherUseCase(any(), any()) } returns listOf(
            org.jewzaam.cruiseweather.domain.usecase.PortFetchResult(port(id = 11), WeatherFetchResult.Failure("timeout")),
        )

        viewModel.loadCruise(1L)
        advanceUntilIdle()
        viewModel.fetchWeather()
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.fetchMessage).contains("failed")
    }

    // --- Update Port (Notes) ---

    @Test
    fun `updatePortOfCall delegates to repository`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { cruiseRepository.updatePortOfCall(any()) } returns Unit

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        val updatedPort = port(id = 11, notes = "Visit the old town")
        viewModel.updatePortOfCall(updatedPort)
        advanceUntilIdle()

        coVerify { cruiseRepository.updatePortOfCall(updatedPort) }
    }

    @Test
    fun `updatePortOfCall sets error on exception`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { cruiseRepository.updatePortOfCall(any()) } throws RuntimeException("Update failed")

        viewModel.loadCruise(1L)
        advanceUntilIdle()

        viewModel.updatePortOfCall(port())
        advanceUntilIdle()

        assertThat(viewModel.uiState.value.error).isEqualTo("Update failed")
    }

    // --- Utility ---

    @Test
    fun `clearMessage clears fetchMessage and error`() = runTest {
        val cwp = cruiseWithPorts()
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(cwp)
        coEvery { weatherRepository.getPortWithWeather(any()) } returns null
        coEvery { weatherRepository.isFetchNeeded(any()) } returns false
        coEvery { fetchWeatherUseCase(any(), any()) } returns emptyList()

        viewModel.loadCruise(1L)
        advanceUntilIdle()
        viewModel.fetchWeather()
        advanceUntilIdle()

        viewModel.clearMessage()
        val state = viewModel.uiState.value
        assertThat(state.fetchMessage).isNull()
        assertThat(state.error).isNull()
    }
}
