// Generated By: Claude Code (claude-opus-4-6)
package org.jewzaam.cruiseweather.domain.usecase

import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.local.entity.PortWeatherSummary
import org.jewzaam.cruiseweather.data.repository.CruiseRepository
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.CruiseWithPorts
import org.jewzaam.cruiseweather.domain.model.PortWithWeather
import org.junit.Before
import org.junit.Test
import java.time.Instant
import java.time.LocalDate

class CompareCruisesUseCaseTest {

    private val cruiseRepository = mockk<CruiseRepository>()
    private val weatherRepository = mockk<WeatherRepository>()
    private lateinit var useCase: CompareCruisesUseCase

    private val cruise1 = Cruise(
        id = 1L,
        name = "Caribbean",
        sailDate = LocalDate.of(2026, 12, 14),
        returnDate = LocalDate.of(2026, 12, 21),
        departurePortName = "Miami",
    )

    private val cruise2 = Cruise(
        id = 2L,
        name = "Mediterranean",
        sailDate = LocalDate.of(2027, 6, 10),
        returnDate = LocalDate.of(2027, 6, 17),
        departurePortName = "Barcelona",
    )

    private val port1 = PortOfCall(
        id = 10L,
        cruiseId = 1L,
        portName = "Cozumel",
        date = LocalDate.of(2026, 12, 16),
        type = PortType.PORT_OF_CALL,
        latitude = 20.43,
        longitude = -86.92,
    )

    private val port2 = PortOfCall(
        id = 20L,
        cruiseId = 2L,
        portName = "Naples",
        date = LocalDate.of(2027, 6, 12),
        type = PortType.PORT_OF_CALL,
        latitude = 40.85,
        longitude = 14.27,
    )

    private fun buildSummary(
        portOfCallId: Long,
        avgTempHighF: Double = 80.0,
        avgTempLowF: Double = 70.0,
        rainyYearCount: Int = 1,
        totalYearCount: Int = 5,
    ) = PortWeatherSummary(
        portOfCallId = portOfCallId,
        dataSource = "historical_avg",
        yearsUsed = "2021,2022,2023,2024,2025",
        avgTempHighF = avgTempHighF,
        avgTempLowF = avgTempLowF,
        tempHighMin = avgTempHighF - 2.0,
        tempHighMax = avgTempHighF + 2.0,
        tempLowMin = avgTempLowF - 2.0,
        tempLowMax = avgTempLowF + 2.0,
        avgPrecipMm = 1.0,
        avgPrecipHours = 0.5,
        rainyYearCount = rainyYearCount,
        totalYearCount = totalYearCount,
        avgWindMaxMph = 12.0,
        avgWindGustMph = 18.0,
        avgHumidityPct = 75.0,
        avgUvIndexMax = 9.0,
        avgSunshineMins = 400.0,
        fetchedAt = Instant.now(),
    )

    @Before
    fun setUp() {
        useCase = CompareCruisesUseCase(
            cruiseRepository = cruiseRepository,
            weatherRepository = weatherRepository,
        )
    }

    @Test
    fun `returns comparison for cruises with weather data`() = runTest {
        val summary1 = buildSummary(portOfCallId = 10L)
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(
            CruiseWithPorts(cruise = cruise1, ports = listOf(port1)),
        )
        coEvery { weatherRepository.getPortWithWeather(10L) } returns PortWithWeather(
            port = port1,
            summary = summary1,
            years = emptyList(),
        )

        val results = useCase(cruiseIds = listOf(1L))

        assertThat(results).hasSize(1)
        assertThat(results.first().cruise.name).isEqualTo("Caribbean")
        assertThat(results.first().avgTempHighF).isWithin(0.01).of(80.0)
    }

    @Test
    fun `skips cruises with no weather summaries`() = runTest {
        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(
            CruiseWithPorts(cruise = cruise1, ports = listOf(port1)),
        )
        coEvery { weatherRepository.getPortWithWeather(10L) } returns PortWithWeather(
            port = port1,
            summary = null,
            years = emptyList(),
        )

        val results = useCase(cruiseIds = listOf(1L))

        assertThat(results).isEmpty()
    }

    @Test
    fun `computes rain probability from aggregate rainy and total year counts`() = runTest {
        // Port1: 3 rainy out of 5 years, Port2: 1 rainy out of 5 years
        // Aggregate: 4 rainy / 10 total = 40%
        val summary1 = buildSummary(portOfCallId = 10L, rainyYearCount = 3, totalYearCount = 5)
        val port1b = PortOfCall(
            id = 11L,
            cruiseId = 1L,
            portName = "Jamaica",
            date = LocalDate.of(2026, 12, 18),
            type = PortType.PORT_OF_CALL,
            latitude = 18.11,
            longitude = -77.30,
        )
        val summary1b = buildSummary(portOfCallId = 11L, rainyYearCount = 1, totalYearCount = 5)

        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(
            CruiseWithPorts(cruise = cruise1, ports = listOf(port1, port1b)),
        )
        coEvery { weatherRepository.getPortWithWeather(10L) } returns PortWithWeather(
            port = port1,
            summary = summary1,
            years = emptyList(),
        )
        coEvery { weatherRepository.getPortWithWeather(11L) } returns PortWithWeather(
            port = port1b,
            summary = summary1b,
            years = emptyList(),
        )

        val results = useCase(cruiseIds = listOf(1L))

        assertThat(results).hasSize(1)
        assertThat(results.first().rainProbabilityPct).isWithin(0.01).of(40.0)
    }

    @Test
    fun `identifies rainiest port`() = runTest {
        val port1b = PortOfCall(
            id = 11L,
            cruiseId = 1L,
            portName = "Jamaica",
            date = LocalDate.of(2026, 12, 18),
            type = PortType.PORT_OF_CALL,
            latitude = 18.11,
            longitude = -77.30,
        )
        // Cozumel: 4/5 rainy, Jamaica: 1/5 rainy
        val summaryRainy = buildSummary(portOfCallId = 10L, rainyYearCount = 4, totalYearCount = 5)
        val summaryDry = buildSummary(portOfCallId = 11L, rainyYearCount = 1, totalYearCount = 5)

        every { cruiseRepository.getCruiseWithPorts(1L) } returns flowOf(
            CruiseWithPorts(cruise = cruise1, ports = listOf(port1, port1b)),
        )
        coEvery { weatherRepository.getPortWithWeather(10L) } returns PortWithWeather(
            port = port1,
            summary = summaryRainy,
            years = emptyList(),
        )
        coEvery { weatherRepository.getPortWithWeather(11L) } returns PortWithWeather(
            port = port1b,
            summary = summaryDry,
            years = emptyList(),
        )

        val results = useCase(cruiseIds = listOf(1L))

        assertThat(results).hasSize(1)
        assertThat(results.first().rainiestPortName).isEqualTo("Cozumel")
        assertThat(results.first().rainiestPortRainPct).isWithin(0.01).of(80.0)
    }
}
