// Generated By: Claude Code (claude-sonnet-4-6)
package org.jewzaam.cruiseweather.domain.usecase

import com.google.common.truth.Truth.assertThat
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.mockk
import kotlinx.coroutines.test.runTest
import org.jewzaam.cruiseweather.data.local.entity.PortOfCall
import org.jewzaam.cruiseweather.data.local.entity.PortType
import org.jewzaam.cruiseweather.data.local.entity.Cruise
import org.jewzaam.cruiseweather.data.repository.WeatherFetchResult
import org.jewzaam.cruiseweather.data.repository.WeatherRepository
import org.jewzaam.cruiseweather.domain.model.CruiseWithPorts
import org.junit.Before
import org.junit.Test
import java.time.LocalDate

class FetchWeatherForCruiseUseCaseTest {

    private val weatherRepository = mockk<WeatherRepository>(relaxed = true)
    private lateinit var useCase: FetchWeatherForCruiseUseCase

    private val cruise = Cruise(
        id = 1L,
        name = "Test Cruise",
        sailDate = LocalDate.of(2026, 12, 14),
        returnDate = LocalDate.of(2026, 12, 21),
        departurePortName = "Miami",
    )

    private val portWithCoords = PortOfCall(
        id = 10L,
        cruiseId = 1L,
        portName = "Cozumel",
        date = LocalDate.of(2026, 12, 16),
        type = PortType.PORT_OF_CALL,
        latitude = 20.43,
        longitude = -86.92,
    )

    private val portWithoutCoords = PortOfCall(
        id = 11L,
        cruiseId = 1L,
        portName = "Nassau",
        date = LocalDate.of(2026, 12, 18),
        type = PortType.PORT_OF_CALL,
        latitude = null,
        longitude = null,
    )

    @Before
    fun setUp() {
        useCase = FetchWeatherForCruiseUseCase(weatherRepository = weatherRepository)
    }

    @Test
    fun `skips ports without coordinates and records NoCoordinates result`() = runTest {
        val cruiseWithPorts = CruiseWithPorts(
            cruise = cruise,
            ports = listOf(portWithoutCoords),
        )
        val results = useCase(cruiseWithPorts = cruiseWithPorts)
        assertThat(results).hasSize(1)
        assertThat(results.first().result).isEqualTo(WeatherFetchResult.NoCoordinates)
        coVerify(exactly = 0) { weatherRepository.fetchWeatherForPort(any()) }
    }

    @Test
    fun `skips fresh ports when forceRefresh is false`() = runTest {
        coEvery { weatherRepository.isFetchNeeded(portWithCoords.id) } returns false
        val cruiseWithPorts = CruiseWithPorts(cruise = cruise, ports = listOf(portWithCoords))
        val results = useCase(cruiseWithPorts = cruiseWithPorts, forceRefresh = false)
        assertThat(results).isEmpty()
        coVerify(exactly = 0) { weatherRepository.fetchWeatherForPort(any()) }
    }

    @Test
    fun `fetches weather for ports that need refresh`() = runTest {
        coEvery { weatherRepository.isFetchNeeded(portWithCoords.id) } returns true
        coEvery { weatherRepository.fetchWeatherForPort(portWithCoords) } returns WeatherFetchResult.Success
        val cruiseWithPorts = CruiseWithPorts(cruise = cruise, ports = listOf(portWithCoords))
        val results = useCase(cruiseWithPorts = cruiseWithPorts)
        assertThat(results).hasSize(1)
        assertThat(results.first().result).isEqualTo(WeatherFetchResult.Success)
    }

    @Test
    fun `returns empty list when cruise has no ports`() = runTest {
        val cruiseWithPorts = CruiseWithPorts(cruise = cruise, ports = emptyList())
        val results = useCase(cruiseWithPorts = cruiseWithPorts)
        assertThat(results).isEmpty()
    }

    @Test
    fun `returns results for both success and failure ports`() = runTest {
        val failPort = PortOfCall(
            id = 12L,
            cruiseId = 1L,
            portName = "Grand Cayman",
            date = LocalDate.of(2026, 12, 17),
            type = PortType.PORT_OF_CALL,
            latitude = 19.30,
            longitude = -81.38,
        )
        coEvery { weatherRepository.isFetchNeeded(portWithCoords.id) } returns true
        coEvery { weatherRepository.isFetchNeeded(failPort.id) } returns true
        coEvery { weatherRepository.fetchWeatherForPort(portWithCoords) } returns WeatherFetchResult.Success
        coEvery { weatherRepository.fetchWeatherForPort(failPort) } returns WeatherFetchResult.Failure("API error")

        val cruiseWithPorts = CruiseWithPorts(
            cruise = cruise,
            ports = listOf(portWithCoords, failPort),
        )
        val results = useCase(cruiseWithPorts = cruiseWithPorts)

        assertThat(results).hasSize(2)
        assertThat(results[0].result).isEqualTo(WeatherFetchResult.Success)
        assertThat(results[1].result).isInstanceOf(WeatherFetchResult.Failure::class.java)
    }
}
